/* =================================================================================================================================================================================== *
 *  v 4.2.0                                                                                                                                                                            *
 *                                                      C O M P O N E N T   :   A v a t a r   f i x e s   [ 1 p p v 3   ( 4 ! ) ]                                                      *
 *                                                                                                                                                                                     *
 * =================================================================================================================================================================================== *
 *  This component contains fixes and improvements for several avatar series of Baldur's Gate II character animations, along with updated paperdolls to better match the new content.  *
 *  Like whoa, this is huge..                                                                                                                                                          *
 *  Gwen fix: not anymore, since it now copies entire folders and gets rid of copy xxxxxA1... A9, G1... G19, CA, SA, SX, SX!                                                           *
 * =================================================================================================================================================================================== *
 *  change-log:                                                                                                                                                                        *
 *  -----------                                                                                                                                                                        *
 *      - Coding simplification:                                                                                                                                                       *
 *          Replaced `GAME_IS` conditions with variables checks to speed up install time.                                                                                              *
 *          Copied entire folders instead of infinite lines (COPY ~1pp/folder/file.ext~ ~override~ or ACTION_FOR_EACH file IN list BEGIN COPY ~1pp/folder/file.ext~ ~override~ END).   *
 * =================================================================================================================================================================================== */

SILENT
/* ===================================== *
 *  Improved Animation for Elven Female  *
 * ===================================== */

/* ----------------------------------------- *
 *  Female Elves with leather armour (EFB2)  *
 * ----------------------------------------- */

COPY ~1pp/core/1pp_avatars/f/efb2~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu OR is_iwd) BEGIN // GAME_IS ~totlm how bg2 tob tutu tutu_totsc ca~

	ACTION_FOR_EACH paperdoll IN ~cefc2inv~ ~ceff2inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

/* --------------------------------------------- *
 *  Elven Female with chainmail (EFB3)           *
 *  Female Elven Cleric with plate mail (EFC4)   *
 *  Female Elven Fighter with plate mail (EFF4)  *
 * --------------------------------------------- */

COPY ~1pp/core/1pp_avatars/f/efb3~ ~override~
COPY ~1pp/core/1pp_avatars/f/efc4~ ~override~
COPY ~1pp/core/1pp_avatars/f/eff4~ ~override~
 

/* ===================================== *
 *  Improved Animation for Female Human  *
 * ===================================== */

/* ----------------------------------------- *
 *  Female Human unarmoured (HFB1)           *
 *  Female Human with leather armour (HFB2)  *
 * ----------------------------------------- */

COPY ~1pp/core/1pp_avatars/f/hfb1~ ~override~
COPY ~1pp/core/1pp_avatars/f/hfb2~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu) BEGIN // GAME_IS ~bg2 tob tutu tutu_totsc ca~

	ACTION_FOR_EACH paperdoll IN ~chfc2inv~ ~chff2inv~ ~cofc2inv~ ~coff2inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

ACTION_IF (is_iwd) BEGIN // GAME_IS ~totlm how~

	ACTION_FOR_EACH paperdoll IN ~chfc2inv~ ~chff2inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

/* ------------------------------------- *
 *  Female Human with chain mail (HFB3)  *
 * ------------------------------------- */

COPY ~1pp/core/1pp_avatars/f/hfb3~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu) BEGIN // GAME_IS ~bg2 tob tutu tutu_totsc ca~

	ACTION_FOR_EACH paperdoll IN ~chfc3inv~ ~chff3inv~ ~cofc3inv~ ~coff3inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

ACTION_IF (is_iwd) BEGIN // GAME_IS ~totlm how~

	ACTION_FOR_EACH paperdoll IN ~chfc3inv~ ~chff3inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

/* -------------------------------------------- *
 *  Female Human Cleric with plate mail (HFC4)  *
 * -------------------------------------------- */

COPY ~1pp/core/1pp_avatars/f/hfc4~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu) BEGIN // GAME_IS ~bg2 tob tutu tutu_totsc ca~

	ACTION_FOR_EACH paperdoll IN ~chfc4inv~ ~cofc4inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

ACTION_IF (is_iwd) BEGIN // GAME_IS ~totlm how~

	ACTION_FOR_EACH paperdoll IN ~chfc4inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

/* --------------------------------------------- *
 *  Female Human Fighter with plate mail (HFF4)  *
 * --------------------------------------------- */

COPY ~1pp/core/1pp_avatars/f/hff4~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu) BEGIN // GAME_IS ~bg2 tob tutu tutu_totsc ca~

	ACTION_FOR_EACH paperdoll IN ~chff4inv~ ~coff4inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

ACTION_IF (is_iwd) BEGIN // GAME_IS ~totlm how~

	ACTION_FOR_EACH paperdoll IN ~chff4inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

/* ------------------------------------- *
 *  Female Human unarmoured mage (HFW1)  *
 * ------------------------------------- */

COPY ~1pp/core/1pp_avatars/f/hfw1~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu) BEGIN // GAME_IS ~bg2 tob tutu tutu_totsc ca~

	ACTION_FOR_EACH paperdoll IN ~chfw1inv~ ~cofw1inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

ACTION_IF (is_iwd) BEGIN // GAME_IS ~totlm how~

	ACTION_FOR_EACH paperdoll IN ~chfw1inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

/* ------------------------------------------ *
 *  Female Human mage with light robe (HFW2)  *
 * ------------------------------------------ */

COPY ~1pp/core/1pp_avatars/f/hfw2~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu) BEGIN // GAME_IS ~bg2 tob tutu tutu_totsc ca~

	ACTION_FOR_EACH paperdoll IN ~chfw2inv~ ~cofw2inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

ACTION_IF (is_iwd) BEGIN // GAME_IS ~totlm how~

	ACTION_FOR_EACH paperdoll IN ~chfw2inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END


/* ============================================================ *
 *  Improved Animation for Female Halflings (IFB1, IFB2, IFB3)  *
 * ============================================================ */

COPY ~1pp/core/1pp_avatars/f/ifb~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu OR is_iwd) BEGIN // (GAME_IS ~totlm how bg2 tob tutu tutu_totsc ca~)

	ACTION_FOR_EACH paperdoll IN ~cifc1inv~ ~ciff1inv~ ~cifc2inv~ ~ciff2inv~ ~cifc3inv~ ~ciff3inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END

/* -------------------------------------------- *
 *  Fix frame error in halfling clerics (IFC4)  *
 * -------------------------------------------- */

COPY ~1pp/core/1pp_avatars/f/ifc~ ~override~

COPY ~1pp/core/1pp_avatars/f/efw4/cefw4a6.bam~ ~override~

COPY ~1pp/core/1pp_avatars/m/emw4/cemw4a6.bam~ ~override~


/* ======================================================= *
 *  Improved Animation for Dwarves with chain mail (DMB3)  *
 * ======================================================= */

COPY ~1pp/core/1pp_avatars/m/dmb3~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu OR is_iwd) BEGIN // (GAME_IS ~totlm how bg2 tob tutu tutu_totsc ca~)

	ACTION_FOR_EACH paperdoll IN ~cdfc3inv~ ~cdff3inv~ ~cdmc3inv~ ~cdmf3inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END


/* ========================================================== *
 *  Improved Animation for Male Elves with chain mail (EMB3)  *
 * ========================================================== */

COPY ~1pp/core/1pp_avatars/m/emb3~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu OR is_iwd) BEGIN // (GAME_IS ~totlm how bg2 tob tutu tutu_totsc ca~)

	ACTION_FOR_EACH paperdoll IN ~cemc3inv~ ~cemf3inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END


/* ============================================================== *
 *  Improved Animation for Male Human with leather armour (HMB2)  *
 * ============================================================== */

COPY ~1pp/core/1pp_avatars/m/hmb2~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu OR is_iwd) BEGIN // (GAME_IS ~totlm how bg2 tob tutu tutu_totsc ca~)

	ACTION_FOR_EACH paperdoll IN ~chmc2inv~ ~chmf2inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END


/*  ========================================================  *
 *  Improved Animation for Male Human with chain mail (HMB3)  *
 *  ========================================================  */

COPY ~1pp/core/1pp_avatars/m/hmb3~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu OR is_iwd) BEGIN // (GAME_IS ~totlm how bg2 tob tutu tutu_totsc ca~)

	ACTION_FOR_EACH paperdoll IN ~chmc3inv~ ~chmf3inv~ BEGIN

		COPY ~1pp/core/1ppfixed/%paperdoll%.bam~ ~override~

		ACTION_IF FILE_EXISTS_IN_GAME ~%paperdoll%.plt~ BEGIN
			COPY ~1pp/core/ilove.plt~ ~override/%paperdoll%.plt~
		END

	END

END


PRINT @105000 // ~The End.~