// 1ppv4 Thieves Galore!
// NOTE: IWD HoW .exe patching is only required if you'd like to have armour and chain mail on thieves.
// (leather and unarmoured work fine) | IWD II should not need it at all.
// +Unique animations for different thief armour levels

/*  ==============================================================================================================================================================================  *
 *  change-log:                                                                                                                                                                     *
 *  -----------                                                                                                                                                                     *
 *      - Coding simplification:                                                                                                                                                    *
 *  		Copy entire folders instead of infinite lines (COPY ~1pp/folder/file.ext~ ~override~ or ACTION_FOR_EACH file IN list BEGIN COPY ~1pp/folder/file.ext~ ~override~ END).  *
 *  ==============================================================================================================================================================================  */

/*  ================  *
 *  COPY NEW CONTENT  *
 *  ================  */

PRINT @106002 /* Copying new files... */

/* --------------------------------------------------- *
 *  CDFT1 - Female unarmoured dwarven thief            *
 *  CDFT3 - Female dwarven thief with chain mail       *
 *  CDMT1 - Male unarmoured dwarven thief              *
 *  CDMT3 - Male dwarven thief with chain mail         *
 *  CEFT1 - Female unarmoured elven thief              *
 *  CEFT2 - Female elven thief with leather armour     *
 *  CEFT3 - Female elven thief with chain mail         *
 *  CEMT1 - Male unarmoured elven thief                *
 *  CEMT3 - Male elven thief with chain mail           *
 *  CHFT1 - Female unarmoured human thief              *
 *  CHFT2 - Female human thief with leather armour     *
 *  CHFT3 - Female human thief with chain mail         *
 *  CHMT1 - Male unarmoured human thief                *
 *  CHMT3 - Male human thief with chain mail           *
 *  CIFT1 - Female unarmoured halfling thief           *
 *  CIFT3 - Female halfling thief with chain mail      *
 *  CIMT1 - Male unarmoured halfling thief             *
 *  CIMT2 - Female halfling thief with leather armour  *
 *  CIMT3 - Male halfling thief with chain mail        *
 * --------------------------------------------------- */
COPY ~1pp/core/1pp_thieves_galore/files/CDFT1~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CDFT3~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CDMT1~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CDMT3~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CEFT1~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CEFT2~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CEFT3~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CEMT1~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CEMT3~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CHFT1~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CHFT2~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CHFT3~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CHMT1~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CHMT3~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CIFT1~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CIFT3~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CIMT1~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CIMT2~ ~override~
COPY ~1pp/core/1pp_thieves_galore/files/CIMT3~ ~override~


/*  ==============================  *
 *  CLONING PLATE ARMOR ANIMATIONS  *
 *  ==============================  */
// We are duplicating the plate armour animations here to avoid massive crashing

PRINT @110001 /* Creating T4 duplicates.. */

ACTION_FOR_EACH category IN ~DF~ ~DM~ ~EF~ ~HF~ ~HM~ ~IF~ ~IM~ BEGIN
	ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~G11~ ~G12~ ~G13~ ~G14~ ~G15~ ~G16~ ~G17~ ~G18~ ~G19~ ~SA~ ~SS~ ~SX~ BEGIN
		COPY_EXISTING ~C%category%F4%sequence%.bam~ ~override/C%category%T4%sequence%.bam~
	END
END

COPY_EXISTING 	~CEMC4A1.BAM~	~override/CEMT4A1.BAM~
				~CEMC4A2.BAM~	~override/CEMT4A2.BAM~
				~CEMC4A3.BAM~	~override/CEMT4A3.BAM~
				~CEMC4A4.BAM~	~override/CEMT4A4.BAM~
				~CEMC4A5.BAM~	~override/CEMT4A5.BAM~
				~CEMC4A6.BAM~	~override/CEMT4A6.BAM~
				~CEMC4A7.BAM~	~override/CEMT4A7.BAM~
				~CEMC4A8.BAM~	~override/CEMT4A8.BAM~
				~CEMC4A9.BAM~	~override/CEMT4A9.BAM~
				~CEMC4CA.BAM~	~override/CEMT4CA.BAM~
				~CEMC4G1.BAM~	~override/CEMT4G1.BAM~
				~CEMC4G11.BAM~	~override/CEMT4G11.BAM~
				~CEMC4G12.BAM~	~override/CEMT4G12.BAM~
				~CEMC4G13.BAM~	~override/CEMT4G13.BAM~
				~CEMC4G14.BAM~	~override/CEMT4G14.BAM~
				~CEMC4G15.BAM~	~override/CEMT4G15.BAM~
				~CEMC4G16.BAM~	~override/CEMT4G16.BAM~
				~CEMC4G17.BAM~	~override/CEMT4G17.BAM~
				~CEMC4G18.BAM~	~override/CEMT4G18.BAM~
				~CEMC4G19.BAM~	~override/CEMT4G19.BAM~
				~CEMC4SA.BAM~	~override/CEMT4SA.BAM~
				~CEMC4SS.BAM~	~override/CEMT4SS.BAM~
				~CEMC4SX.BAM~	~override/CEMT4SX.BAM~

// END of COMPONENT