// Avatar switching/morphing
// PATCH ME HAPPY

/*  ==============================================================================================================================================================================  *
 *  change-log:                                                                                                                                                                     *
 *  -----------                                                                                                                                                                     *
 *    . - Use newer and more efficient WeiDU ADD_ITEM_EQEFFECT function to replace so many lines of codes.                                                                          *
 *  ==============================================================================================================================================================================  */

/*  =======  *
 *  BG2-ToB  *
 *  =======  */
ACTION_IF (GAME_IS ~bg2 tob tutu tutu_totsc ca~) BEGIN
	PRINT @113000 /* BGII detected */
	PRINT @113001 /* Installing: Improved Improved Galactygon's Avatar Switching */
	PRINT @113002 /* Installing avatar switching code and files */

	EXTEND_TOP ~baldur.bcs~ ~1pp/core/1pp_thieves_galore/patches/script/script.baf~
	EXTEND_TOP ~baldur25.bcs~ ~1pp/core/1pp_thieves_galore/patches/script/script.baf~

// the following built on and mostly copied from the BGII Tweak Pack component
// http://www.gibberlings3.net/bg2tweaks/

	COPY ~1pp/core/1pp_thieves_galore/patches/switch/fc_dwar2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fc_dwarf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fc_el2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fc_elf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fc_gnom2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fc_gnome.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fc_half2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fc_halfl.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fc_hfor2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fc_hforc.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fc_huma2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fc_human.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ff_dwar2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ff_dwarf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/FF_EL2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ff_elf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ff_gnom2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ff_gnome.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ff_half2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ff_halfl.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ff_hfor2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ff_hforc.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ff_huma2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ff_human.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fm_dwar2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fm_dwarf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fm_el2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fm_elf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/FM_GNOM2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fm_gnome.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fm_half2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fm_halfl.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/FM_HFOR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/FM_HFORC.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fm_huma2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/fm_human.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_dwar2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_dwarf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_el2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_elf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_gnom2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_gnome.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_half2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_halfl.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_hfor2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_hforc.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_huma2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/ft_human.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/FX_HUMA2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/FX_HUMAN.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/lcarmor.spl~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/LCARMOR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/lcarmorc.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/LCARMORC.spl~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/lcarmorf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/LCARMORF.spl~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/LCARMORM.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/LCARMORM.SPL~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/lcarmort.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/LCARMORT.spl~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/lcrobe.spl~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/LCROBE2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/LCUARMRD.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/LCUARMRD.SPL~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mc_dwar2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/MC_DWARF.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mc_el2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/MC_ELF.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mc_gnom2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/MC_GNOME.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mc_half2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/MC_HALFL.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mc_hfor2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/MC_HFORC.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mc_huma2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/MC_HUMAN.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_dwar2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_dwarf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_el2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_elf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_gnom2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_gnome.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_half2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_halfl.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_hfor2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_hforc.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_huma2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mf_human.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mm_dwar2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mm_dwarf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mm_el2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mm_elf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mm_gnom2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mm_gnome.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mm_half2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mm_halfl.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/MM_HFOR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/MM_HFORC.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mm_huma2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/MM_HUMAN.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_dwar2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_dwarf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_el2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_elf.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_gnom2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_gnome.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_half2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_halfl.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_hfor2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_hforc.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_huma2.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/mt_human.eff~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/MX_HUMA2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/switch/MX_HUMAN.EFF~ ~override~

	ACTION_IF (FILE_EXISTS_IN_GAME ~PROPC101.EFF~) BEGIN
	END ELSE BEGIN
		COPY ~1pp/core/1pp_thieves_galore/patches/switch/PROPC101.EFF~ ~override~
	END

	PRINT @113003 /* Patching armour and robes (BGII style) */
	COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
		READ_SHORT 0x1c "itemtype" ELSE 0
		PATCH_IF (itemtype = 2) BEGIN
			READ_ASCII 0x22 "anim" (2)
			PATCH_IF (("%anim%" STRING_COMPARE_CASE "2w" = 0) OR
					  ("%anim%" STRING_COMPARE_CASE "3w" = 0) OR
					  ("%anim%" STRING_COMPARE_CASE "4w" = 0)) BEGIN // if robe
				LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = "-1" opcode = 146 target = 1 timing = 2 parameter1 = 1 parameter2 = 1 STR_VAR resource = lcrobe END	// robe spell effect
			END ELSE BEGIN
				LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = "-1" opcode = 146 target = 1 timing = 2 parameter1 = 1 parameter2 = 1 STR_VAR resource = lcarmor END	// armor spell effect
			END
		END
	BUT_ONLY

END // of ACTION_IF (GAME_IS ~bg2 tob tutu tutu_totsc ca~)


/*  ===  *
 *  IWD  *
 *  ===  */
ACTION_IF (GAME_IS ~totlm how~) BEGIN
	PRINT @113004 /* IWD HoW/TotLM detected */
	PRINT @113005 /* Installing: IWD Avatar Switching */
	PRINT @113006 /* Installing avatar switching files */

	COPY ~1pp/core/1pp_thieves_galore/patches/iwd_switch~ ~override~

	PRINT @113007 /* Patching armour and robes (IWD style) */
	COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
		READ_SHORT 0x1c "itemtype" ELSE 0
		PATCH_IF ("%itemtype%" = 2) BEGIN
			READ_ASCII 0x22 "anim" (2)
			PATCH_IF (("%anim%" STRING_COMPARE_CASE "2w" = 0) OR
					  ("%anim%" STRING_COMPARE_CASE "3w" = 0) OR
					  ("%anim%" STRING_COMPARE_CASE "4w" = 0)) BEGIN // if robe
				SPRINT "resource" "lirobe"	// resource
				SPRINT "icon" "licng1" 		// resource
			END ELSE BEGIN
				SPRINT "resource" "liarmor"	// resource
				SPRINT "icon" "licng0"		// resource
			END

			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
				READ_LONG 0x64 ~abil_loc~
				READ_SHORT 0x68 ~abil_num~
				READ_SHORT 0x6A ~fx_loc~

				// generate real eff number
				SET overhead = (%SOURCE_SIZE% - %fx_loc%)
				SET entfx_num = (overhead / 0x30)

				READ_SHORT 0x70 ~fx_num~
				SET abil_size = ((%fx_loc% - %abil_loc%) / %abil_num%)
				SET new_bytes = (%fx_loc%)
				SET new_abil_loc = %new_bytes%
				SET new_fx_loc = (%new_abil_loc% + 0x38)
				INSERT_BYTES %new_bytes% 0x38
				WRITE_SHORT 104 (%abil_num% + 1)
				WRITE_LONG  106 (%new_fx_loc%)
				WRITE_BYTE  (%new_abil_loc% + 0) 0					// attack type
				WRITE_BYTE  (%new_abil_loc% + 2) 3					// use location
				WRITE_EVALUATED_ASCII (%new_abil_loc% + 4) ~%icon%~	// use icon
				WRITE_BYTE  (%new_abil_loc% + 12) 5					// type of target
				WRITE_BYTE  (%new_abil_loc% + 14) 1					// Range
				WRITE_SHORT (%new_abil_loc% + 18) 0					// speed
				WRITE_SHORT (%new_abil_loc% + 22) 6					// dice sides
				WRITE_SHORT (%new_abil_loc% + 24) 0					// dice rolls
				WRITE_SHORT (%new_abil_loc% + 28) 1					// damage type
				WRITE_SHORT (%new_abil_loc% + 36) 1					// charge removal
				WRITE_LONG  (%new_abil_loc% + 38) 0					// flag: use strength
				WRITE_SHORT (%new_abil_loc% + 42) 1					// Projectile Type
				WRITE_SHORT (%new_abil_loc% + 44) 34				// overh
				WRITE_SHORT (%new_abil_loc% + 46) 33				// backhand
				WRITE_SHORT (%new_abil_loc% + 48) 33				// thrust
				WRITE_SHORT (%new_abil_loc% + 30) 3					// # of effects
				WRITE_SHORT (%new_abil_loc% + 32) %entfx_num%		// Effect index

				SET addeffectone = (%SOURCE_SIZE% + 0x38)
				SET addeffecttwo = (%SOURCE_SIZE% + 0x30 + 0x38)
				SET addeffectthree = (%SOURCE_SIZE% + 0x60 + 0x38)

				// CAST SPELL
				SET new_abil_loc = addeffectone
				INSERT_BYTES %addeffectone% 0x30
				WRITE_SHORT (%new_abil_loc% + 0x00) 146						// opcode
				WRITE_BYTE  (%new_abil_loc% + 0x02) 1						// target
				WRITE_BYTE  (%new_abil_loc% + 0x03) 0						// power
				WRITE_LONG  (%new_abil_loc% + 0x04) 1						// cast at level
				WRITE_LONG  (%new_abil_loc% + 0x08) 1						// cast instantly
				WRITE_BYTE  (%new_abil_loc% + 0x0C) 2						// timing mode
				WRITE_BYTE  (%new_abil_loc% + 0x0D) 0						// dispel/resist
				WRITE_LONG  (%new_abil_loc% + 0x0E) 0						// duration
				WRITE_BYTE  (%new_abil_loc% + 0x12) 100						// probability 1
				WRITE_BYTE  (%new_abil_loc% + 0x13) 0						// probability 2
				WRITE_EVALUATED_ASCII (%new_abil_loc% + 0x14) ~%resource%~	// resource
				WRITE_LONG  (%new_abil_loc% + 0x1C) 0						// #dice/maxlevel
				WRITE_LONG  (%new_abil_loc% + 0x20) 0						// dicesize/minlevel
				WRITE_LONG  (%new_abil_loc% + 0x24) 0						// savetype
				WRITE_LONG  (%new_abil_loc% + 0x28) 0						// savebogus

				//REMOVE SPELL
				SET new_abil_loc = addeffecttwo
				INSERT_BYTES %addeffecttwo% 0x30
				WRITE_SHORT (%new_abil_loc% + 0x00) 172					// opcode
				WRITE_BYTE  (%new_abil_loc% + 0x02) 1					// target
				WRITE_BYTE  (%new_abil_loc% + 0x03) 0					// power
				WRITE_LONG  (%new_abil_loc% + 0x04) 0					// cast at level
				WRITE_LONG  (%new_abil_loc% + 0x08) 0 					// cast instantly
				WRITE_BYTE  (%new_abil_loc% + 0x0C) 1					// timing mode
				WRITE_BYTE  (%new_abil_loc% + 0x0D) 0					// dispel/resist
				WRITE_LONG  (%new_abil_loc% + 0x0E) 0					// duration
				WRITE_BYTE  (%new_abil_loc% + 0x12) 100					// probability 1
				WRITE_BYTE  (%new_abil_loc% + 0x13) 0					// probability 2
				WRITE_EVALUATED_ASCII (%new_abil_loc% + 0x14) ~liuarm3~	// resource
				WRITE_LONG  (%new_abil_loc% + 0x1C) 0					// #dice/maxlevel
				WRITE_LONG  (%new_abil_loc% + 0x20) 0 					// dicesize/minlevel
				WRITE_LONG  (%new_abil_loc% + 0x24) 0					// savetype
				WRITE_LONG  (%new_abil_loc% + 0x28) 0 					// savebogus

				// GIVE INNATE (switch)
				SET new_abil_loc = addeffectthree
				INSERT_BYTES %addeffectthree% 0x30
				WRITE_SHORT (%new_abil_loc% + 0x00) 171					// opcode
				WRITE_BYTE  (%new_abil_loc% + 0x02) 1					// target
				WRITE_BYTE  (%new_abil_loc% + 0x03) 0					// power
				WRITE_LONG  (%new_abil_loc% + 0x04) 0					// cast at level
				WRITE_LONG  (%new_abil_loc% + 0x08) 0					// cast instantly
				WRITE_BYTE  (%new_abil_loc% + 0x0C) 1					// timing mode
				WRITE_BYTE  (%new_abil_loc% + 0x0D) 0 					// dispel/resist
				WRITE_LONG  (%new_abil_loc% + 0x0E) 0					// duration
				WRITE_BYTE  (%new_abil_loc% + 0x12) 100					// probability 1
				WRITE_BYTE  (%new_abil_loc% + 0x13) 0					// probability 2
				WRITE_EVALUATED_ASCII (%new_abil_loc% + 0x14) ~liuarm3~	// resource
				WRITE_LONG  (%new_abil_loc% + 0x1C) 0					// #dice/maxlevel
				WRITE_LONG  (%new_abil_loc% + 0x20) 0					// dicesize/minlevel
				WRITE_LONG  (%new_abil_loc% + 0x24) 0					// savetype
				WRITE_LONG  (%new_abil_loc% + 0x28) 0					// savebogus

			END

		END
	BUT_ONLY

END // of ACTION_IF (GAME_IS ~totlm how~)


/*  ====  *
 *  IWD2  *
 *  ====  */
ACTION_IF (GAME_IS ~iwd2~) BEGIN
	PRINT @113008 /* IWDII detected */
	PRINT @113009 /* Installing: IWDII Avatar Switching */
	PRINT @113006 /* Installing avatar switching files */

	COPY ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_DWAR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_DWAR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_DWARF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_EL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_EL2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_ELF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_GNOM0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_GNOM2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_GNOME.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_HALF0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_HALF2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_HALFL.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_HEL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_HFOR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_HFOR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_HFORC.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_HUMA0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_HUMA2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FC_HUMAN.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_DWAR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_DWAR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_DWARF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_EL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_EL2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_ELF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_GNOM0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_GNOM2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_GNOME.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_HALF0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_HALF2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_HALFL.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_HEL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_HFOR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_HFOR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_HFORC.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_HUMA0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_HUMA2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FF_HUMAN.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_DWAR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_DWAR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_DWARF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_EL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_EL2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_ELF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_GNOM0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_GNOM2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_GNOME.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_HALF0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_HALF2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_HALFL.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_HEL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_HFOR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_HFOR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_HFORC.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_HUMA0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_HUMA2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FM_HUMAN.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_DWAR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_DWAR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_DWARF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_EL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_EL2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_ELF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_GNOM0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_GNOM2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_GNOME.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_HALF0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_HALF2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_HALFL.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_HEL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_HFOR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_HFOR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_HFORC.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_HUMA0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_HUMA2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/FT_HUMAN.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/L2ARMOR.SPL~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/L2ROBE.SPL~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/LICNG2.BAM~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_DWAR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_DWAR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_DWARF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_EL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_EL2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_ELF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_GNOM0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_GNOM2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_GNOME.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_HALF0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_HALF2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_HALFL.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_HEL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_HFOR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_HFOR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_HFORC.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_HUMA0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_HUMA2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MC_HUMAN.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_DWAR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_DWAR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_DWARF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_EL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_EL2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_ELF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_GNOM0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_GNOM2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_GNOME.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_HALF0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_HALF2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_HALFL.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_HEL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_HFOR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_HFOR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_HFORC.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_HUMA0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_HUMA2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MF_HUMAN.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_DWAR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_DWAR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_DWARF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_EL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_EL2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_ELF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_GNOM0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_GNOM2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_GNOME.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_HALF0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_HALF2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_HALFL.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_HEL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_HFOR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_HFOR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_HFORC.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_HUMA0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_HUMA2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MM_HUMAN.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_DWAR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_DWAR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_DWARF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_EL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_EL2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_ELF.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_GNOM0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_GNOM2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_GNOME.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_HALF0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_HALF2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_HALFL.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_HEL0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_HFOR0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_HFOR2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_HFORC.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_HUMA0.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_HUMA2.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/MT_HUMAN.EFF~ ~override~
		 ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/SPIN100.SPL~ ~override~

	COPY ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/PRE_M01.WAV~ ~override~

	PRINT @113010 /* Copying .2da */
	COPY ~1pp/core/1pp_thieves_galore/patches/iwd2_switch/LISTINNT.2DA~ ~override~

	PRINT @113011 /* Patching armour and robes (IWDII style) */
	COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
		READ_ASCII 0x22 "itemtype" (2)
		PATCH_IF (("%itemtype%" STRING_COMPARE_CASE "2a" = 0) OR
				  ("%itemtype%" STRING_COMPARE_CASE "3a" = 0) OR
				  ("%itemtype%" STRING_COMPARE_CASE "4a" = 0) OR
				  ("%itemtype%" STRING_COMPARE_CASE "2w" = 0) OR
				  ("%itemtype%" STRING_COMPARE_CASE "3w" = 0) OR
				  ("%itemtype%" STRING_COMPARE_CASE "4w" = 0)
				 ) BEGIN
			READ_ASCII 0x22 "anim" (2)
			READ_LONG  0x64 "abil_off"
			READ_SHORT 0x68 "abil_num"
			READ_LONG  0x6a "fx_off"
			READ_SHORT 0x70 "fx_num"
			SET "new_fx" = 1
			FOR (loops = 0 ; loops < abil_num ; loops = loops + 1) BEGIN	// adjusts effects on abilities up by new_fx
				READ_SHORT  (0x20 + "%abil_off%" + ("%loops%" * 0x38)) "abil_fx_idx"
				WRITE_SHORT (0x20 + "%abil_off%" + ("%loops%" * 0x38)) ("%abil_fx_idx%" + "%new_fx%")
			END
			WRITE_SHORT 0x70 ("%fx_num%" + "%new_fx%")
			INSERT_BYTES ("%fx_off%" +        ("%fx_num%" * 0x30)) 0x30	// new effect
			WRITE_SHORT ("%fx_off%" +        ("%fx_num%" * 0x30)) 146	// cast spell
			WRITE_BYTE  ("%fx_off%" + 0x02 + ("%fx_num%" * 0x30)) 1		// target self
			WRITE_LONG  ("%fx_off%" + 0x04 + ("%fx_num%" * 0x30)) 1		// cast at level
			WRITE_BYTE  ("%fx_off%" + 0x08 + ("%fx_num%" * 0x30)) 1		// cast instantly? yes
			WRITE_BYTE  ("%fx_off%" + 0x0c + ("%fx_num%" * 0x30)) 1		// instant/while equipped
			WRITE_BYTE  ("%fx_off%" + 0x12 + ("%fx_num%" * 0x30)) 100	// probability 100
			PATCH_IF (
					  ("%anim%" STRING_COMPARE_CASE "2w" = 0) OR
					  ("%anim%" STRING_COMPARE_CASE "3w" = 0) OR
					  ("%anim%" STRING_COMPARE_CASE "4w" = 0)
					 ) BEGIN // if robe
				WRITE_ASCII  ("%fx_off%" + 0x14 + ("%fx_num%" * 0x30)) ~l2robe~  // robe spell effect
			END ELSE BEGIN
				WRITE_ASCII  ("%fx_off%" + 0x14 + ("%fx_num%" * 0x30)) ~l2armor~ // armor spell effect
			END
		END
	BUT_ONLY

END // of ACTION_IF (GAME_IS ~iwd2~)

// END of COMPONENT