/* =========================================================================================================================================================================================== *
 *  v 4.2.0                                                                                                                                                                                    *
 *                                                                 C O M P O N E N T   :   C o r e   c o n t e n t   p a t c h                                                                 *
 *                                                                                                                                                                                             *
 * =========================================================================================================================================================================================== *
 *  This is essentially the inventory icon/item related patches of 1ppv2 cut and updated (go 2004!). In other words, lots of random icon improvements for BGII, especially on the ToB side     *
 *  of things, as well as some mod item patches and updates. It will form the basis on which 1ppv4 is built on SoA/ToB.                                                                        *
 * =========================================================================================================================================================================================== *
 *  change-log:                                                                                                                                                                                *
 *  -----------                                                                                                                                                                                *
 *      - Variables needed for installation (1pp_potions and 1pp_hammers_icons) are read from 1pp-config-default.ini or 1pp-config-user.ini files.                                             *
 *        The previous version interrupted installation with plain text prompts allowing players to customise components to their liking (depending on which IE game the mod is installed      *
 *        for and already installed components). All those variables set during installation have been moved into 1pp-config-default.ini file in 1pp folder. This file provides a standard     *
 *        installation. If players want to define their own customized installation, they have to modify the variables involved in 1pp-config-default.ini and save it as 1pp-config-user.ini.  *
 *        The installation process will read both ini files and prioritize user values. If a value is not set or mismatched in in user's file 1pp-config-user.ini, the installation process    *
 *        will prevent any installation failure by reverting it back to its default value.                                                                                                     *
 *      - Replaced macros with functions whenever possible.                                                                                                                                    *
 *      - 1ppv2 BAMs: for modding purpose, creates copies of a few vanilla inventory icons (with "v" suffix) before overwriting them (#825). Does not overwrite anymore the following those    *
 *        that are irrelevant (EE does not validate this change): does not replace iax1h14.bam (Axe of the Unyielding +3) with the very inaccurate IWD Celebrant's Blade icon {#836),          *
 *        idagg11.bam (Boomerang Dagger) with a clone of imisc75 (Dagger of Venom, #868), and isw1h06.bam (Varscona +2) with a clone of isw1h41 (Long Sword +2, #918). Does not overwrite      *
 *        Harbinger's icon and copies an alternate resource for modding purpose (1isw2h07). This way, Harbinger keeps its golden icon which fits to its colors settings (#950).                *
 *      - Added a new setting (1pp_hammers_icons) allowing to make alternate the overwriting of the Runehammer icon (#875: saves vanilla ihamm10 icon and installs new ihamm10 1pp icon as     *
 *        ihamm05b), and not to set Borok's Fist's icon to Runehammers.                                                                                                                        *
 *      - Coding simplification:                                                                                                                                                               *
 *          Replaced WRITE_LONG 0x3E 0 and WRITE_ASCII 0x3A ~ISHLDS01~ with WRITE_ASCII 0x3A ~ISHLDS01~ #8. Id. with offsets 0x48 0x44, and 0x5C 0x58.                                         *
 *          Grouped actions or patches with ACTION_FOR_EACH and PATCH_FOR_EACH whenever possible.                                                                                              *
 *                                                                                                                                                                                             *
 *  Code re-written with newer functions to provide automatic process:                                                                                                                         *
 *  ------------------------------------------------------------------                                                                                                                         *
 *    . - Used newer and more efficient WeiDU ALTER_EFFECT and ALTER_ITEM_HEADER functions to replace so many lines of codes.                                                                  *
 *      - Used DELETE_EFFECT and CLONE_EFFECT combo to add new equipped color effects, which avoids writing lines of codes!                                                                    *
 *                                                                                                                                                                                             *
 *  specific fixes:                                                                                                                                                                            *
 *  ---------------                                                                                                                                                                            *
 *      - #96   ==> dagg21.itm & dagg22.itm (Daggers of the Star): reverted to their original inventory icon idagg21. 1PP sets them to idagg18 (Shadow Thief Dagger icon), but EE does         *
 *                  not validate this change.                                                                                                                                                  *
 *      - #110  ==> halb07.itm (Halberd +2): reverted to its original inventory icon ihalb07. 1PP sets it to ihalb03 (Suryris's Blade +2 icon), but EE does not validate this change.          *
 *      - #676  ==> sw1h31.itm (Daystar +2): reverted to its original inventory icon isw1h31. 1PP sets it to isw1h34 (Albruin +1), but EE does not validate this change.                       *
 *      - #686  ==> sw1h34.itm (Albruin +1): reverted to its original inventory icon isw1h34. 1PP sets it to isw1h31 (Daystar +2), but EE does not validate this change.                       *
 *      - #695  ==> sw1h41.itm (Long Sword +2): reverted to its original inventory icon ISW1H41. 1PP sets it to sw1h06 (Varscona +2 icon), but EE does not validate this change.               *
 *      - #783  ==> sw2h10.itm and sw2h19.itm (Carsomyr +5 and +6): reverted to their original inventory icon isw2h10. 1PP sets them to isw2h20, but EE does not validate this change.         *
 *      - #796  ==> sw2h11.itm (Two-handed Sword +2): reverted to its original inventory icon isw2h11. 1PP sets it to isw2h03, but EE does not validate this change.                           *
 *      - #806  ==> sw2h20.itm (Two-handed Sword +3): reverted to its original inventory icon isw2h20. 1PP sets it to isw2h06, but EE does not validate this change.                           *
 *      - #968  ==> sw1hwk.itm (Water's Edge +3): wrong identified name fix moved from 400_update_bgii_misc.tpa because Core content patches component installs it and is a pre-requisite      *
 *                  for Core updates and item patches component.                                                                                                                               *
 *      - #994  ==> BW Herbs mod patches: fixed a typo (was copying bw02ipo1_l.bam instead of bw02ipo1.bam.                                                                                    *
 * =========================================================================================================================================================================================== */

// ----------------------------- //
//     ITEMS               line  //
// ----------------------------- //
//  MISCELLANEOUS        #   63  //
//  HELMETS              #  144  //
//  SHIELDS              #  257  //
//  SWORDS               #  631  //
//  1ppv2 BAMs           #  819  //
//  POTIONS              #  974  //
//  BW HERBS STUFF       #  986  //
// ----------------------------- //
SILENT

/* =============================== *
 *          MISCELLANEOUS          *
 * =============================== */

// Mace - Morning Star: set item color, weapon head (timing mod was set to 0).
ACTION_FOR_EACH item IN ~blun04~ ~blun06~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 16 timing = 2 END
		BUT_ONLY
	END
END

// Improved Cloak of Protection +2: modify inventory icon (Holy cloak).
ACTION_IF (FILE_EXISTS_IN_GAME ~clck31.itm~) BEGIN
	COPY_EXISTING ~clck31.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ICLCK21~ #8	// replaces ICLCK31
		END
	BUT_ONLY
END

// Roranach's Horn: modify inventory icon, item animation and colors (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~compon05.itm~) BEGIN
	COPY_EXISTING ~compon05.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~H0~			// replaces H3
			WRITE_ASCII 0x3A ~IHELM06~ #8	// replaces ICOMPO05
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 53 parameter1 = 67 END // sets item color, helm exterior: 67 SHINY_GOLD replaces 51 DARK_OLIVE_GREEN
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 48 parameter1 = 19 END // sets item color, helm wings: 19 DARK_ROSE_RED replaces 13 LIGHT_PINKISH_SILVER
		END
	BUT_ONLY
END

// Dagger of the Star: modify inventory icon (also modified by 400_1pp_update).
// Gwen fix: reverts to their original inventory icon IDAGG21. 1PP sets it to IDAGG18 (Shadow Thief Dagger icon), but EE does not validate this change.
/* DEPRECATED as of v4.2.0
ACTION_FOR_EACH ~item~ IN ~dagg21~ ~dagg22~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x3A ~IDAGG18~ #8			// replaces IDAGG21
				LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = idagg18 END
			END
		BUT_ONLY
	END
END*/

// Halberd +2: Timing mod was set to 0 for set item color, weapon head (also modified by 400_1pp_update).
// Gwen fix: reverts to its original inventory icon ihalb07 (modified by component 400). 1PP sets it to ihalb03 (Suryris's Blade +2 icon), but EE does not validate this change.
ACTION_IF (FILE_EXISTS_IN_GAME ~halb07.itm~) BEGIN
	COPY_EXISTING ~halb07.itm~ ~override~
//		WRITE_ASCII 0x3A ~IHALB03~ #8
//		LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = IHALB03 END
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 16 timing = 2 END
	BUT_ONLY
END

// Case of Plenty +1 - Case of Plenty +2 (also modified by 400_1pp_update): modifies inventory icon.
ACTION_FOR_EACH item IN ~quiver02~ ~quiver04~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x3A ~IBOLTS01~ #8	// replaces IQUIV01
			END
		BUT_ONLY
	END
END

// Bag of Plenty +1 - Bag of Plenty +2 (also modified by 400_1pp_update): modify inventory icon.
ACTION_FOR_EACH item IN ~quiver05~ ~quiver06~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
				WRITE_ASCII 0x3A ~IQBULL02~ #8	// replaces IQUIV05
			END
		BUT_ONLY
	END
END


/* ========================= *
 *          HELMETS          *
 * ========================= */

// Helm of Opposite Alignment - Helmet - Skull of Death - Dragon Helm - Helmet: modify item animation (also modified by 400_1pp_update).
ACTION_FOR_EACH item IN ~helm02~ ~helm08~ ~helm17~ ~helm21~ ~helm22~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			WRITE_ASCII 0x22 ~H4~		// replaces H3, H2, H0, H2, H3
		BUT_ONLY
	END
END

// Helm of the Noble +1 - Helmet: modify item animation (also modified by 400_1pp_update).
ACTION_FOR_EACH item IN ~helm03~ ~helm12~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			WRITE_ASCII 0x22 ~H2~		// replaces H1
		BUT_ONLY
	END
END

// Gift of Peace : modify inventory icon and item animation (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~helm04.itm~) BEGIN
	COPY_EXISTING ~helm04.itm~ ~override~
		WRITE_ASCII 0x22 ~H5~			// replaces H2
		WRITE_ASCII 0x3A ~IHELM07~ #8	// replaces IHELM03
	BUT_ONLY
END

// Helm of Infravision: modify inventory icon (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~helm05.itm~) BEGIN
	COPY_EXISTING ~helm05.itm~ ~override~
		WRITE_ASCII 0x3A ~IHELM05~ #8	// replaces IHELM06
	BUT_ONLY
END

// Helm of Charm Protection: modify inventory icon and item animation (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~helm06.itm~) BEGIN
	COPY_EXISTING ~helm06.itm~ ~override~
		WRITE_ASCII 0x22 ~H5~			// replaces H2
		WRITE_ASCII 0x3A ~IHELM05~ #8	// replaces IHELM03
	BUT_ONLY
END

// Helmet - Helm of Brilliance: modify item animation (also modified by 400_1pp_update).
ACTION_FOR_EACH item IN ~helm09~ ~helm16~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			WRITE_ASCII 0x22 ~H3~		// replaces H2
		BUT_ONLY
	END
END

// Helmet: modify item animation (also modified by 400_1pp_update).
ACTION_FOR_EACH item IN ~helm10~ ~helm15~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			WRITE_ASCII 0x22 ~H5~		// replaces H4
		BUT_ONLY
	END
END

// Helmet: modify inventory icon and item animation (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~helm11.itm~) BEGIN
	COPY_EXISTING ~helm11.itm~ ~override~
		WRITE_ASCII 0x22 ~H0~			// replaces H5
		WRITE_ASCII 0x3A ~IHELM00~ #8	// replaces IHELM06
	BUT_ONLY
END

// Helmet: modify inventory icon and item animation (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~helm13.itm~) BEGIN
	COPY_EXISTING ~helm13.itm~ ~override~
		WRITE_ASCII 0x22 ~H3~			// replaces H5
		WRITE_ASCII 0x3A ~IHELM03~ #8	// replaces IHELM06
	BUT_ONLY
END

// Helm of the Rock: modify item animation and colors (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~helm31.itm~) BEGIN
	COPY_EXISTING ~helm31.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~H3~			// replaces H0
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 53 parameter1 = 21 END // set item color, helm exterior: 21 DARK_IRON_GRAY replaces 30 LIGHT_IRON_GRAY
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 48 parameter1 = 29 END // set item color, helm wings: 29 RED-TINTED_BLACK replaces 27 GRAY
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 52 parameter1 = 43 END // set item color, helm face: 43 DARK_BEIGE replaces 27 GRAY
		END
	BUT_ONLY
END

// Helm of the Rock: modify item animation and colors (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~helm32.itm~) BEGIN
	COPY_EXISTING ~helm32.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~H4~			// replaces H1
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 53 parameter1 = 29 END // set item color, helm exterior: 29 RED-TINTED_BLACK replaces 30 LIGHT_IRON_GRAY
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 48 parameter1 = 21 END // set item color, helm wings: 21 DARK_IRON_GRAY replaces 27 GRAY
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 52 parameter1 = 66 END // set item color, helm face: 66 FADED_BLACK replaces 27 GRAY
		END
	BUT_ONLY
END

// Gold Horned Helm: modify item animation (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~helm33.itm~) BEGIN
	COPY_EXISTING ~helm33.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~H0~			// replaces H3
		END
	BUT_ONLY
END


/* ========================= *
 *          SHIELDS          *
 * ========================= */

// Small Shield: modify item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld01.itm~) BEGIN
	COPY_EXISTING ~shld01.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD01~ #8		// replaces ISHLDS01
		WRITE_ASCII 0x44 ~GSHLD01~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD01~ #8		// replaces CSHLD28
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 28 END // set item color, shield body: 28 BLUISH_SILVER replaces 42 BEIGE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 30 END // set item color, shield hub: 30 LIGHT_IRON_GRAY replaces 98 LEAF_GREEN
	BUT_ONLY
END

// Small Shield +1: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld02.itm~) BEGIN
	COPY_EXISTING ~shld02.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD02~ #8		// replaces ISHLDS02
		WRITE_ASCII 0x44 ~GSHLD01~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD02~ #8		// replaces CSHLD28
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 24 END // set item color, shield body: 24 BROWN_GOLD replaces 42 BEIGE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 25 END // set item color, shield hub: 25 DARK_PURE_GOLD replaces 98 LEAF_GREEN
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 29 END // set item color, shield panel: 29 RED-TINTED_BLACK
	BUT_ONLY
END

// Medium Shield: modify item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld03.itm~) BEGIN
	COPY_EXISTING ~shld03.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD03~ #8		// replaces ISHLDM01
		WRITE_ASCII 0x44 ~GSHLD03~ #8		// replaces GMSHLD
		WRITE_ASCII 0x58 ~CSHLD03~ #8		// replaces CSHLD29
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 100 END	// set item color, shield body: 100 DARK_ASH_GRAY replaces 104 DARK_CHROME_PURPLE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 70 END	// set item color, shield hub: 70 LIGHT_METALLIC_RED replaces 27 GRAY
	BUT_ONLY
END

// Medium Shield +1: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld04.itm~) BEGIN
	COPY_EXISTING ~shld04.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD04~ #8		// replaces ISHLDM02
		WRITE_ASCII 0x44 ~GSHLD03~ #8		// replaces GMSHLD
		WRITE_ASCII 0x58 ~CSHLD04~ #8		// replaces CSHLD29
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 30 END // set item color, shield body: 30 LIGHT_IRON_GRAY replaces 91 DARK_CHOCOLATE
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 99 END // set item color, shield hub: 99 GOLDEN_BROWN replaces 98 LEAF_GREEN
			LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
			LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 8 END // set item color, shield panel: 8 DARK_MUDDISH_BROWN
	BUT_ONLY
END

// Large Shield: modify item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld05.itm~) BEGIN
	COPY_EXISTING ~shld05.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD05~ #8		// replaces ISHLDL01
		WRITE_ASCII 0x44 ~GSHLD05~ #8		// replaces GLSHLD
		WRITE_ASCII 0x58 ~CSHLD05~ #8		// replaces CSHLD23
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 28 END	// set item color, shield body: 28 BLUISH_SILVER replaces 91 DARK_CHOCOLATE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 111 END	// set item color, shield hub: 111 BURNT_SIENNA replaces 102 SEA_BLUE
	BUT_ONLY
END

// Large Shield +1: modifies item icons and colours, and adds two effects (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld06.itm~) BEGIN
	COPY_EXISTING ~shld06.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD06~ #8		// replaces ISHLDL02
		WRITE_ASCII 0x44 ~GSHLD05~ #8		// replaces GLSHLD
		WRITE_ASCII 0x58 ~CSHLD06~ #8		// replaces CSHLD23
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 30 END	// set item color, shield body: 30 LIGHT_IRON_GRAY replaces 91 DARK_CHOCOLATE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 7 END	// set item color, shield hub: 7 LIGHT_METALLIC_GREEN replaces 98 LEAF_GREEN
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 33 END	// deletes shield interior if present to make way for new one
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 8 STR_VAR insert = first END // set item color, shield panel: 8 DARK_MUDDISH_BROWN
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 33 parameter1 = 6 STR_VAR insert = first END // set item color, shield interior: 6 DARK_SILVER
	BUT_ONLY
END

// Shield of the Falling Stars +1: modifies item icons and colours, and adds two effects (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld07.itm~) BEGIN
	COPY_EXISTING ~shld07.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD07~ #8		// replaces ISHLDL02
		WRITE_ASCII 0x44 ~GSHLD05~ #8		// replaces GLSHLD
		WRITE_ASCII 0x58 ~CSHLD07~ #8		// replaces CSHLD23
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 25 END	// set item color, shield hub: 25 DARK_PURE_GOLD replaces 98 LEAF_GREEN
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 25 END	// set item color, shield body: 25 DARK_PURE_GOLD replaces 91 DARK_CHOCOLATE
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 33 END	// deletes shield interior if present to make way for new one
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 8 STR_VAR insert = first END // set item color, shield panel: 8 DARK_MUDDISH_BROWN
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 33 parameter1 = 6 STR_VAR insert = first END // set item color, shield interior: 6 DARK_SILVER
	BUT_ONLY
END

// Buckler: modify item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld08.itm~) BEGIN
	COPY_EXISTING ~shld08.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD08~ #8		// replaces ISHLDB01
		WRITE_ASCII 0x44 ~GSHLD08~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD08~ #8		// replaces CSHLD28
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 28 END // set item color, shield body: 28 BLUISH_SILVER replaces 42 BEIGE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 30 END // set item color, shield hub: 30 LIGHT_IRON_GRAY replaces 98 LEAF_GREEN
	BUT_ONLY
END

// Buckler: modify item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld09.itm~) BEGIN
	COPY_EXISTING ~shld09.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD09~ #8		// replaces ISHLDB01
		WRITE_ASCII 0x44 ~GSHLD08~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD09~ #8		// replaces CSHLD28
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 22 END // set item color, shield body: 22 DARK_BROWN replaces 42 BEIGE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 23 END // set item color, shield hub: 23 LIGHT_COPPER replaces 98 LEAF_GREEN
	BUT_ONLY
END

// Buckler: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld10.itm~) BEGIN
	COPY_EXISTING ~shld10.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD10~ #8		// replaces ISHLDB01
		WRITE_ASCII 0x44 ~GSHLD08~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD10~ #8		// replaces CSHLD28
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 28 END	// set item color, shield body: 28 BLUISH_SILVER replaces 42 BEIGE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 26 END	// set item color, shield hub: 26 WOOD replaces 98 LEAF_GREEN
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 36 END	// deletes shield grip if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 36 parameter1 = 26 STR_VAR insert = first END // set item color, shield grip: 26 WOOD
	BUT_ONLY
END

// Small Shield: modify item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld11.itm~) BEGIN
	COPY_EXISTING ~shld11.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD11~ #8		// replaces ISHLDS01
		WRITE_ASCII 0x44 ~GSHLD01~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD01~ #8		// replaces CSHLD28
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 28 END // set item color, shield body: 28 BLUISH_SILVER replaces 42 BEIGE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 30 END // set item color, shield hub: 30 LIGHT_IRON_GRAY replaces 98 LEAF_GREEN
	BUT_ONLY
END

// Small Shield: modify item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld12.itm~) BEGIN
	COPY_EXISTING ~shld12.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD12~ #8		// replaces ISHLDS01
		WRITE_ASCII 0x44 ~GSHLD01~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD01~ #8		// replaces CSHLD28
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 27 END // set item color, shield body: 27 GRAY replaces 42 BEIGE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 30 END // set item color, shield hub: 30 LIGHT_IRON_GRAY replaces 98 LEAF_GREEN
	BUT_ONLY
END

// Medium Shield: modify item icons (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld13.itm~) BEGIN
	COPY_EXISTING ~shld13.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD13~ #8		// replaces ISHLDM01
		WRITE_ASCII 0x44 ~GSHLD03~ #8		// replaces GMSHLD
		WRITE_ASCII 0x58 ~CSHLD03~ #8		// replaces CSHLD29
	BUT_ONLY
END

// Medium Shield: modify item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld14.itm~) BEGIN
	COPY_EXISTING ~shld14.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD14~ #8		// replaces ISHLDM01
		WRITE_ASCII 0x44 ~GSHLD03~ #8		// replaces GMSHLD
		WRITE_ASCII 0x58 ~CSHLD03~ #8		// replaces CSHLD29
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 30 END // set item color, shield body: 30 LIGHT_IRON_GRAY replaces 100 DARK_ASH_GRAY
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 10 END // set item color, shield hub: 10 LIGHT_PURE_GOLD replaces 59 LIGHT_PURPLE
	BUT_ONLY
END

// Large Shield: modify item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld15.itm~) BEGIN
	COPY_EXISTING ~shld15.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD15~ #8		// replaces ISHLDL01
		WRITE_ASCII 0x44 ~GSHLD05~ #8		// replaces GLSHLD
		WRITE_ASCII 0x58 ~CSHLD05~ #8		// replaces CSHLD23
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 27 END // set item color, shield body: 27 GRAY replaces 41 MEDIUM_BROWN
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 19 END // set item color, shield hub: 19 DARK_ROSE_RED replaces 102 SEA_BLUE
	BUT_ONLY
END

// Large Shield: modify item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld16.itm~) BEGIN
	COPY_EXISTING ~shld16.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD16~ #8		// replaces ISHLDL01
		WRITE_ASCII 0x44 ~GSHLD05~ #8		// replaces GLSHLD
		WRITE_ASCII 0x58 ~CSHLD05~ #8		// replaces CSHLD23
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 28 END // set item color, shield body: 28 BLUISH_SILVER replaces 91 DARK_CHOCOLATE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 19 END // set item color, shield hub: 19 DARK_ROSE_RED replaces 102 SEA_BLUE
	BUT_ONLY
END

// Buckler +1: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld17.itm~) BEGIN
	COPY_EXISTING ~shld17.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD17~ #8		// replaces ISHLDB02
		WRITE_ASCII 0x44 ~GSHLD08~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD17~ #8		// replaces CSHLD28
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 17 END	// set item color, shield body: 17 PALE_BLUE replaces 42 BEIGE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 93 END	// set item color, shield hub: 93 DARK_CEMENT_GRAY replaces 98 LEAF_GREEN
 		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 36 END	// deletes shield grip if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 36 parameter1 = 18 STR_VAR insert = first END // set item color, shield grip: 18 BLUE
	BUT_ONLY
END

// Large Shield: modify item icons and colours.
ACTION_IF (FILE_EXISTS_IN_GAME ~shld18.itm~) BEGIN
	COPY_EXISTING ~shld18.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD15~ #8		// replaces ISHLDL01
		WRITE_ASCII 0x44 ~GSHLD05~ #8		// replaces GLSHLD
		WRITE_ASCII 0x58 ~CSHLD05~ #8		// replaces CSHLD23
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 27 END // set item color, shield body: 27 GRAY replaces 98 LEAF_GREEN
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 19 END // set item color, shield hub: 19 DARK_ROSE_RED replaces 100 DARK_ASH_GRAY
	BUT_ONLY
END

// Pellan's Shield +2: modifies item icons and colours, and adds two effects (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld19.itm~) BEGIN
	COPY_EXISTING ~shld19.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD19~ #8		// replaces ISHLDL02
		WRITE_ASCII 0x44 ~GSHLD05~ #8		// replaces GLSHLD
		WRITE_ASCII 0x58 ~CSHLD19~ #8		// replaces CSHLD23
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 50 END	// set item color, shield body: 50 DARK_YELLOW replaces 91 DARK_CHOCOLATE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 50 END	// set item color, shield hub: 50 DARK_YELLOW replaces 98 LEAF_GREEN
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 36 END	// deletes shield grip if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 66 STR_VAR insert = first END // set item color, shield panel: 66 FADED_BLACK
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 36 parameter1 = 0  STR_VAR insert = first END // set item color, shield grip: 0 RUST-TINTED_BLACK
	BUT_ONLY
END

// Kiel's Buckler: modify item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld20.itm~) BEGIN
	COPY_EXISTING ~shld20.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD20~ #8		// replaces ISHLDB01
		WRITE_ASCII 0x44 ~GSHLD08~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD20~ #8		// replaces CSHLD28
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 24 END // set item color, shield body: 24 BROWN_GOLD replaces 42 BEIGE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 24 END // set item color, shield hub: 24 BROWN_GOLD replaces 98 LEAF_GREEN
	BUT_ONLY
END

// Dragon Scale Shield +2: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld21.itm~) BEGIN
	COPY_EXISTING ~shld21.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLDDS~ #8		// replaces ISHLD21
		WRITE_ASCII 0x44 ~GSHLD03~ #8		// replaces GMSHLD
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 19 STR_VAR insert = first END // set item color, shield panel: 19 DARK_ROSE_RED
	BUT_ONLY
END

// Fortress Shield +3: modifies item icons and colours, and adds two effects (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld23.itm~) BEGIN
	COPY_EXISTING ~shld23.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLDFS~ #8		// replaces ISHLD23
		WRITE_ASCII 0x44 ~GSHLD05~ #8		// replaces GLSHLD
		WRITE_ASCII 0x58 ~CSHLD05~ #8		// replaces CSHLD23
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 31 END	// set item color, shield body: 31 LIGHT_SEA_BLUE replaces 60 DARK_PURPLE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 31 END	// set item color, shield hub: 31 LIGHT_SEA_BLUE replaces 59 LIGHT_PURPLE
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 33 END	// deletes shield interior if present to make way for new one
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 18 STR_VAR insert = first END // set item color, shield panel: 18 BLUE
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 33 parameter1 = 18 STR_VAR insert = first END // set item color, shield interior: 18 BLUE
	BUT_ONLY
END

// Reflection Shield +1: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld24.itm~) BEGIN
	COPY_EXISTING ~shld24.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLDRF~ #8		// replaces ISHLD24
		WRITE_ASCII 0x44 ~GSHLD01~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD08~ #8		// replaces CSHLD24
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 26 END	// set item color, shield body: 26 WOOD replaces 60 DARK_PURPLE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 26 END	// set item color, shield hub: 26 WOOD replaces 59 LIGHT_PURPLE
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 63 STR_VAR insert = first END // set item color, shield panel: 63 LIGHT_GRAY
	BUT_ONLY
END

// Shield of Harmony +2: modifies item icons and colours (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld25.itm~) BEGIN
	COPY_EXISTING ~shld25.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLDHM~ #8		// replaces ISHLD25
		WRITE_ASCII 0x44 ~GSHLD01~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD02~ #8		// replaces CSHLD25
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 31 END // set item color, shield body: 31 LIGHT_SEA_BLUE replaces 24 BROWN_GOLD
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 31 END // set item color, shield hub: 31 LIGHT_SEA_BLUE replaces 25 DARK_PURE_GOLD
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 34 parameter1 = 17 END // set item color, shield panel: 17 PALE_BLUE replaces 29 RED-TINTED_BLACK
	BUT_ONLY
END

// Shield of the Lost +2: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld26.itm~) BEGIN
	COPY_EXISTING ~shld26.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLDVR~ #8		// replaces ISHLD26
		WRITE_ASCII 0x44 ~GSHLD03~ #8		// replaces GMSHLD
		WRITE_ASCII 0x58 ~CSHLD03~ #8		// replaces CSHLD26
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 48 END	// set item color, shield body: 48 LIGHT_RUST replaces 31 LIGHT_SEA_BLUE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 58 END	// set item color, shield hub: 58 DARK_BLUE replaces 57 LIGHT_BLUE
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 58 STR_VAR insert = first END // set item color, shield panel: 58 DARK_BLUE
	BUT_ONLY
END

// Saving Grace +3: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld27.itm~) BEGIN
	COPY_EXISTING ~shld27.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLDGN~ #8		// replaces ISHLD27
		WRITE_ASCII 0x44 ~GSHLD03~ #8		// replaces GMSHLD
		WRITE_ASCII 0x58 ~CSHLD04~ #8		// replaces CSHLD27
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 30 END	// set item color, shield body: 30 LIGHT_IRON_GRAY replaces 41 MEDIUM_BROWN
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 96 END	// set item color, shield hub: 96 CHROME_BLUE replaces 98 LEAF_GREEN
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 18 STR_VAR insert = first END // set item color, shield panel: 18 BLUE
	BUT_ONLY
END

// Small Shield +2: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld28.itm~) BEGIN
	COPY_EXISTING ~shld28.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLDK2~ #8		// replaces ISHLD28
		WRITE_ASCII 0x44 ~GSHLD01~ #8		// replaces GSSHLD
		WRITE_ASCII 0x58 ~CSHLD08~ #8		// replaces CSHLD28
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 46 END	// set item color, shield body: 46 RED replaces 59 LIGHT_PURPLE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 26 END	// set item color, shield hub: 26 WOOD replaces 98 LEAF_GREEN
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 29 STR_VAR insert = first END // set item color, shield panel: 29 RED-TINTED_BLACK
	BUT_ONLY
END

// Medium Shield +2: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld29.itm~) BEGIN
	COPY_EXISTING ~shld29.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD13~ #8		// replaces ISHLD29
		WRITE_ASCII 0x44 ~GSHLD03~ #8		// replaces GMSHLD
		WRITE_ASCII 0x58 ~CSHLD03~ #8		// replaces CSHLD29
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 38 END	// set item color, shield body: 38 LIGHT_DIRT_BROWN replaces 39 DARK_DIRT_BROWN
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 21 END	// set item color, shield hub: 21 DARK_IRON_GRAY replaces 27 GRAY
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 66 STR_VAR insert = first END // set item color, shield panel: 66 FADED_BLACK
	BUT_ONLY
END

// Large Shield +2: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld30.itm~) BEGIN
	COPY_EXISTING ~shld30.itm~ ~override~
		WRITE_ASCII 0x3A ~ISHLD07~ #8		// replaces ISHLD30
		WRITE_ASCII 0x44 ~GSHLD05~ #8		// replaces GLSHLD
		WRITE_LONG  0x50 6820				// General description
		WRITE_ASCII 0x58 ~CSHLD06~ #8		// replaces CSHLD30
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 25 END	// set item color, shield body: 25 DARK_PURE_GOLD replaces 91 DARK_CHOCOLATE
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 25 END	// set item color, shield hub: 25 DARK_PURE_GOLD replaces 27 GRAY
		LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
		LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 66 STR_VAR insert = first END // set item color, shield panel: 66 FADED_BLACK
	BUT_ONLY
END

// Darksteel Shield +4: modifies item icons and colours, and adds one effect (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~shld31.itm~) BEGIN
	COPY_EXISTING ~shld31.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ISHLDZS~ #8	// replaces ISHLD31
			WRITE_ASCII 0x44 ~GSHLD05~ #8	// replaces GLSHLD
			WRITE_ASCII 0x58 ~CSHLD07~ #8	// replaces PSHLD31
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 37 parameter1 = 31 END	// set item color, shield body: 31 LIGHT_SEA_BLUE replaces 60 DARK_PURPLE
			LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 32 parameter1 = 20 END	// set item color, shield hub: 20 DARK_MOLDY_GREEN replaces 57 LIGHT_BLUE
			LPF ~DELETE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 34 END	// deletes shield panel if present to make way for new one
			LPF ~CLONE_EFFECT~ INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 7 match_parameter2 = 37 parameter2 = 34 parameter1 = 21 STR_VAR insert = first END // set item color, shield panel: 21 DARK_IRON_GRAY
		END
	BUT_ONLY
END


/* ======================== *
 *          SWORDS          *
 * ======================== */

// Varscona +2: modify inventory icon (also modified by 400_1pp_update).
ACTION_FOR_EACH item IN ~killsw01~ ~sw1h06~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			WRITE_ASCII 0x3A ~ISW1HRN~ #8	// replaces ISW1H06
			LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1HRN END
		BUT_ONLY
	END
END

// Twinkle +3: modify inventory icon (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h16.itm~) BEGIN
	COPY_EXISTING ~sw1h16.itm~ ~override~
		WRITE_ASCII 0x3A ~ISW1H16~ #8		// replaces ISW1H15
		LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1H16 END
	BUT_ONLY
END

// Sword of Balduran: modify inventory icon (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h18.itm~) BEGIN
	COPY_EXISTING ~sw1h18.itm~ ~override~
		WRITE_ASCII 0x3A ~ISW1HBS~ #8		// replaces ISW1H18
		LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1HBS END
	BUT_ONLY
END

// Rashad's Talon +2: modify inventory icon (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h23.itm~) BEGIN
	COPY_EXISTING ~sw1h23.itm~ ~override~
		WRITE_ASCII 0x3A ~ISW1HRC~ #8		// replaces ISW1H23
		LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1HRC END
	BUT_ONLY
END

// The Burning Earth +1: modify item colors.
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h24.itm~) BEGIN
	COPY_EXISTING ~sw1h24.itm~ ~override~
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 20 parameter1 = 67 END // set item color, wpn grip/staff minor: 67 SHINY_GOLD replaces 115 SUNKISSED
		LPF ~ALTER_EFFECT~ INT_VAR silent = 1 check_headers = 0 match_opcode = 7 match_parameter2 = 21 parameter1 = 67 END // set item color, wpn head/blade minor: 67 SHINY_GOLD replaces 115 SUNKISSED
	BUT_ONLY
END

/* DEPRECATED as of v4.2.0
// Daystar +2: modify inventory icon (also modified by 400_1pp_update).
// Gwen fix: reverted to its original inventory icon ISW1H31. 1PP sets it ISW1H34 (Albruin +1), but EE does not validate this change.
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h31.itm~) BEGIN
	COPY_EXISTING ~sw1h31.itm~ ~override~
		WRITE_ASCII 0x3A ~ISW1H34~ #8		// replaces ISW1H31
		LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1H34 END
	BUT_ONLY
END

// Albruin +1: modify inventory icon (also modified by 400_1pp_update).
// Gwen fix: reverted to its original inventory icon ISW1H34. 1PP sets it to SW1H31 (Daystar +2 icon), but EE does not validate this change.
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h34.itm~) BEGIN
	COPY_EXISTING ~sw1h34.itm~ ~override~
		WRITE_ASCII 0x3A ~ISW1H31~ #8		// replaces ISW1H34
		LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1H31 END
	BUT_ONLY
END

// Long Sword +2: modify inventory icon (also modified by 400_1pp_update).
// Gwen fix: reverted to its original inventory icon ISW1H41. 1PP sets it to SW1H06 (Varscona +2 icon), but EE does not validate this change.
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h41.itm~) BEGIN
	COPY_EXISTING ~sw1h41.itm~ ~override~
		WRITE_ASCII 0x3A ~ISW1H06~ #8		// replaces ISW1H41
		LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1H06 END
	BUT_ONLY
END*/

// Water's Edge +3: modify inventory icon (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h52.itm~) BEGIN
	COPY_EXISTING ~sw1h52.itm~ ~override~
		WRITE_ASCII 0x3A ~ISW1HWK~ #8		// replaces ISW1H15
		LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1HWK END
	BUT_ONLY
END

// Short Sword of Mask +5: modify inventory icon.
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h59.itm~) BEGIN
	COPY_EXISTING ~sw1h59.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ISW1H59~ #8	// replaces ISW1H58
			LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1H59 END
		END
	BUT_ONLY
END

// Angurvadal +5: modify inventory icon.
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h61.itm~) BEGIN
	COPY_EXISTING ~sw1h61.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ISW1H61~ #8	// replaces ISW1H60
			LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1H61 END
		END
	BUT_ONLY
END

// Foebane +5: modify inventory icon (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h63.itm~) BEGIN
	COPY_EXISTING ~sw1h63.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ISW1H63~ #8	// replaces ISW1H62
			LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1H63 END
		END
	BUT_ONLY
END

// Purifier +5: modify inventory icon (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h65.itm~) BEGIN
	COPY_EXISTING ~sw1h65.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ISW1H65~ #8	// replaces ISW1H64
			LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1H65 END
		END
	BUT_ONLY
END

// Spectral Brand +5: modify inventory icon.
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h69.itm~) BEGIN
	COPY_EXISTING ~sw1h69.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ISW1H69~ #8	// replaces ISW1H68
			LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1H69 END
		END
	BUT_ONLY
END

// Hindo's Doom +4: modify inventory icon (also modified by 400_1pp_update).
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h71.itm~) BEGIN
	COPY_EXISTING ~sw1h71.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ISW1H71~ #8	// replaces ISW1H70
			LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW1H71 END
		END
	BUT_ONLY
END

// Cambion two handed sword: modify inventory icon.
ACTION_IF (FILE_EXISTS_IN_GAME ~demosum4.itm~) BEGIN
	COPY_EXISTING ~demosum4.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ISW2H03~ #8	// replaces ISW2H11
			LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW2H03 END
		END
	BUT_ONLY
END

/* DEPRECATED as of v4.2.0
// Carsomyr +5 & +6: modify inventory icon (also modified by 400_1pp_update).
// Gwen fix: reverts to their original inventory icon ISW2H10. 1PP sets it to ISW2H20, but EE does not validate this change.
ACTION_FOR_EACH item IN ~sw2h10~ ~sw2h19~ BEGIN
 ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x3A ~ISW2H20~ #8	// replaces ISW2H10
				LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW2H20 END
			END
		BUT_ONLY
	END
END

// Two-handed Sword +2: modify inventory icon (also modified by 400_1pp_update).
// Gwen fix: reverts to its original inventory icon ISW2H11. 1PP sets it to ISW2H03, but EE does not validate this change.
ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h11.itm~) BEGIN
	COPY_EXISTING ~sw2h11.itm~ ~override~
		WRITE_ASCII 0x3A ~ISW2H03~ #8			// replaces ISW2H11
		LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW2H03 END
	BUT_ONLY
END

// Two-handed Sword +3: modify inventory icon (also modified by 400_1pp_update).
// Gwen fix: reverts to its original inventory icon ISW2H20. 1PP sets it to ISW2H06, but EE does not validate this change.
ACTION_IF (FILE_EXISTS_IN_GAME ~sw2h20.itm~) BEGIN
	COPY_EXISTING ~sw2h20.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN		// protects against invalid files
			WRITE_ASCII 0x3A ~ISW2H06~ #8		// replaces ISW2H20
 			LPF ~ALTER_ITEM_HEADER~ INT_VAR header_type = 1 STR_VAR icon = ISW2H06 END
		END
	BUT_ONLY
END
*/


/* ================================= *
 *          COPY 1ppv2 BAMs          *
 * ================================= */

PRINT @200001 // ~Copying...~
SILENT

// Gwen fix: keeps a few vanilla inventory icons for modding purpose (Club of Detonation +3, Splint Mail +1, Chain Mail +3, Mage Robe of Cold Resistance, Mage Robe of Fire Resistance, Mage Robe of Electric Resistance, Knave's Robe, Traveler's Robe, Adventurer's Robe, Robes of the Good Neutral Evil Archmagi, Suryris's Blade +2, Ravager +4, Halberd +3, The Eyes of Truth, Helm of the Rock, Helm of the Rock, Leather Armor, Studded Leather Armor, Plate Mail, Mithral Field Plate +2, Quiver of Plenty +1, Bastard Sword +2, Celestial Fury +3, Short Sword of Mask +4, Angurvadal +4, Foebane +3, Purifier +4, Yamato +4, Usuno's Blade +4, Spectral Brand +4, Hindo's Doom +3, Bastard Sword +3, Katana +3, Scimitar +3, The Answerer +4, Gram the Sword of Grief +5). Instead of overwriting them, 1pp now saves them with "v" suffix before overwriting them.

ACTION_FOR_EACH bam IN iblun26 ichan05 ichan07 iclck09 iclck10 iclck11 iclck12 iclck13 iclck14 iclck15 iclck16 iclck17 ihalb03 ihalb10 ihalb12 ihelm06 ihelm31 ihelm32 ileat01 ileat04 iplat01 iplat09 iquiv01 isw1h42 isw1h51 isw1h58 isw1h60 isw1h62 isw1h64 isw1h66 isw1h67 isw1h68 isw1h70 isw1h72 isw1h75 isw1h76 isw1h77 isw2h17 BEGIN
	COPY_EXISTING ~%bam%.bam~	~override/%bam%v.bam~
END

COPY ~1pp/item/v2_copy/cshld19.bam~		~override~				// Pellan's Shield +2 (new)
COPY ~1pp/item/v2_copy/cshld20.bam~		~override~				// Kiel's Buckler (new)

COPY ~1pp/item/v2_copy/iax1h01.bam~		~override~				// Battle Axe (overwrite)

/* DEPRECATED as of v4.2.0
// Gwen fix: removes iax1h14.bam from the copying process because EE does not validate this change (IWD icon: The Celebrant's Blade).
COPY ~1pp/item/v2_copy/iax1h14.bam~	~override~					// Axe of the Unyielding +3 (overwrite)*/

COPY ~1pp/item/v2_copy/iblun01.bam~		~override~				// Club (overwrite)
COPY ~1pp/item/v2_copy/iblun04.bam~		~override~				// Mace (overwrite)
COPY ~1pp/item/v2_copy/iblun05.bam~		~override~				// Mace +1 (overwrite)
COPY ~1pp/item/v2_copy/iblun06.bam~		~override~				// Morning Star (overwrite)
COPY ~1pp/item/v2_copy/iblun26.bam~		~override~				// Club of Detonation +3 (overwrite)

COPY ~1pp/item/v2_copy/ibolts01.bam~	~override~				// Case of Plenty (overwrite)

COPY ~1pp/item/v2_copy/ibow26.bam~		~override~				// Shortbow +3 (overwrite). Gwen note: IWD icon (Messenger of Sseth).

COPY ~1pp/item/v2_copy/ichan04.bam~	 	~override~				// Splint Mail (overwrite). Gwen note: not validated by EE.
COPY ~1pp/item/v2_copy/ichan05.bam~	 	~override~				// Splint Mail +1 (overwrite)
COPY ~1pp/item/v2_copy/ichan07.bam~	 	~override~				// Chain Mail +3 (overwrite)

COPY ~1pp/item/v2_copy/iclck03.bam~	 	~override~				// Cloak of Displacement (overwrite)
COPY ~1pp/item/v2_copy/iclck04.bam~	 	~override~				// Relair's Mistake (overwrite)
COPY ~1pp/item/v2_copy/iclck05.bam~	 	~override~				// Cloak of Balduran (overwrite)
COPY ~1pp/item/v2_copy/iclck06.bam~	 	~override~				// Whispers of Silence (overwrite)
COPY ~1pp/item/v2_copy/iclck09.bam~	 	~override~				// Mage Robe of Cold Resistance (overwrite)
COPY ~1pp/item/v2_copy/iclck10.bam~	 	~override~				// Mage Robe of Fire Resistance (overwrite)
COPY ~1pp/item/v2_copy/iclck11.bam~	 	~override~				// Mage Robe of Electric Resistance (overwrite)
COPY ~1pp/item/v2_copy/iclck12.bam~	 	~override~				// Knave's Robe (overwrite)
COPY ~1pp/item/v2_copy/iclck13.bam~	 	~override~				// Traveler's Robe (overwrite)
COPY ~1pp/item/v2_copy/iclck14.bam~	 	~override~				// Adventurer's Robe (overwrite)
COPY ~1pp/item/v2_copy/iclck15.bam~		~override~				// Robe of the Good Archmagi (overwrite)
COPY ~1pp/item/v2_copy/iclck16.bam~	 	~override~				// Robe of the Neutral Archmagi (overwrite)
COPY ~1pp/item/v2_copy/iclck17.bam~		~override~				// Robe of the Evil Archmagi (overwrite)

/* DEPRECATED as of v4.2.0
// Gwen fix: removes bam from the copying process because EE does not validate this change (overwrites Boomerang Dagger's icon with Dagger of Venom's IMISC75)
COPY ~1pp/item/v2_copy/idagg11.bam~	 	~override~				// Boomerang Dagger +2 (overwrite)*/

COPY ~1pp/item/v2_copy/ihalb03.bam~		~override~				// Suryris's Blade +2 (overwrite)
COPY ~1pp/item/v2_copy/ihalb10.bam~		~override~				// Ravager +4 (overwrite)
COPY ~1pp/item/v2_copy/ihalb12.bam~		~override~				// Halberd +3 (overwrite)

// Gwen fix: adds a new setting (1pp_hammers_icons) allowing to make alternate the overwriting of the Runehammer icon (saves vanilla IHAMM10 icon and installs new IHAMM10 1pp icon as IHAMM05B) and not to set Borok's Fist's icon to Runehammers.
ACTION_IF (1pp_hammers_icons = 1) BEGIN
	COPY ~1pp/item/v2_copy/ihamm10.bam~	~override~				// Runehammer +4 (overwrite)
END ELSE BEGIN
	COPY ~1pp/item/v2_copy/ihamm10.bam~	~override/ihamm05b.bam~ // Save vanilla's Runehammer icon
END

COPY ~1pp/item/v2_copy/ihelm00.bam~		~override~				// Helmet (overwrite)
COPY ~1pp/item/v2_copy/ihelm01.bam~		~override~				// Helmet (overwrite)
COPY ~1pp/item/v2_copy/ihelm02.bam~		~override~				// Helmet (overwrite)
COPY ~1pp/item/v2_copy/ihelm03.bam~		~override~				// Helmet (overwrite)
COPY ~1pp/item/v2_copy/ihelm04.bam~		~override~				// Helmet (overwrite)
COPY ~1pp/item/v2_copy/ihelm05.bam~		~override~				// Helmet (overwrite)
COPY ~1pp/item/v2_copy/ihelm06.bam~		~override~				// Helmet (overwrite)	==> compon05
COPY ~1pp/item/v2_copy/ihelm07.bam~		~override~				// Helmet (overwrite)
COPY ~1pp/item/v2_copy/ihelm14.bam~		~override~				// Helm of Balduran (overwrite)
COPY ~1pp/item/v2_copy/ihelm31.bam~		~override~				// Helm of the Rock (overwrite)
COPY ~1pp/item/v2_copy/ihelm32.bam~		~override~				// Helm of the Rock (overwrite)

COPY ~1pp/item/v2_copy/ileat01.bam~		~override~				// Leather Armor (overwrite)
COPY ~1pp/item/v2_copy/ileat04.bam~		~override~				// Studded Leather Armor (overwrite)

COPY ~1pp/item/v2_copy/iplat01.bam~		~override~				// Plate Mail (overwrite)
COPY ~1pp/item/v2_copy/iplat09.bam~		~override~				// Mithral Field Plate +2 (overwrite)

COPY ~1pp/item/v2_copy/iplot01f.bam~	~override~				// Candle (overwrite)

COPY ~1pp/item/v2_copy/iqbull02.bam~	~override~				// Bag of Plenty +1 (new)
COPY ~1pp/item/v2_copy/iquiv01.bam~		~override~				// Quiver of Plenty +1 (overwrite)

COPY ~1pp/item/v2_copy/ishld17.bam~		~override~				// Buckler +1 (overwrite)
COPY ~1pp/item/v2_copy/ishldds.bam~		~override~				// Dragon Scale Shield +2 (new)
COPY ~1pp/item/v2_copy/ishldfs.bam~		~override~				// Fortress Shield +3 (new)
COPY ~1pp/item/v2_copy/ishldgn.bam~		~override~				// Saving Grace +3: (new)
COPY ~1pp/item/v2_copy/ishldhm.bam~		~override~				// Shield of Harmony +2 (new)
COPY ~1pp/item/v2_copy/ishldk2.bam~		~override~				// Small Shield +2 (new)
COPY ~1pp/item/v2_copy/ishldrf.bam~		~override~				//  (new) 24
COPY ~1pp/item/v2_copy/ishldvr.bam~		~override~				// Shield of the Lost +2 (new)
COPY ~1pp/item/v2_copy/ishldzs.bam~		~override~				// Darksteel Shield +4 (new)

COPY ~1pp/item/v2_copy/isw1h02.bam~		~override~				// Bastard Sword +1 (overwrite)

/* DEPRECATED as of v4.2.0
// Gwen fix: Does not overwrite Varscona's icon with a clone of isw1h41 (Long Sword +2) because EE does not validate this change.
COPY ~1pp/item/v2_copy/isw1h06.bam~		~override~				// Varscona +2 (overwrite)*/

COPY ~1pp/item/v2_copy/isw1h16.bam~		~override~				// Twinkle +3 (overwrite)
COPY ~1pp/item/v2_copy/isw1h42.bam~		~override~				// Bastard Sword +2 (overwrite)
COPY ~1pp/item/v2_copy/isw1h51.bam~		~override~				// Celestial Fury +3 (overwrite)
COPY ~1pp/item/v2_copy/isw1h58.bam~		~override~				// Short Sword of Mask +4 (overwrite)
COPY ~1pp/item/v2_copy/isw1h59.bam~		~override~				// Short Sword of Mask +5 (new)
COPY ~1pp/item/v2_copy/isw1h60.bam~		~override~				// Angurvadal +4 (overwrite)
COPY ~1pp/item/v2_copy/isw1h61.bam~		~override~				// Angurvadal +5 (new)
COPY ~1pp/item/v2_copy/isw1h62.bam~		~override~				// Foebane +3 (overwrite)
COPY ~1pp/item/v2_copy/isw1h63.bam~		~override~				// Foebane +5 (new)
COPY ~1pp/item/v2_copy/isw1h64.bam~		~override~				// Purifier +4 (overwrite)
COPY ~1pp/item/v2_copy/isw1h65.bam~		~override~				// Purifier +5 (new)
COPY ~1pp/item/v2_copy/isw1h66.bam~		~override~				// Yamato +4 (overwrite)
COPY ~1pp/item/v2_copy/isw1h67.bam~		~override~				// Usuno's Blade +4 (overwrite)
COPY ~1pp/item/v2_copy/isw1h68.bam~		~override~				// Spectral Brand +4 (overwrite)
COPY ~1pp/item/v2_copy/isw1h69.bam~		~override~				// Spectral Brand +5 (new)
COPY ~1pp/item/v2_copy/isw1h70.bam~		~override~				// Hindo's Doom +3 (overwrite)
COPY ~1pp/item/v2_copy/isw1h71.bam~		~override~				// Hindo's Doom +4 (new)
COPY ~1pp/item/v2_copy/isw1h72.bam~		~override~				// Bastard Sword +3 (overwrite)
COPY ~1pp/item/v2_copy/isw1h73.bam~		~override~				// Long Sword +3 (overwrite)
COPY ~1pp/item/v2_copy/isw1h74.bam~		~override~				// Short Sword +3 (overwrite)
COPY ~1pp/item/v2_copy/isw1h75.bam~		~override~				// Katana +3 (overwrite)
COPY ~1pp/item/v2_copy/isw1h76.bam~		~override~				// Scimitar +3 (overwrite)
COPY ~1pp/item/v2_copy/isw1h77.bam~		~override~				// The Answerer +4 (overwrite)
COPY ~1pp/item/v2_copy/isw1hbs.bam~		~override~				// Sword of Balduran (new)
COPY ~1pp/item/v2_copy/isw1hrc.bam~		~override~				// Rashad's Talon +2 (new)
COPY ~1pp/item/v2_copy/isw1hrn.bam~		~override~				// Varscona +2 (new)
COPY ~1pp/item/v2_copy/isw1hwk.bam~		~override~				// Water's Edge +3 (new)

// Gwen fix: Does not overwrite Harbinger's icon and copies an alternate resource for modding purpose. This way, Harbinger keeps its golden icon which fits to its colors settings.
COPY ~1pp/item/v2_copy/isw2h07.bam~		~override/1isw2h07.bam~	// Harbinger +3 (overwrite)

COPY ~1pp/item/v2_copy/isw2h17.bam~		~override~				// Gram the Sword of Grief +5 (overwrite)
COPY ~1pp/item/v2_copy/isw2h20.bam~		~override~				// Two-handed Sword +3 (overwrite)

COPY ~1pp/item/v2_copy/iwand01.bam~		~override~				// Wand (overwrite)
COPY ~1pp/item/v2_copy/iwand02.bam~		~override~				// Wand of Fear (overwrite)
COPY ~1pp/item/v2_copy/iwand03.bam~		~override~				// Wand of Magic Missiles (overwrite)
COPY ~1pp/item/v2_copy/iwand04.bam~		~override~				// Wand of Paralyzation (overwrite)
COPY ~1pp/item/v2_copy/iwand05.bam~		~override~				// Wand of Fire (overwrite)
COPY ~1pp/item/v2_copy/iwand06.bam~		~override~				// Wand of Frost (overwrite)
COPY ~1pp/item/v2_copy/iwand07.bam~		~override~				// Wand of Lightning (overwrite)
COPY ~1pp/item/v2_copy/iwand08.bam~		~override~				// Wand of Sleep (overwrite)
COPY ~1pp/item/v2_copy/iwand09.bam~		~override~				// Wand of Polymorphing (overwrite)
COPY ~1pp/item/v2_copy/iwand10.bam~		~override~				// Wand of Monster Summoning (overwrite)
COPY ~1pp/item/v2_copy/iwand11.bam~		~override~				// Wand of the Heavens (overwrite)

// Water's Edge +3: wrong identified name fix moved from 400_update_bgii_misc.tpa because Core content patches component installs it and is a pre-requisite for Core updates and item patches component.
COPY ~1pp/item/v2_copy/sw1hwk.itm~		~override~
	SAY NAME2 @400801


/* ========================= *
 *          POTIONS          *
 * ========================= */

ACTION_IF (1pp_potions_icons = 1) BEGIN
	PRINT @200001 // ~Copying...~
	SILENT
	COPY ~1pp/item/v2_copy/ipotn52.bam~ ~override~
	COPY_EXISTING ~potn52.itm~ ~override~
	  WRITE_ASCII 0x58 ~cpotn02~ #8
	BUT_ONLY
	COPY ~1pp/item/v2_copy/ipotn55.bam~ ~override~
	COPY_EXISTING ~potn55.itm~ ~override~
	  WRITE_ASCII 0x58 ~cpotn41~ #8
	BUT_ONLY
END


/* ================================ *
 *          BW HERBS STUFF          *
 * ================================ */

ACTION_IF (is_bw_herbs) BEGIN // FILE_EXISTS_IN_GAME ~bw02chb1.bam~

	PRINT @200003 // ~BW Herbs mod detected. Installing patches...~
	SILENT

	// Gwen fix: typo (bw02ipo1_l instead of bw02ipo1).
	ACTION_FOR_EACH icon IN ~bw02chb1~ ~bw02chb2~ ~bw02chb3~ ~bw02chb4~ ~bw02chb5~ ~bw02idg1~ ~bw02idg2~ ~bw02ihb1~ ~bw02ihb2~ ~bw02ihb3~ ~bw02ihb4~ ~bw02ihb5~ ~bw02ipo1~ ~bw02ipo3~ ~bw02ist1~ ~bw02ist2~ BEGIN
		COPY ~1pp/item/bw_herbs_bg2/bam/%icon%.bam~ ~override~
	END

	ACTION_FOR_EACH item IN ~bw02blun~ ~bw02dg1~ ~bw02dg2~ ~bw02dg3~ ~bw02dg4~ ~bw02dg5~ ~bw02dg6~ ~bw02po02~ ~bw02po04~ ~bw02po05~ ~bw02po06~ ~bw02po07~ ~bw02po09~ ~bw02po10~ ~bw02st1~ ~bw02st2~ ~bw02st3~ ~bw02st4~ ~bw02st5~ ~bw02st6~ BEGIN

		OUTER_SET uname = 0
		OUTER_SET iname = 0
		OUTER_SET udesc = 0
		OUTER_SET idesc = 0

		ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
			COPY_EXISTING ~%item%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
					READ_LONG 0x8 uname
					READ_LONG 0xc iname
					READ_LONG 0x50 udesc
					READ_LONG 0x54 idesc
				 END

			COPY ~1pp/item/bw_herbs_bg2/itm/%item%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
					WRITE_LONG 0x8 uname
					WRITE_LONG 0xc iname
					WRITE_LONG 0x50 udesc
					WRITE_LONG 0x54 idesc
				END

		END

	END

END

//END of COMPONENT