/* ================================================================================================================================================================================== *
 *  v 4.2.0                                                                                                                                                                           *
 *                                                      C O M P O N E N T   :   C o l o u r a b l e   Q u a r t e r s t a v e s                                                       *
 *                                                                                                                                                                                    *
 * ================================================================================================================================================================================== *
 *  This component makes quarterstaves colourable by segment (as opposed to uniform) to allow more variety in-game and match inventory depictions.                                    *
 *  It also includes item patches to make use of the new content. (Presented in Technicolour!)                                                                                        *
 * ================================================================================================================================================================================== *
 *  change-log:                                                                                                                                                                       *
 *  -----------                                                                                                                                                                       *
 *     - Coding simplification:                                                                                                                                                       *
 *          Copied entire folders instead of infinite lines (COPY ~1pp/folder/file.ext~ ~override~ or ACTION_FOR_EACH file IN list BEGIN COPY ~1pp/folder/file.ext~ ~override~ END).  *
 *          Grouped actions or patches with ACTION_FOR_EACH and PATCH_FOR_EACH whenever possible.                                                                                     *
 *          Used new 1pp_compatibility.tph library to improve 1PP crossmods compatibility (Bolsa, Rolles, Ruad, Stuff of the Magi and The Unusual Oddities Shop).                     *
 * ================================================================================================================================================================================== */

// ----------------------------- //
//     ITEMS               line  //
// ----------------------------- //
//  CORE ITEM PATCHES    #   45  //
//  ORDINARY STAVES      #  253  //
//  MODS STAVES          #  823  //
// ----------------------------- //

/* =============================== *
 *  COLOURABLE QUARTERSTAVES CORE  *
 * =============================== */

PRINT @204000 // ~Installing Colourable Quarterstaves core~

PRINT @204001 // ~Copying...~
SILENT

COPY ~1pp/additions/obj_anim/qs~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu OR is_iwd) BEGIN // (GAME_IS ~totlm how bg2 tob tutu tutu_totsc ca~)
	COPY ~1pp/additions/obj_1pp/wplqsinv.bam~ ~override~
	COPY ~1pp/additions/obj_1pp/wpmqsinv.bam~ ~override~
	COPY ~1pp/additions/obj_1pp/wpnqsinv.bam~ ~override~
	COPY ~1pp/additions/obj_1pp/wpsqsinv.bam~ ~override~
END


/* =================== *
 *  CORE ITEM PATCHES  *
 * =================== */

PRINT @204002 // ~Installing core item patches~

PRINT @204003 // ~Patching...~
SILENT

// Quaterstaff +3
ACTION_IF (FILE_EXISTS_IN_GAME ~enstaff.itm~) BEGIN
	COPY_EXISTING ~enstaff.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 25		// sets colour index 25 DARK_PURE_GOLD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 21		// sets colour index 21 DARK_IRON_GRAY
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 109		// sets colour index 109 TERRA_COTTA
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 27		// sets colour index 27 GRAY
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Quarterstaff
ACTION_IF (FILE_EXISTS_IN_GAME ~hgnya01.itm~) BEGIN
	COPY_EXISTING ~hgnya01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 23		// 23 LIGHT_COPPER replaces colour index 25 DARK_PURE_GOLD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 36		// sets colour index 36 LIGHT_DIRTY_YELLOW
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 25		// sets colour index 25 DARK_PURE_GOLD
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 23		// sets colour index 23 LIGHT_COPPER
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 27		// sets colour index 27 GRAY
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Quarterstaff
ACTION_IF (FILE_EXISTS_IN_GAME ~hgwra01.itm~) BEGIN
	COPY_EXISTING ~hgwra01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET setr = 0x60			// Set Red
			SET setg = 0x00			// Set Green
			SET setb = 0x71			// Set Blue
			SET speed = 0x1E		// Speed
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~pulse~
			SET setr = 0x00
			SET setg = 0x00
			SET setb = 0xC0
			SET speed = 0x14
			SET location = wteal	// location (Staff minor)
			LPM ~pulse~
			SET setr = 0x63
			SET setg = 0x63
			SET setb = 0xE6
			SET speed = 0x0C
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~pulse~
			SET setr = 0x6D
			SET setg = 0x6D
			SET setb = 0xFF
			SET speed = 0x0C
			SET location = wblue	// location (Head/Blade minor)
			LPM ~pulse~
			SET setr = 0x60	
			SET setg = 0x00
			SET setb = 0x71
			SET speed = 0x1E
			SET location = wred		// location * compatibility
			LPM ~pulse~
		END
	BUT_ONLY
END

// Shaman's Staff
ACTION_IF (FILE_EXISTS_IN_GAME ~misc5t.itm~) BEGIN
	COPY_EXISTING ~misc5t.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 11		// 11 LIGHT_ROSE_RED replaces colour index 27 GRAY
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 24		// sets colour index 24 BROWN_GOLD
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 19		// sets colour index 19 DARK_ROSE_RED
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 26		// sets colour index 26 WOOD
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Staff
ACTION_IF (FILE_EXISTS_IN_GAME ~misc9o.itm~) BEGIN
	COPY_EXISTING ~misc9o.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 23		// sets colour index 23 LIGHT_COPPER
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Rod of Smiting
ACTION_IF (FILE_EXISTS_IN_GAME ~rods04.itm~) BEGIN
	COPY_EXISTING ~rods04.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 102		// sets colour index 102 SEA_BLUE
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 96		// sets colour index 96 CHROME_BLUE
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 91		// sets colour index 91 DARK_CHOCOLATE
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 102		// sets colour index 102 SEA_BLUE
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Rod of Terror
ACTION_IF (FILE_EXISTS_IN_GAME ~rods05.itm~) BEGIN
	COPY_EXISTING ~rods05.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 5		// sets colour index 5 MEDIUM_SILVER
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 6		// sets colour index 6 DARK_SILVER
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 5		// sets colour index 5 MEDIUM_SILVER
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 3		// sets colour index 3 LIGHT_GOLD
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Quarterstaff
ACTION_IF (FILE_EXISTS_IN_GAME ~sahstaff.itm~) BEGIN
	COPY_EXISTING ~sahstaff.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 22		// 22 DARK_BROWN replaces colour index 27 GRAY
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 90		// sets colour index 90 MOLDY_GOLD
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END


/* ================= *
 *  ORDINARY STAVES  *
 * ================= */

// Quarterstaff
ACTION_FOR_EACH item IN ~staf01~ ~_staf01~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
				LPM ~clear~
				SET gradient = 22		// 22 DARK_BROWN replaces colour index 27 GRAY
				SET location = wgrey	// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 90		// sets colour index 90 MOLDY_GOLD
				SET location = wteal	// location (Staff minor)
				LPM ~colour~
				SET gradient = 22		// sets colour index 22 DARK_BROWN
				SET location = wblue	// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 22		// sets colour index 22 DARK_BROWN
				SET location = wred		// location * compatibility
				LPM ~colour~
			END
		BUT_ONLY
	END
END

// Quarterstaff +1
ACTION_FOR_EACH item IN ~staf02~ ~_staf02~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
				LPM ~clear~
				SET gradient = 25		// sets colour index 25 DARK_PURE_GOLD
				SET location = wgrey	// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 21		// sets colour index 21 DARK_IRON_GRAY
				SET location = wteal	// location (Staff minor)
				LPM ~colour~
				SET gradient = 25		// sets colour index 25 DARK_PURE_GOLD
				SET location = wpink	// location (Bolt-Mace-Staff)
				LPM ~colour~
				SET gradient = 5		// sets colour index 5 MEDIUM_SILVER
				SET location = wblue	// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 27		// sets colour index 27 GRAY
				SET location = wred		// location * compatibility
				LPM ~colour~
			END
		BUT_ONLY
	END
END

// Quarterstaff
ACTION_IF (FILE_EXISTS_IN_GAME ~staf03.itm~) BEGIN
	COPY_EXISTING ~staf03.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 2		// 2 DARK_GOLD replaces colour index 27 GRAY
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 90		// sets colour index 90 MOLDY_GOLD
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 2		// sets colour index 2 DARK_GOLD
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Quarterstaff
ACTION_FOR_EACH item IN ~staf04~ ~_staf04~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
				LPM ~clear~
				SET gradient = 2		// sets colour index 2 DARK_GOLD
				SET location = wgrey	// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 90		// sets colour index 90 MOLDY_GOLD
				SET location = wteal	// location (Staff minor)
				LPM ~colour~
				SET gradient = 2		// sets colour index 2 DARK_GOLD
				SET location = wblue	// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 22		// sets colour index 22 DARK_BROWN
				SET location = wred		// location * compatibility
				LPM ~colour~
			END
		BUT_ONLY
	END
END

// Staff of Striking +3
ACTION_FOR_EACH item IN ~staf05~ ~_staf05~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
				LPM ~clear~
				SET gradient = 25		// sets colour index 25 DARK_PURE_GOLD
				SET location = wgrey	// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 21		// sets colour index 21 DARK_IRON_GRAY
				SET location = wteal	// location (Staff minor)
				LPM ~colour~
				SET gradient = 109		// sets colour index 109 TERRA_COTTA
				SET location = wpink	// location (Bolt-Mace-Staff)
				LPM ~colour~
				SET gradient = 27		// sets colour index 27 GRAY
				SET location = wblue	// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 27		// sets colour index 27 GRAY
				SET location = wred		// location * compatibility
			END
		BUT_ONLY
	END
END

// Martial Staff +3
ACTION_FOR_EACH item IN ~staf08~ ~_staf08~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
				LPM ~clear~
				SET gradient = 81		// 81 FADED_GOLD replaces colour index 55
				SET location = wgrey	// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 66		// sets colour index 66 FADED_BLACK
				SET location = wteal	// location (Staff minor)
				LPM ~colour~
				SET gradient = 83		// sets colour index 83 DARK_BLUISH_GRAY
				SET location = wpink	// location (Bolt-Mace-Staff)
				LPM ~colour~
				SET gradient = 85		// sets colour index 85 PURE_GOLD
				SET location = wblue	// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 85		// sets colour index 85 PURE_GOLD
				SET location = wred		// location * compatibility
				LPM ~colour~
				SET setr = 0x00
				SET setg = 0x14
				SET setb = 0x14
				SET location = wgrey	// location (Head/Blade/Staff major)
				LPM ~glow~
				SET setr = 0x00
				SET setg = 0x19
				SET setb = 0x19
				SET location = wteal	// location  (Staff minor)
				LPM ~glow~
				SET setr = 0x00
				SET setg = 0x28
				SET setb = 0x28
				SET location = wpink	// location (Bolt-Mace-Staff)
				LPM ~glow~
				SET setr = 0x00
				SET setg = 0x1E
				SET setb = 0x1E
				SET location = wblue	// location (Head/Blade minor)
				LPM ~glow~
				SET setr = 0x00
				SET setg = 0x28
				SET setb = 0x28
				SET location = wred		// location * compatibility
				LPM ~glow~
			END
		BUT_ONLY
	END
END

// Staff of Command
ACTION_IF (FILE_EXISTS_IN_GAME ~staf09.itm~) BEGIN
	COPY_EXISTING ~staf09.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 14		// 14 DARK_PURE_SILVER replaces colour index 10 LIGHT_PURE_GOLD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 19		// sets colour index 19 DARK_ROSE_RED
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 21		// sets colour index 21 DARK_IRON_GRAY
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 13		// sets colour index 13 LIGHT_PINKISH_SILVER
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 10		// sets colour index 10 LIGHT_PURE_GOLD
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Staff of Curing
ACTION_IF (FILE_EXISTS_IN_GAME ~staf10.itm~) BEGIN
	COPY_EXISTING ~staf10.itm~ ~override~
		LPF ~1pp_staf10_0~ END
	BUT_ONLY
END

// Staff of the Magi
ACTION_IF (FILE_EXISTS_IN_GAME ~staf11.itm~) BEGIN
	COPY_EXISTING ~staf11.itm~ ~override~
		LPF ~1pp_staf11_0~ END
	BUT_ONLY
END

// Staff of Power
ACTION_IF (FILE_EXISTS_IN_GAME ~staf12.itm~) BEGIN
	COPY_EXISTING ~staf12.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 25		// sets colour index 25 DARK_PURE_GOLD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 21		// sets colour index 21 DARK_IRON_GRAY
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 25		// sets colour index 25 DARK_PURE_GOLD
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 5		// sets colour index 5 MEDIUM_SILVER
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 27		// sets colour index 27 GRAY
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Staff of Thunder and Lightning +2
ACTION_IF (FILE_EXISTS_IN_GAME ~staf13.itm~) BEGIN
	COPY_EXISTING ~staf13.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 18		//  18 BLUE replaces colour index 104 DARK_CHROME_PURPLE
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 100		// sets colour index 100 DARK_ASH_GRAY
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 101		// sets colour index 101 METALLIC_RED
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 96		// sets colour index 96 CHROME_BLUE
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 104		// sets colour index 104 DARK_CHROME_PURPLE
			SET location = wred		// location * compatibility
			LPM ~colour~
			SET setr = 0xC6
			SET setg = 0xD5
			SET setb = 0xDE
			SET speed = 0x14
			SET location = wteal	// location (Staff minor)
			LPM ~pulse~
		END
	BUT_ONLY
END

// Staff of the Woodlands +4
ACTION_IF (FILE_EXISTS_IN_GAME ~staf14.itm~) BEGIN
	COPY_EXISTING ~staf14.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 16		// 16 SILVERISH_GOLD replaces colour index 39 DARK_DIRT_BROWN
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 19		// sets colour index 19 DARK_ROSE_RED
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 16		// sets colour index 16 SILVERISH_GOLD
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 39		// sets colour index 39 DARK_DIRT_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Staff of Air +2
ACTION_IF (FILE_EXISTS_IN_GAME ~staf15.itm~) BEGIN
	COPY_EXISTING ~staf15.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 14		// 14 DARK_PURE_SILVER replaces colour index 25 DARK_PURE_GOLD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 17		// sets colour index 17 PALE_BLUE
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 28		// sets colour index 28 BLUISH_SILVER
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 27		// sets colour index 27 GRAY
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 27		// sets colour index 27 GRAY
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Staff of Earth +2
ACTION_IF (FILE_EXISTS_IN_GAME ~staf16.itm~) BEGIN
	COPY_EXISTING ~staf16.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 38		// 38 LIGHT_DIRT_BROWN replaces colour index 39 DARK_DIRT_BROWN
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 20		// sets colour index 20 DARK_MOLDY_GREEN
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 39		// sets colour index 39 DARK_DIRT_BROWN
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 38		// sets colour index 38 LIGHT_DIRT_BROWN
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 39		// sets colour index 39 DARK_DIRT_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Staff of Fire +2
ACTION_IF (FILE_EXISTS_IN_GAME ~staf17.itm~) BEGIN
	COPY_EXISTING ~staf17.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 10		// sets colour index 10 LIGHT_PURE_GOLD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 11		// sets colour index 11 LIGHT_ROSE_RED
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 111		// sets colour index 111 BURNT_SIENNA
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 12		// sets colour index 12 LIGHT_CARNATION_PINK
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 10		// sets colour index 10 LIGHT_PURE_GOLD
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Quarterstaff +2
ACTION_IF (FILE_EXISTS_IN_GAME ~staf18.itm~) BEGIN
	COPY_EXISTING ~staf18.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 25		// 25 DARK_PURE_GOLD replaces colour index 39 DARK_DIRT_BROWN
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 66		// sets colour index 66 FADED_BLACK
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 81		// sets colour index 81 FADED_GOLD
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 43		// sets colour index 43 DARK_BEIGE
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 39		// sets colour index 39 DARK_DIRT_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Cleric's Staff +3
ACTION_IF (FILE_EXISTS_IN_GAME ~staf19.itm~) BEGIN
	COPY_EXISTING ~staf19.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 105		// 105 OFF_WHITE replaces colour index 97 LIGHT_MINTY_BLUE
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 96		// sets colour index 96 CHROME_BLUE
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 97		// sets colour index 97 LIGHT_MINTY_BLUE
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 97		// sets colour index 97 LIGHT_MINTY_BLUE
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 97		// sets colour index 97 LIGHT_MINTY_BLUE
			SET location = wred		// location * compatibility
			LPM ~colour~
			SET setr = 0x00
			SET setg = 0x8B
			SET setb = 0xCA
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~glow~
			SET setr = 0x00
			SET setg = 0x77
			SET setb = 0xB6
			SET location = wteal	// location (Staff minor)
			LPM ~glow~
			SET setr = 0x00
			SET setg = 0x90
			SET setb = 0xD0
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~glow~
			SET setr = 0x00
			SET setg = 0x8B
			SET setb = 0xCA
			SET location = wblue	//location (Head/Blade minor)
			LPM ~glow~
			SET setr = 0x00
			SET setg = 0x8B
			SET setb = 0xCA
			SET location = wred		// location * compatibility
			LPM ~glow~
		END
	BUT_ONLY
END

// Staff of Rynn +4
ACTION_IF (FILE_EXISTS_IN_GAME ~staf20.itm~) BEGIN
	COPY_EXISTING ~staf20.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 97		// sets colour index 97 LIGHT_MINTY_BLUE
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 96		// sets colour index 96 CHROME_BLUE
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 97		// sets colour index 97 LIGHT_MINTY_BLUE
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 97		// sets colour index 97 LIGHT_MINTY_BLUE
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 97		// sets colour index 97 LIGHT_MINTY_BLUE
			SET location = wred		// location * compatibility
			LPM ~colour~
			SET setr = 0x00
			SET setg = 0x8B
			SET setb = 0xCA
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~glow~
			SET setr = 0x00	
			SET setg = 0x77
			SET setb = 0xB6
			SET location = wteal	// location (Staff minor)
			LPM ~glow~
			SET setr = 0x00
			SET setg = 0x90
			SET setb = 0xD0
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~glow~
			SET setr = 0x00
			SET setg = 0x8B
			SET setb = 0xCA
			SET location = wblue	// location (Head/Blade minor)
			LPM ~glow~
			SET setr = 0x00
			SET setg = 0x8B
			SET setb = 0xCA
			SET location = wred		// location * compatibility
			LPM ~glow~
		END
	BUT_ONLY
END

// Staff of the Ram +4 and +6
ACTION_FOR_EACH item IN ~staf21~ ~staf22~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
		COPY_EXISTING ~%item%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
				LPM ~clear~
				SET gradient = 42		// 42 BEIGE replaces colour index 36 LIGHT_DIRTY_YELLOW
				SET location = wgrey	// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 37		// sets colour index 37 DARK_DIRTY_YELLOW
				SET location = wteal	// location (Staff minor)
				LPM ~colour~
				SET gradient = 36		// sets colour index 36 LIGHT_DIRTY_YELLOW
				SET location = wpink	// location (Bolt-Mace-Staff)
				LPM ~colour~
				SET gradient = 42		// sets colour index 42 BEIGE
				SET location = wblue	// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 36		// sets colour index 36 LIGHT_DIRTY_YELLOW
				SET location = wred		// location * compatibility
				LPM ~colour~
			END
		BUT_ONLY
	END
END

// Serpent Shaft
ACTION_IF (FILE_EXISTS_IN_GAME ~staf23.itm~) BEGIN
	COPY_EXISTING ~staf23.itm~ ~override~
		LPF ~1pp_staf23_0~ END
	BUT_ONLY
END

// Quarterstaff +3
ACTION_IF (FILE_EXISTS_IN_GAME ~staf24.itm~) BEGIN
	COPY_EXISTING ~staf24.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 25		// 25 DARK_PURE_GOLD replaces colour index 39 DARK_DIRT_BROWN
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 66		// sets colour index 66 FADED_BLACK
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 81		// sets colour index 81 FADED_GOLD
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 43		// sets colour index 43 DARK_BEIGE
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 39		// sets colour index 39 DARK_DIRT_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
	BUT_ONLY
END

// Staff of Arundel +3
ACTION_IF (FILE_EXISTS_IN_GAME ~wastaff.itm~) BEGIN
	COPY_EXISTING ~wastaff.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 10		// 10 LIGHT_PURE_GOLD replaces colour index 25 DARK_PURE_GOLD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 15		// sets colour index 15 PASTEL_GREEN
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 10		// sets colour index 10 LIGHT_PURE_GOLD
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 10		// sets colour index 10 LIGHT_PURE_GOLD
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 27		// sets colour index 27 GRAY
			SET location = wred		// location * compatibility
			LPM ~colour~
			SET setr = 0x4C
			SET setg = 0xFF
			SET setb = 0x00
			SET location = wteal	// location (Staff minor)
			LPM ~glow~
		END
	BUT_ONLY
END


/* ============= *
 *  MODS STAVES  *
 * ============= */

PRINT @204004 // ~Installing mod item patches (if found).~

PRINT @204003 // ~Patching...~
SILENT

/* ----------- *
 *  Bolsa mod  *
 * ----------- */

// Staff of Magus
ACTION_IF (FILE_EXISTS_IN_GAME ~mhconti.itm~) BEGIN
	COPY_EXISTING ~mhconti.itm~ ~override~
		LPF ~1pp_staf11_0~ END
	BUT_ONLY
END

/* ---------------------------------------------- *
 *  Herbs and Potions Add-in for BG2 by Baronius  *
 * ---------------------------------------------- */

// Poisonkiss Staff +1
ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st1.itm~) BEGIN
	COPY_EXISTING ~bw02st1.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 81		// sets colour index 81 FADED_GOLD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 15		// sets colour index 15 PASTEL_GREEN
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 25		// sets colour index 25 DARK_PURE_GOLD
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 27		// sets colour index 27 GRAY
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
END

// Firebeard Staff +1
ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st2.itm~) BEGIN
COPY_EXISTING ~bw02st2.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 26		// sets colour index 26 WOOD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 19		// sets colour index 19 DARK_ROSE_RED
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 19		// sets colour index 19 DARK_ROSE_RED
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 24		// sets colour index 24 BROWN_GOLD
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
END

// Poisonkiss Staff +2
ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st3.itm~) BEGIN
	COPY_EXISTING ~bw02st3.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 81		// sets colour index 81 FADED_GOLD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 15		// sets colour index 15 PASTEL_GREEN
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 25		// sets colour index 25 DARK_PURE_GOLD
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 27		// sets colour index 27 GRAY
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
END

// Firebeard Staff +2
ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st4.itm~) BEGIN
	COPY_EXISTING ~bw02st4.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 26		// sets colour index 26 WOOD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 19		// sets colour index 19 DARK_ROSE_RED
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 19		// sets colour index 19 DARK_ROSE_RED
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 24		// sets colour index 24 BROWN_GOLD
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
END

// Poisonkiss Staff +3
ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st5.itm~) BEGIN
	COPY_EXISTING ~bw02st5.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 81		// sets colour index 81 FADED_GOLD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 15		// sets colour index 15 PASTEL_GREEN
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 25		// sets colour index 25 DARK_PURE_GOLD
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 27		// sets colour index 27 GRAY
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
END

// Firebeard Staff +3
ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st6.itm~) BEGIN
	COPY_EXISTING ~bw02st6.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
			LPM ~clear~
			SET gradient = 26		// sets colour index 26 WOOD
			SET location = wgrey	// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 19		// sets colour index 19 DARK_ROSE_RED
			SET location = wteal	// location (Staff minor)
			LPM ~colour~
			SET gradient = 19		// sets colour index 19 DARK_ROSE_RED
			SET location = wpink	// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 24		// sets colour index 24 BROWN_GOLD
			SET location = wblue	// location (Head/Blade minor)
			LPM ~colour~
			SET gradient = 22		// sets colour index 22 DARK_BROWN
			SET location = wred		// location * compatibility
			LPM ~colour~
		END
END


/* ------------ *
 *  Rolles mod  *
 * ------------ */

// Enhanced Staff of Curing
ACTION_IF (FILE_EXISTS_IN_GAME ~s#staf01.itm~) BEGIN
	COPY_EXISTING ~s#staf01.itm~ ~override~
		LPF ~1pp_staf10_0~ END
	BUT_ONLY
END

// Enhanced Staff of the Magi
ACTION_IF (FILE_EXISTS_IN_GAME ~s#staf02.itm~) BEGIN
	COPY_EXISTING ~s#staf02.itm~ ~override~
		LPF ~1pp_staf11_0~ END
	BUT_ONLY
END


/* -------------------- *
 *  Ruad Ro'fhessa mod  *
 * -------------------- */

// Staff of Resurrection
ACTION_IF (FILE_EXISTS_IN_GAME ~u#staf04.itm~) BEGIN
	COPY_EXISTING ~u#staf04.itm~ ~override~
		LPF ~1pp_staf10_0~ END
	BUT_ONLY
END


/* ----------------------- *
 *  Stuff of the Magi mod  *
 * ----------------------- */

// Staff of the Magi
ACTION_IF (FILE_EXISTS_IN_GAME ~wzrdstaf.itm~) BEGIN
	COPY_EXISTING ~wzrdstaf.itm~ ~override~
		LPF ~1pp_staf11_0~ END
	BUT_ONLY
END


/* ------------------------------- *
 *  The Unusual Oddities Shop mod  *
 * ------------------------------- */

// Staff of the Dragon +3
ACTION_IF (FILE_EXISTS_IN_GAME ~r#asmstf.itm~) BEGIN
	COPY_EXISTING ~r#asmstff.itm~ ~override~
		LPF ~1pp_staf23_0~ END
	BUT_ONLY
END


// END of COMPONENT