/* ================================================================================================================================================= *
 *  v 4.2.0                                                                                                                                   T w o  *
 *                                        C O M P O N E N T   :   W i z a r d s '    S t a v e s   (c o r e)                                         *
 *                                                                                                                                                   *
 * ================================================================================================================================================= *
 *  his component includes one new animation (wizard's staff) as well as several new paperdoll appearances for regular colourable quarterstaves.     *
 * ================================================================================================================================================= *
 *  change-log:                                                                                                                                      *
 *  -----------                                                                                                                                      *
 *      - Coding simplification:                                                                                                                     *
 *          Copied entire folders instead of infinite lines and group actions or patches with ACTION_FOR_EACH and PATCH_FOR_EACH whenever possible.  *
 * ================================================================================================================================================= */

PRINT @207000 // ~Copying files...~
SILENT

COPY ~1pp/additions/obj_anim/gs~ ~override~


PRINT @207001 // ~Building BG1 animation compatibility...~
SILENT

ACTION_FOR_EACH category IN ~l~ ~m~ ~s~ BEGIN
	ACTION_FOR_EACH sequence IN ~a2~ ~a2e~ ~a4~ ~a4e~ ~a6~ ~a6e~ ~g1~ ~g1e~ ~w2~ ~w2e~ BEGIN
		COPY_EXISTING ~wp%category%qs%sequence%.bam~ ~override/wp%category%gs%sequence%.bam~
	END
END

ACTION_IF (is_bg2 OR is_tob OR is_tutu OR is_iwd) BEGIN // (GAME_IS ~totlm how bg2 tob tutu tutu_totsc ca~)

	PRINT @207002 // ~Installing paperdoll images...~
	SILENT

	ACTION_FOR_EACH paperdoll IN ~wplgsinv~ ~wpmgsinv~ ~wpngsinv~ ~wpsgsinv~ BEGIN
		COPY ~1pp/additions/obj_1pp/%paperdoll%.bam~ ~override~
	END

END
