/* ================================================================================================================================================================================== *
 *                                                                                                                                                                                    *
 *                                            C O M P O N E N T   :   A t t a c h a b l e   W i n g s   (1 p p   v 7)                                                                 *
 *                                                                                                                                                                                    *
 * ================================================================================================================================================================================== *
 *  This component adds equippable wings for elven characters (with some restrictions).                                                                                               *
 *  'Presented in Aerievision)                                                                                                                                                        *
 * ================================================================================================================================================================================== *
 *  change-log:                                                                                                                                                                       *
 *  -----------                                                                                                                                                                       *
 *      - Coding simplification:                                                                                                                                                      *
 *          Replaced `GAME_IS` conditions with variables checks to speed up install time.                                                                                             *
 *          Copy entire folders instead of infinite lines (COPY ~1pp/folder/file.ext~ ~override~ or ACTION_FOR_EACH file IN list BEGIN COPY ~1pp/folder/file.ext~ ~override~ END).    *
 * ================================================================================================================================================================================== */

PRINT @209000 // Copying...
SILENT

COPY ~1pp/additions/obj_anim/zw~ ~override~

ACTION_IF (is_bg2 OR is_tob OR is_tutu OR is_iwd) BEGIN // (GAME_IS ~totlm how bg2 tob tutu tutu_totsc ca~)
	COPY ~1pp/additions/obj_1pp/wpmzwinv.bam~ ~override~
END


PRINT @209001 // ~Installing test items...~
SILENT

COPY ~1pp/additions/1pp_awings/cwings01.bam~ ~override~
COPY ~1pp/additions/1pp_awings/gwings01.bam~ ~override~
COPY ~1pp/additions/1pp_awings/iwings01.bam~ ~override~
COPY ~1pp/additions/1pp_awings/wings01.itm~ ~override~
     ~1pp/additions/1pp_awings/wings01b.itm~ ~override~
	SAY NAME1 @209101 /* Wings */
	SAY NAME2 @209101
	SAY UNIDENTIFIED_DESC @209102
	SAY IDENTIFIED_DESC @209102


PRINT @209002 // ~Building crash protection for BG1 animations and non-elves...~
SILENT

ACTION_FOR_EACH set IN ~zw~ BEGIN
	ACTION_FOR_EACH category IN ~l~ ~n~ ~s~ BEGIN
		ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
			COPY ~1pp/additions/obj_anim/donotexist/empty%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
		END
	END
END

ACTION_FOR_EACH set IN ~zw~ BEGIN
	ACTION_FOR_EACH category IN ~l~ ~m~ ~s~ ~t~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a1e~ ~a2~ ~a2e~ ~a3~ ~a3e~ ~a4~ ~a4e~ ~a5~ ~a5e~ ~a6~ ~a6e~ ~ca~ ~cae~ ~g1~ ~g1e~ ~sa~ ~sae~ ~sx~ ~sxe~ ~w2~ ~w2e~ BEGIN
		 COPY ~1pp/additions/obj_anim/donotexist_bg1/empty%sequence%.bam~ ~override/wp%category%%set%%sequence%.bam~
		END
	END
END

// NOW SOMEONE WRITE A MOD THAT HAS AERIE LEAVE THE PARTY AS SOON AS PEOPLE TRY AND EQUIP SOME ON HER
// A WELL-WRITTEN ONE, WITH DIALOGUE!