/* ================================================================================================================================================================================ *
 *                                                                                                                                                                                  *
 *                                   C O M P O N E N T   :   C o r e   u p d a t e s   a n d   i t e m   p a t c h e s   ( n e w   s t a v e s )                                    *
 *                                                                                                                                                                                  *
 * ================================================================================================================================================================================ *
 *  This part installs vanilla staves stuff.                                                                                                                                        *
 * ================================================================================================================================================================================ *
 *  change-log:                                                                                                                                                                     *
 *  -----------                                                                                                                                                                     *
 *      - Replaced macros with functions whenever possible.                                                                                                                         *
 *      - Avoid copying and overwriting the same files again and again...                                                                                                           *
 *      - Coding simplification:                                                                                                                                                    *
 *  		Replaced WRITE_LONG 0x3E 0 and WRITE_ASCII 0x3A ~ISHLDS01~ with WRITE_ASCII 0x3A ~ISHLDS01~ #8. Id. with offsets 0x48 0x44, and 0x5C 0x58.                              *
 *          Rewrote tooltip.2da appending to make sure it contains at least 4 columns, so we can add all Narbucchad's Demise staves abilities.                                      *
 * ================================================================================================================================================================================ */

/* ============================ *
 *          NEW STAVES          *
 * ============================ */

PRINT @400056 // ~Installing new staves...~
SILENT

// Gwen fix: moved PSSTAFMxx items from automatic copy to avoid overwriting them.
ACTION_FOR_EACH resource IN ~1stafm0.bam~ ~1stafm0.spl~ ~1stafm0b.spl~ ~1stafm0c.spl~ ~1stafm0d.spl~ ~1stafm0e.spl~ ~1stafm1.bam~ ~1stafm1.spl~ ~1stafm2.bam~ BEGIN

	COPY ~1pp/item/1ppv4_update/item/%resource%~ ~override~

END


ADD_PROJECTILE ~1pp/item/1ppv4_update/item/1stafm1.pro~

// Narbucchad's Demise +5
COPY ~1pp/item/1ppv4_update/item/pstafm1.itm~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
		SAY NAME1 @400901
		SAY NAME2 @400902
		SAY UNIDENTIFIED_DESC @400903
		SAY DESC  @400904
		WRITE_SHORT 0x144 ~%1stafm1%~
	END
BUT_ONLY


ADD_PROJECTILE ~1pp/item/1ppv4_update/item/1stafm0.pro~

// Narbucchad's Demise +4
COPY ~1pp/item/1ppv4_update/item/pstafm0.itm~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
		SAY NAME1 @400901
		SAY NAME2 @400905
		SAY UNIDENTIFIED_DESC @400903
		SAY DESC  @400906
		WRITE_SHORT 0x144 ~%1stafm0%~
	END
BUT_ONLY

// Narbucchad's Demise +3
COPY ~1pp/item/1ppv4_update/item/pstafm0b.itm~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
		SAY NAME1 @400901
		SAY NAME2 @400907
		SAY UNIDENTIFIED_DESC @400903
		SAY DESC  @400908
		WRITE_SHORT 0x144 ~%1stafm0%~
	END
BUT_ONLY


ADD_PROJECTILE ~1pp/item/1ppv4_update/item/1stafm0c.pro~

// Narbucchad's Demise +2
COPY ~1pp/item/1ppv4_update/item/pstafm0c.itm~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
		SAY NAME1 @400901
		SAY NAME2 @400909
		SAY UNIDENTIFIED_DESC @400903
		SAY DESC  @400910
		WRITE_SHORT 0x144 ~%1stafm0c%~
	END
BUT_ONLY

// Narbucchad's Demise +1
COPY ~1pp/item/1ppv4_update/item/pstafm0d.itm~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
		SAY NAME1 @400901
		SAY NAME2 @400911
		SAY UNIDENTIFIED_DESC @400903
		SAY DESC  @400912
		WRITE_SHORT 0x144 ~%1stafm0c%~
	END
BUT_ONLY

// Narbucchad's Demise +1
COPY ~1pp/item/1ppv4_update/item/pstafm0e.itm~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
		SAY NAME1 @400901
		SAY NAME2 @400911
		SAY UNIDENTIFIED_DESC @400903
		SAY DESC  @400913
		WRITE_SHORT 0x144 ~%1stafm0c%~
	END
BUT_ONLY

// Narbucchad's Demise
COPY ~1pp/item/1ppv4_update/item/pstafm2.itm~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // protects against invalid files
		SAY NAME1 @400901
		SAY NAME2 @400914
		SAY UNIDENTIFIED_DESC @400915
		SAY DESC  @400916
	END
BUT_ONLY


/* --------------------- *
 *  Installing tooltips  *
 * --------------------- */

// Gwen fix: made sure that tooltip.2da contains at least 4 strref columns, so we can add Narbucchad's Demise ability.
// -------------------------------------------------------------------------------------------------------------------
LAM ~GW_ADJUST_COL_TOOLTIP~

// Reads how many columns are in tooltip.2da file.
// -----------------------------------------------
LAM ~GW_READ_COL_TOOLTIP~

LAF ~GW_ADD_ITEM_TOOLTIPS~ STR_VAR GW_objet = ~PSTAFM1~ GW_tooltips = ~@400917 @400918 @400919 @400914~ END		// Narbucchad's Demise +5 : Melee - Ranged, powered - Ranged, channelled - Narbucchad's Demise
LAF ~GW_ADD_ITEM_TOOLTIPS~ STR_VAR GW_objet = ~PSTAFM0~ GW_tooltips = ~@400917 @400918 @400919 @400914~ END		// Narbucchad's Demise +4 : Melee - Ranged, powered - Ranged, channelled - Narbucchad's Demise
LAF ~GW_ADD_ITEM_TOOLTIPS~ STR_VAR GW_objet = ~PSTAFM0B~ GW_tooltips = ~@400917 @400918 @400919 @400914~ END	// Narbucchad's Demise +3 : Melee - Ranged, powered - Ranged, channelled - Narbucchad's Demise
LAF ~GW_ADD_ITEM_TOOLTIPS~ STR_VAR GW_objet = ~PSTAFM0C~ GW_tooltips = ~@400917 @400918 @400919 @400914~ END	// Narbucchad's Demise +2 : Melee - Ranged, powered - Ranged, channelled - Narbucchad's Demise
LAF ~GW_ADD_ITEM_TOOLTIPS~ STR_VAR GW_objet = ~PSTAFM0D~ GW_tooltips = ~@400917 @400918 @400919 @400914~ END	// Narbucchad's Demise +1 : Melee - Ranged, powered - Ranged, channelled - Narbucchad's Demise
LAF ~GW_ADD_ITEM_TOOLTIPS~ STR_VAR GW_objet = ~PSTAFM0E~ GW_tooltips = ~@400917 @400920 @400914~ END			// Narbucchad's Demise +1 : Melee - Ranged - Narbucchad's Demise

// Pure cosmetic, but so cool!
// ---------------------------
COPY_EXISTING ~tooltip.2da~ ~override~
	PRETTY_PRINT_2DA
BUT_ONLY

//END of COMPONENT