/*  ==============================================================================================================================================================================  *
 *  change-log:                                                                                                                                                                     *
 *  -----------                                                                                                                                                                     *
 *      - Replace macros with functions whenever possible.                                                                                                                          *
 *      - Coding simplification:                                                                                                                                                    *
 *  		Replace WRITE_LONG 0x3E 0 and WRITE_ASCII 0x3A ~ISHLDS01~ with WRITE_ASCII 0x3A ~ISHLDS01~ #8. Id. with offsets 0x48 0x44, and 0x5C 0x58.                               *
 *  		Group actions or patches with ACTION_FOR_EACH and PATCH_FOR_EACH whenever possible.                                                                                     *
 *                                                                                                                                                                                  *
 *  specific fixes:                                                                                                                                                                 *
 *  ---------------                                                                                                                                                                 *
 *      - #809  ==> helm33.itm (Gold Horned Helm): fixes typo (was copying helm22 instead of helm33).                                                                               *
 *      - #2676 ==> Adds Lollorian's patch for Ashes of Embers compatibility.                                                                                                       *
 *  ==============================================================================================================================================================================  */

/*  =============================  *
 *          HELMETS BEGIN          *
 *  =============================  */

ACTION_IF (1pp_helmets_shadows = 2) BEGIN // shadow helmets

	ACTION_FOR_EACH resource IN ~WPLJ0INV~ ~WPLJ1INV~ ~WPLJ2INV~ ~WPLJ3INV~ ~WPLJ4INV~ ~WPLJ5INV~ ~WPLJ6INV~ ~WPLJ7INV~ ~WPLJ8INV~ ~WPLJ9INV~ ~WPLJAINV~ ~WPLJCINV~ ~WPMJ0INV~ ~WPMJ1INV~ ~WPMJ2INV~ ~WPMJ3INV~ ~WPMJ4INV~ ~WPMJ5INV~ ~WPMJ6INV~ ~WPMJ7INV~ ~WPMJ8INV~ ~WPMJ9INV~ ~WPMJAINV~ ~WPMJCINV~ ~WPNJ0INV~ ~WPNJ1INV~ ~WPNJ2INV~ ~WPNJ3INV~ ~WPNJ4INV~ ~WPNJ5INV~ ~WPNJ6INV~ ~WPNJ7INV~ ~WPNJ8INV~ ~WPNJ9INV~ ~WPNJAINV~ ~WPNJCINV~ ~WPSJ0INV~ ~WPSJ1INV~ ~WPSJ2INV~ ~WPSJ3INV~ ~WPSJ4INV~ ~WPSJ5INV~ ~WPSJ6INV~ ~WPSJ7INV~ ~WPSJ8INV~ ~WPSJ9INV~ ~WPSJAINV~ ~WPSJCINV~ BEGIN
		COPY ~1pp/additions/obj_1pp_h/%resource%.bam~ ~override~
	END

END

/* ------------------------------ *
 * updated Baldur's Gate II style *
 * ------------------------------ */
ACTION_IF (1pp_helmets_compatibility = 1) BEGIN

	PRINT @400015 /* Installing helmet compatibility... */

	ACTION_FOR_EACH set IN ~0~ ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J%set%%sequence%.BAM~ ~override/WQ%category%H%set%%sequence%.BAM~
			END
			COPY_EXISTING ~WP%category%J%set%INV.BAM~ ~override/WP%category%H%setINV.BAM~
		END
	END

/* DEPRECATED
	ACTION_FOR_EACH set IN ~H0~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J0%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H0~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J0%sequence%.BAM~ ~override/WP%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H1~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J1%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H1~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J1%sequence%.BAM~ ~override/WP%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H2~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J2%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H2~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J2%sequence%.BAM~ ~override/WP%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H3~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J3%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H3~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J3%sequence%.BAM~ ~override/WP%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H4~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J4%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H4~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J4%sequence%.BAM~ ~override/WP%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H5~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J5%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H5~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J5%sequence%.BAM~ ~override/WP%category%%set%%sequence%.BAM~
			END
		END
	END
*/
END // of ACTION_IF (1pp_helmets_compatibility = 1) = updated Baldur's Gate II style


/* ------------------------------ *
 * based on Baldur's Gate I style *
 * ------------------------------ */
ACTION_IF (1pp_helmets_compatibility = 2) BEGIN

	PRINT @400015 /* Installing helmet compatibility... */

	ACTION_FOR_EACH set IN ~H0~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J6%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H1~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J7%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H2~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J8%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H3~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J9%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H4~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J8%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H5~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%JA%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

END // of ACTION_IF (1pp_helmets_compatibility = 2) = based on Baldur's Gate I style


/* ------------------- *
 * 1ppv4 style HELMETS *
 * ------------------- */
ACTION_IF (1pp_helmets_appearance = 1) BEGIN

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm01.itm~) BEGIN
		COPY_EXISTING ~helm01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J6~			// Replace H0
				WRITE_ASCII 0x3A ~1HELM01~ #8	// Replace IHELM00
				WRITE_ASCII 0x58 ~CHELM01~ #8
				LPM ~clear~
				SET gradient = 14				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 28				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 202			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of Opposite Alignment
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm02.itm~) BEGIN
		COPY_EXISTING ~helm02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H3
				WRITE_ASCII 0x3A ~1HELM26~ #8	// Replace IHELM04
				WRITE_ASCII 0x58 ~CHELM04~ #8
				LPM ~clear~
				SET gradient = 14				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 21				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 21				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 90				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 21				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Noble +1
	ACTION_FOR_EACH helmet IN ~helm03~ ~palhelm~ BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%helmet%.itm~) BEGIN
			COPY_EXISTING ~%helmet%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
					WRITE_ASCII 0x22 ~J8~			// Replace H1
					WRITE_ASCII 0x3A ~1HELM07~ #8	// Replace IHELM02
					WRITE_ASCII 0x58 ~1CHELMX6~ #8	// Replace CHELM02
					LPM ~clear~
					SET gradient = 207				// Replace colour index 27
					SET location = hgrey			// location
					LPM ~colour~
					SET gradient = 21				// colour index
					SET location = hpink			// location
					LPM ~colour~
					SET gradient = 184				// Replace colour index 27
					SET location = hblue			// location
					LPM ~colour~
					SET gradient = 21				// Replace colour index 27
					SET location = hred				// location
					LPM ~colour~
					//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
					SET gradient = 223				// colour index
					SET location = hteal			// location
					LPM ~colour~
					//END
				END
			BUT_ONLY
		END
	END

	// The Eyes of Truth
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm05.itm~) BEGIN
		COPY_EXISTING ~helm05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM19~ #8	// Replace IHELM06
				WRITE_ASCII 0x58 ~1CHELM18~ #8	// Replace CHELM06
				LPM ~clear~
				SET gradient = 0				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 210				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 224				// Replace colour index 47
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 159				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Charm Protection
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm06.itm~) BEGIN
		COPY_EXISTING ~helm06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// Replace H2
				WRITE_ASCII 0x3A ~1HELM18~ #8	// Replace IHELM03
				WRITE_ASCII 0x58 ~1CHELM18~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 0				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 119				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 118				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Gift of Peace
	ACTION_FOR_EACH helmet IN ~helm04~ ~chalhelm~ BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%helmet%.itm~) BEGIN
			COPY_EXISTING ~%helmet%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
					WRITE_ASCII 0x22 ~J1~			// Replace H2
					WRITE_ASCII 0x3A ~1HELM21~ #8	// Replace IHELM03
					WRITE_ASCII 0x58 ~1CHELM21~ #8	// Replace CHELM03
					LPM ~clear~
					SET gradient = 21				// Replace colour index 27
					SET location = hgrey			// location
					LPM ~colour~
					SET gradient = 6				// colour index
					SET location = hpink			// location
					LPM ~colour~
					SET gradient = 142				// Replace colour index 27
					SET location = hblue			// location
					LPM ~colour~
					SET gradient = 0				// colour index
					SET location = hred				// location
					LPM ~colour~
					//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
					SET gradient = 0				// colour index
					SET location = hteal			// location
					LPM ~colour~
					//END
				END
			BUT_ONLY
		END
	END

	// Helm of Balduran
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm07.itm~) BEGIN
		COPY_EXISTING ~helm07.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// Replace H1
				WRITE_ASCII 0x58 ~CHELM07~ #8
				LPM ~clear~
				SET gradient = 98				// Replace colour index 42
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 114				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 241				// Replace colour index 99
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 241				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm08.itm~) BEGIN
		COPY_EXISTING ~helm08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// Replace H3
				WRITE_ASCII 0x3A ~1HELM05~ #8	// Replace IHELM04
				WRITE_ASCII 0x58 ~1CHELMX4~ #8	// Replace CHELM04
				LPM ~clear~
				SET gradient = 209				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 223			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm09.itm~) BEGIN
		COPY_EXISTING ~helm09.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// Replace H2
				WRITE_ASCII 0x3A ~1HELM17~ #8	// Replace IHELM03
				WRITE_ASCII 0x58 ~1CHELM17~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 223				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hteal			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// colour index
					SET location = hpink		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm10.itm~) BEGIN
		COPY_EXISTING ~helm10.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// Replace H4
				WRITE_ASCII 0x3A ~1HELM20~ #8	// Replace IHELM05
				WRITE_ASCII 0x58 ~1CHELM20~ #8	// Replace CHELM05
				LPM ~clear~
				SET gradient = 0				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 99				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 210			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm11.itm~) BEGIN
		COPY_EXISTING ~helm11.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J6~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM08~ #8	// Replace IHELM06
				WRITE_ASCII 0x58 ~1CHELM01~ #8	// Replace CHELM06
				LPM ~clear~
				SET gradient = 226				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 102				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 102				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 98			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 102			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm12.itm~) BEGIN
		COPY_EXISTING ~helm12.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// Replace H1
				WRITE_ASCII 0x3A ~1HELM02~ #8	// Replace IHELM02
				WRITE_ASCII 0x58 ~1CHELMX2~ #8	// Replace CHELM02
				LPM ~clear~
				SET gradient = 195				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 21				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 242				// Replace colour index 24
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 109			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm13.itm~) BEGIN
		COPY_EXISTING ~helm13.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J5~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM12~ #8	// Replace IHELM06
				WRITE_ASCII 0x58 ~CHELM05~ #8	// Replace CHELM06
				LPM ~clear~
				SET gradient = 210				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 102				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 248				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 0			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Kiel's Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm14.itm~) BEGIN
		COPY_EXISTING ~helm14.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// Replace H1
				WRITE_ASCII 0x3A ~1HELM22~ #8	// Replace IHELM14
				WRITE_ASCII 0x58 ~CHELM07~ #8
				LPM ~clear~
				SET gradient = 209				// Replace colour index 42
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 182				// Replace colour index 99
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// Replace colour index 98
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 21				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 225				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm15.itm~) BEGIN
		COPY_EXISTING ~helm15.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J0~			// Replace H4
				WRITE_ASCII 0x3A ~1HELM15~ #8	// Replace IHELM05
				WRITE_ASCII 0x58 ~1CHELM11~ #8	// Replace CHELM05
				LPM ~clear~
				SET gradient = 232				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 209				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 232			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of Brilliance
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm16.itm~) BEGIN
		COPY_EXISTING ~helm16.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J4~			// Replace H2
				WRITE_ASCII 0x3A ~1HELM16~ #8	// Replace IHELM03
				WRITE_ASCII 0x58 ~CHELM16~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 209				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 205				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 226				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Skull of Death
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm17.itm~) BEGIN
		COPY_EXISTING ~helm17.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H0
				LPM ~clear~
				SET gradient = 98				// Replace colour index 100
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 3				// Replace colour index 106
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 253				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Dragon Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm21.itm~) BEGIN
		COPY_EXISTING ~helm21.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// Replace H2
				LPM ~clear~
				SET gradient = 227				// Replace colour index 33
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 88				// Replace colour index 33
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 70				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 195				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm22.itm~) BEGIN
		COPY_EXISTING ~helm22.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// Replace H3
				WRITE_ASCII 0x3A ~1HELM03~ #8	// Replace IHELM04
				WRITE_ASCII 0x58 ~1CHELMX3~ #8	// Replace CHELM04
				LPM ~clear~
				SET gradient = 119				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 205				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 209				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 102				// colour index
				SET location = hteal			// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// colour index
					SET location = hpink		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm31.itm~) BEGIN
		COPY_EXISTING ~helm31.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// Replace H0
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// Replace PHELM31
				LPM ~clear~
				SET gradient = 66				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 183				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 183				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

-	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm32.itm~) BEGIN
		COPY_EXISTING ~helm32.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// Replace H1 (Gwen todo: check J3 in EE)
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// Replace PHELM32
				LPM ~clear~
				SET gradient = 207				// Replace colour index 27 (Gwen todo: check 233 in EE)
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 199				// Replace colour index 30 (Gwen todo: check 208 in EE)
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 199				// Replace colour index 27 (Gwen todo: check 208 in EE)
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Gold Horned Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm33.itm~) BEGIN
		COPY_EXISTING ~helm33.itm~ ~override~	// fix typo (was copying helm32 instead of helm33)
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H3 (not modified in EE)
				LPM ~clear~
				SET gradient = 223				// Replace colour index 42 (not modified in EE)
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 208				// Replace colour index 99 (not modified in EE)
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 208				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 0			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Roranach's Horn
	ACTION_IF (FILE_EXISTS_IN_GAME ~compon05.itm~) BEGIN
		COPY_EXISTING ~compon05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// Replace H3
				LPM ~clear~
				SET gradient = 225				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 250				// Replace colour index 51
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 47				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 210				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 250				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Vhailor's Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~wa2helm.itm~) BEGIN
		COPY_EXISTING ~wa2helm.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H0
				WRITE_ASCII 0x3A ~1HELM24~ #8	// Replace IHELM17
				WRITE_ASCII 0x58 ~CHELM04~ #8	// Replace CHELM17
				LPM ~clear~
				SET gradient = 223				// Replace colour index 100
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// Replace colour index 106
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

END	// of ACTION_IF (1pp_helmets_appearance = 1) = END of 1ppv4 style HELMETS


/* ------------ *
 * TUTU HELMETS *
 * ------------ */

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm01.itm~) BEGIN
	COPY_EXISTING ~_helm01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~H0~			// Replace H
			WRITE_ASCII 0x58 ~1CHELM01~ #8
			LPM MACRO ~clear~
			SET gradient = 223				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = hred				// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = hteal			// location
			LPM ~colour~
			//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
			SET gradient = 27				// colour index
			SET location = hpink			// location
			LPM ~colour~
			//END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm03.itm~) BEGIN
	COPY_EXISTING ~_helm03.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~H2~			// Replace H
			WRITE_ASCII 0x58 ~1CHELM03~ #8
			LPM ~clear~
			SET gradient = 224				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 90				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 30				// colour index
			SET location = hred				// location
			LPM ~colour~
			SET gradient = 30				// colour index
			SET location = hteal			// location
			LPM ~colour~
			//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
			SET gradient = 30				// colour index
			SET location = hpink			// location
			LPM ~colour~
			//END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm04.itm~) BEGIN
	COPY_EXISTING ~_helm04.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~H5~			// Replace H
			WRITE_ASCII 0x58 ~1CHELM04~ #8
			LPM ~clear~
			SET gradient = 0				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 202				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 0				// colour index
			SET location = hred				// location
			LPM ~colour~
			SET gradient = 5				// colour index
			SET location = hteal			// location
			LPM ~colour~
			//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
			SET gradient = 5				// colour index
			SET location = hpink			// location
			LPM ~colour~
			//END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm05.itm~) BEGIN
	COPY_EXISTING ~_helm05.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~JA~			// Replace H
			WRITE_ASCII 0x3A ~1HELM20~ #8
			WRITE_ASCII 0x58 ~1CHELM20~ #8
			LPM ~clear~
			SET gradient = 0				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 99				// colour index
			SET location = hred				// location
			LPM ~colour~
			//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
			SET gradient = 195				// colour index
			SET location = hpink			// location
			LPM ~colour~
			SET gradient = 210				// colour index
			SET location = hteal			// location
			LPM ~colour~
			//END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm06.itm~) BEGIN
	COPY_EXISTING ~_helm06.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~JA~
			WRITE_ASCII 0x3A ~1HELM18~ #8
			WRITE_ASCII 0x58 ~1CHELM18~ #8
			LPM ~clear~
			SET gradient = 0				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 119				// colour index
			SET location = hpink			// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 224				// colour index
			SET location = hred				// location
			LPM ~colour~
			//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
			SET gradient = 118				// colour index
			SET location = hteal			// location
			LPM ~colour~
			//END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm07.itm~) BEGIN
	COPY_EXISTING ~_helm07.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~J7~
			WRITE_ASCII 0x3A ~1HELM00~ #8
			WRITE_ASCII 0x58 ~CHELM07~ #8
			LPM ~clear~
			SET gradient = 223				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = hpink			// location
			LPM ~colour~
			SET gradient = 66				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 0				// colour index
			SET location = hred				// location
			LPM ~colour~
			//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
			SET gradient = 173				// colour index
			SET location = hteal			// location
			LPM ~colour~
			//END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm08.itm~) BEGIN
	COPY_EXISTING ~_helm08.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~JC~
			WRITE_ASCII 0x3A ~1HELM03~ #8
			WRITE_ASCII 0x58 ~1CHELMX3~ #8
			LPM ~clear~
			SET gradient = 119				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 205				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 209				// colour index
			SET location = hred				// location
			LPM ~colour~
			SET gradient = 102				// colour index
			SET location = hteal			// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 0			// colour index
				SET location = hpink		// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm09.itm~) BEGIN
	COPY_EXISTING ~_helm09.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~H3~
			//WRITE_ASCII 0x3A ~1HELM03~ #8
			WRITE_ASCII 0x58 ~1CHELM06~ #8
			LPM ~clear~
			SET gradient = 27				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 224				// colour index
			SET location = hred				// location
			LPM ~colour~
			SET gradient = 224				// colour index
			SET location = hteal			// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 195			// colour index
				SET location = hpink		// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm10.itm~) BEGIN
	COPY_EXISTING ~_helm10.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~H5~
			//WRITE_ASCII 0x3A ~1HELM03~ #8
			WRITE_ASCII 0x58 ~1CHELM05~ #8
			LPM ~clear~
			SET gradient = 27				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 224				// colour index
			SET location = hred				// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 47			// colour index
				SET location = hpink		// location
				LPM ~colour~
				SET gradient = 127			// colour index
				SET location = hteal		// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm11.itm~) BEGIN
	COPY_EXISTING ~_helm11.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~J8~
			WRITE_ASCII 0x3A ~1HELM04~ #8
			WRITE_ASCII 0x58 ~1CHELMX4~ #8
			LPM ~clear~
			SET gradient = 248				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 232				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 0				// colour index
			SET location = hred				// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 202			// colour index
				SET location = hpink		// location
				LPM ~colour~
				SET gradient = 202			// colour index
				SET location = hteal		// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm12.itm~) BEGIN
	COPY_EXISTING ~_helm12.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~JC~
			WRITE_ASCII 0x3A ~IHELM04~ #8
			WRITE_ASCII 0x58 ~1CHELM02~ #8
			LPM ~clear~
			SET gradient = 235				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 232				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 102				// colour index
			SET location = hred				// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 232			// colour index
				SET location = hpink		// location
				LPM ~colour~
				SET gradient = 232			// colour index
				SET location = hteal		// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm13.itm~) BEGIN
	COPY_EXISTING ~_helm13.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~J9~
			WRITE_ASCII 0x3A ~1HELM17~ #8
			WRITE_ASCII 0x58 ~1CHELM17~ #8
			LPM ~clear~
			SET gradient = 223				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = hteal			// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 224				// colour index
			SET location = hred				// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 195			// colour index
				SET location = hpink		// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm14.itm~) BEGIN
	COPY_EXISTING ~_helm14.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~J7~
			WRITE_ASCII 0x58 ~CHELM07~ #8
			LPM ~clear~
			SET gradient = 98				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 114				// colour index
			SET location = hpink			// location
			LPM ~colour~
			SET gradient = 241				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 0				// colour index
			SET location = hred				// location
			LPM ~colour~
			//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
			SET gradient = 241				// colour index
			SET location = hteal			// location
			LPM ~colour~
			//END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_helm15.itm~) BEGIN
	COPY_EXISTING ~_helm15.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~J9~
			WRITE_ASCII 0x3A ~1HELM09~ #8
			WRITE_ASCII 0x58 ~1CHELMX9~ #8
			LPM ~clear~
			SET gradient = 226				// colour index
			SET location = hgrey			// location
			LPM ~colour~
			SET gradient = 232				// colour index
			SET location = hteal			// location
			LPM ~colour~
			SET gradient = 232				// colour index
			SET location = hblue			// location
			LPM ~colour~
			SET gradient = 102				// colour index
			SET location = hred				// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 208			// colour index
				SET location = hpink		// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

//END OF TUTU


/* ---------------------- *
 * faux BG1 style HELMETS *
 * ---------------------- */
ACTION_IF (1pp_helmets_appearance = 2) BEGIN

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm01.itm~) BEGIN
		COPY_EXISTING ~helm01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H0~			// Replace H0
				WRITE_ASCII 0x58 ~1CHELM01~ #8	// Replace CHELM01
				LPM ~clear~
				SET gradient = 223				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 27				// colour index
				SET location = hpink			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Opposite Alignment
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm02.itm~) BEGIN
		COPY_EXISTING ~helm02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// Replace H3
				WRITE_ASCII 0x3A ~1HELM06~ #8	// Replace IHELM04
				WRITE_ASCII 0x58 ~1CHELMX6~ #8	// Replace CHELM04
				LPM ~clear~
				SET gradient = 249				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Noble +1
	ACTION_FOR_EACH helmet IN ~helm03~ ~palhelm~ BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%helmet%.itm~) BEGIN
			COPY_EXISTING ~%helmet%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
					WRITE_ASCII 0x22 ~H2~			// Replace H1
					//WRITE_ASCII 0x3A ~1HELM06~ #8
					WRITE_ASCII 0x58 ~1CHELM03~ #8	// Replace CHELM02
					LPM ~clear~
					SET gradient = 224				// Replace colour index 27
					SET location = hgrey			// location
					LPM ~colour~
					SET gradient = 90				// Replace colour index 27
					SET location = hblue			// location
					LPM ~colour~
					SET gradient = 30				// Replace colour index 27
					SET location = hred				// location
					LPM ~colour~
					SET gradient = 30				// colour index
					SET location = hteal			// location
					LPM ~colour~
					//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
					SET gradient = 30				// colour index
					SET location = hpink			// location
					LPM ~colour~
					//END
				END
			BUT_ONLY
		END
	END

	// Gift of Peace
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm04.itm~) BEGIN
		COPY_EXISTING ~helm04.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H5~			// Replace H2
				//WRITE_ASCII 0x3A ~1HELM06~ #8
				WRITE_ASCII 0x58 ~1CHELM04~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 0				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 5				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 5				// colour index
				SET location = hpink			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// The Eyes of Truth
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm05.itm~) BEGIN
		COPY_EXISTING ~helm05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM20~ #8	// Replace IHELM06
				WRITE_ASCII 0x58 ~1CHELM20~ #8	// Replace CHELM06
				LPM ~clear~
				SET gradient = 0				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 99				// Replace colour index 47
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 210				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Charm Protection
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm06.itm~) BEGIN
		COPY_EXISTING ~helm06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// Replace H2
				WRITE_ASCII 0x3A ~1HELM18~ #8	// Replace IHELM03
				WRITE_ASCII 0x58 ~1CHELM18~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 0				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 119				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 118				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Balduran
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm07.itm~) BEGIN
		COPY_EXISTING ~helm07.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// Replace H1
				WRITE_ASCII 0x3A ~1HELM00~ #8	// Replace IHELM14
				WRITE_ASCII 0x58 ~CHELM07~ #8	// Replace CHELM07
				LPM ~clear~
				SET gradient = 223				// Replace colour index 42
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 66				// Replace colour index 99
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 173				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm08.itm~) BEGIN
		COPY_EXISTING ~helm08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// Replace H3
				WRITE_ASCII 0x3A ~1HELM03~ #8	// Replace IHELM04
				WRITE_ASCII 0x58 ~1CHELMX3~ #8	// Replace CHELM04
				LPM ~clear~
				SET gradient = 119				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 205				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 209				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 102				// colour index
				SET location = hteal			// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// colour index
					SET location = hpink		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm09.itm~) BEGIN
		COPY_EXISTING ~helm09.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H3~			// Replace H2
				//WRITE_ASCII 0x3A ~1HELM03~ #8
				WRITE_ASCII 0x58 ~1CHELM06~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 27				// colour index
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hteal			// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// colour index
					SET location = hpink		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm10.itm~) BEGIN
		COPY_EXISTING ~helm10.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H5~			// Replace H4
				//WRITE_ASCII 0x3A ~1HELM03~ #8
				WRITE_ASCII 0x58 ~1CHELM05~ #8	// Replace CHELM05
				LPM ~clear~
				SET gradient = 27				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 47			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 127			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm11.itm~) BEGIN
		COPY_EXISTING ~helm11.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM04~ #8	// Replace IHELM06
				WRITE_ASCII 0x58 ~1CHELMX4~ #8	// Replace CHELM06
				LPM ~clear~
				SET gradient = 248				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 202			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 202			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm12.itm~) BEGIN
		COPY_EXISTING ~helm12.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// Replace H1
				WRITE_ASCII 0x3A ~IHELM04~ #8	// Replace IHELM02
				WRITE_ASCII 0x58 ~1CHELM02~ #8	// Replace CHELM02
				LPM ~clear~
				SET gradient = 235				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 102				// Replace colour index 24
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 232			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 232			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm13.itm~) BEGIN
		COPY_EXISTING ~helm13.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM17~ #8	// Replace IHELM06
				WRITE_ASCII 0x58 ~1CHELM17~ #8	// Replace CHELM6
				LPM ~clear~
				SET gradient = 223				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hteal			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// colour index
					SET location = hpink		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Kiel's Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm14.itm~) BEGIN
		COPY_EXISTING ~helm14.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// Replace H1
				WRITE_ASCII 0x58 ~CHELM07~ #8	// Replace CHELM07
				LPM ~clear~
				SET gradient = 98				// Replace colour index 42
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 114				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 241				// Replace colour index 99
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// Replace colour index 98
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 241				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm15.itm~) BEGIN
		COPY_EXISTING ~helm15.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// Replace H4
				WRITE_ASCII 0x3A ~1HELM09~ #8	// Replace IHELM05
				WRITE_ASCII 0x58 ~1CHELMX9~ #8	// Replace CHELM05
				LPM ~clear~
				SET gradient = 226				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 232				// colour index
				SET location = hteal			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 102				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 208			// colour index
					SET location = hpink		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of Brilliance
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm16.itm~) BEGIN
		COPY_EXISTING ~helm16.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// Replace H2
				WRITE_ASCII 0x3A ~1HELM02~ #8	// Replace IHELM03
				WRITE_ASCII 0x58 ~1CHELMX2~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 195				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 21				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 242				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 109				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Skull of Death
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm17.itm~) BEGIN
		COPY_EXISTING ~helm17.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H0
				LPM ~clear~
				SET gradient = 98				// Replace colour index 100
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 3				// Replace colour index 106
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 253				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Dragon Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm21.itm~) BEGIN
		COPY_EXISTING ~helm21.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// Replace H2
				LPM ~clear~
				SET gradient = 227				// Replace colour index 33
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 88				// Replace colour index 33
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 70				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 195				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm22.itm~) BEGIN
		COPY_EXISTING ~helm22.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H0~			// Replace H3
				WRITE_ASCII 0x3A ~1HELM08~ #8	// Replace IHELM04
				WRITE_ASCII 0x58 ~1CHELM01~ #8	// Replace CHELM04
				LPM ~clear~
				SET gradient = 226				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 27				// colour index
				SET location = hpink			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm31.itm~) BEGIN
		COPY_EXISTING ~helm31.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// Replace H0
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// Replace PHELM31
				LPM ~clear~
				SET gradient = 66				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 183				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 183				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm32.itm~) BEGIN
		COPY_EXISTING ~helm32.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// Replace H1
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// Replace PHELM32
				LPM ~clear~
				SET gradient = 207				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 199				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 199				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Gold Horned Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm33.itm~) BEGIN
		COPY_EXISTING ~helm33.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// Replace H3
				LPM ~clear~
				SET gradient = 225				// Replace colour index 42
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 250				// Replace colour index 99
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 47				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 210				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 250				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END


	// Roranach's Horn
	ACTION_IF (FILE_EXISTS_IN_GAME ~compon05.itm~) BEGIN
		COPY_EXISTING ~compon05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// Replace H3
				LPM ~clear~
				SET gradient = 225				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 250				// Replace colour index 51
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 47				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 210				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 250				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Vhailor's Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~wa2helm.itm~) BEGIN
		COPY_EXISTING ~wa2helm.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H0
				WRITE_ASCII 0x3A ~1HELM24~ #8	// Replace IHELM17
				WRITE_ASCII 0x58 ~CHELM04~ #8	// Replace CHELM17
				LPM ~clear~
				SET gradient = 223				// Replace colour index 100
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// Replace colour index 106
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

END	// of ACTION_IF (1pp_helmets_appearance = 2) = faux BG1 style HELMETS


/* ----------------- *
 * BG2 style HELMETS *
 * ----------------- */
ACTION_IF (1pp_helmets_appearance = 3) BEGIN

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm01.itm~) BEGIN
		COPY_EXISTING ~helm01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J6~			// Replace H0
				WRITE_ASCII 0x3A ~1HELM01~ #8	// Replace IHELM00
				WRITE_ASCII 0x58 ~CHELM01~ #8
				LPM ~clear~
				SET gradient = 14				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 28				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 202			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of Opposite Alignment
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm02.itm~) BEGIN
		COPY_EXISTING ~helm02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// Replace H3
				WRITE_ASCII 0x3A ~1HELM02~ #8	// Replace IHELM04
				WRITE_ASCII 0x58 ~1CHELMX2~ #8	// Replace CHELM04
				LPM ~clear~
				SET gradient = 195				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 21				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 242				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 109				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Noble +1
	ACTION_FOR_EACH helmet IN ~helm03~ ~palhelm~ BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%helmet%.itm~) BEGIN
			COPY_EXISTING ~%helmet%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
					WRITE_ASCII 0x22 ~J1~			// Replace H1
					WRITE_ASCII 0x3A ~1HELM21~ #8	// Replace IHELM02
					WRITE_ASCII 0x58 ~1CHELM21~ #8	// Replace CHELM02
					LPM ~clear~
					SET gradient = 21				// Replace colour index 27
					SET location = hgrey			// location
					LPM ~colour~
					SET gradient = 6				// colour index
					SET location = hpink			// location
					LPM ~colour~
					SET gradient = 142				// Replace colour index 27
					SET location = hblue			// location
					LPM ~colour~
					SET gradient = 0				// Replace colour index 27
					SET location = hred				// location
					LPM ~colour~
					//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
					SET gradient = 0				// colour index
					SET location = hteal			// location
					LPM ~colour~
					//END
				END
			BUT_ONLY
		END
	END

	// Gift of Peace
	ACTION_FOR_EACH helmet IN ~helm04~ ~chalhelm~ BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%helmet%.itm~) BEGIN
			COPY_EXISTING ~%helmet%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
					WRITE_ASCII 0x22 ~J4~			// Replace H2
					WRITE_ASCII 0x3A ~1HELM10~ #8	// Replace IHELM03
					WRITE_ASCII 0x58 ~CHELM06~ #8	// Replace CHELM03
					LPM ~clear~
					SET gradient = 223				// Replace colour index 27
					SET location = hgrey			// location
					LPM ~colour~
					SET gradient = 195				// colour index
					SET location = hpink			// location
					LPM ~colour~
					SET gradient = 192				// Replace colour index 27
					SET location = hblue			// location
					LPM ~colour~
					SET gradient = 209				// colour index
					SET location = hred				// location
					LPM ~colour~
					//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
					SET gradient = 200				// colour index
					SET location = hteal			// location
					LPM ~colour~
					//END
				END
			BUT_ONLY
		END
	END

	// The Eyes of Truth
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm05.itm~) BEGIN
		COPY_EXISTING ~helm05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J4~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM16~ #8	// Replace IHELM06
				WRITE_ASCII 0x58 ~CHELM16~ #8	// Replace CHELM06
				LPM ~clear~
				SET gradient = 209				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 205				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 226				// Replace colour index 47
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Charm Protection
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm06.itm~) BEGIN
		COPY_EXISTING ~helm06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J5~			// Replace H2
				WRITE_ASCII 0x3A ~1HELM12~ #8	// Replace IHELM03
				WRITE_ASCII 0x58 ~CHELM05~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 210				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 102				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 248				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 0			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of Balduran
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm07.itm~) BEGIN
		COPY_EXISTING ~helm07.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// Replace H1
				WRITE_ASCII 0x58 ~CHELM07~ #8	// Replace CHELM07
				LPM ~clear~
				SET gradient = 98				// Replace colour index 42
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 114				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 241				// Replace colour index 99
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 241				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm08.itm~) BEGIN
		COPY_EXISTING ~helm08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H3
				WRITE_ASCII 0x3A ~1HELM23~ #8	// Replace IHELM04
				WRITE_ASCII 0x58 ~CHELM04~ #8	// Replace CHELM04
				LPM ~clear~
				SET gradient = 226				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 202				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm09.itm~) BEGIN
		COPY_EXISTING ~helm09.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J6~			// Replace H2
				WRITE_ASCII 0x3A ~1HELM08~ #8	// Replace IHELM03
				WRITE_ASCII 0x58 ~1CHELM01~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 226				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 102				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 102				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 98			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 102			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm10.itm~) BEGIN
		COPY_EXISTING ~helm10.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J0~			// Replace H4
				WRITE_ASCII 0x3A ~1HELM14~ #8	// Replace IHELM05
				WRITE_ASCII 0x58 ~1CHELM11~ #8	// Replace CHELM05
				LPM ~clear~
				SET gradient = 98				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 91				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 98			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 232			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm11.itm~) BEGIN
		COPY_EXISTING ~helm11.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J5~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM12~ #8	// Replace IHELM06
				WRITE_ASCII 0x58 ~CHELM05~ #8	// Replace CHELM06
				LPM ~clear~
				SET gradient = 210				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 249				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 91				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 0			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm12.itm~) BEGIN
		COPY_EXISTING ~helm12.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J0~			// Replace H1
				WRITE_ASCII 0x3A ~1HELM11~ #8	// Replace IHELM02
				WRITE_ASCII 0x58 ~1CHELM11~ #8	// Replace CHELM02
				LPM ~clear~
				SET gradient = 21				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 27				// Replace colour index 24
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 27			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 200			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm13.itm~) BEGIN
		COPY_EXISTING ~helm13.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J0~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM15~ #8	// Replace IHELM06
				WRITE_ASCII 0x58 ~1CHELM11~ #8	// Replace CHELM06
				LPM ~clear~
				SET gradient = 232				// Replace colour index 47
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 232				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 98			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 232			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Kiel's Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm14.itm~) BEGIN
		COPY_EXISTING ~helm14.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// Replace H1
				WRITE_ASCII 0x3A ~1HELM22~ #8	// Replace IHELM14
				WRITE_ASCII 0x58 ~CHELM07~ #8
				LPM ~clear~
				SET gradient = 209				// Replace colour index 42
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 182				// Replace colour index 99
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// Replace colour index 98
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 21				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 225				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm15.itm~) BEGIN
		COPY_EXISTING ~helm15.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H4
				WRITE_ASCII 0x3A ~1HELM25~ #8	// Replace IHELM05
				WRITE_ASCII 0x58 ~CHELM04~ #8	// Replace CHELM05
				LPM ~clear~
				SET gradient = 226				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Brilliance
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm16.itm~) BEGIN
		COPY_EXISTING ~helm16.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J4~			// Replace H2
				WRITE_ASCII 0x3A ~1HELM16~ #8	// Replace IHELM03
				WRITE_ASCII 0x58 ~CHELM16~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 209				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 205				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 226				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Skull of Death
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm17.itm~) BEGIN
		COPY_EXISTING ~helm17.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H0
				LPM ~clear~
				SET gradient = 98				// Replace colour index 100
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 3				// Replace colour index 106
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 253				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Dragon Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm21.itm~) BEGIN
		COPY_EXISTING ~helm21.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// Replace H2
				LPM ~clear~
				SET gradient = 227				// Replace colour index 33
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 88				// Replace colour index 33
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 70				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 195				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm22.itm~) BEGIN
		COPY_EXISTING ~helm22.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// Replace H3
				WRITE_ASCII 0x3A ~1HELM05~ #8	// Replace IHELM04
				WRITE_ASCII 0x58 ~1CHELMX4~ #8	// Replace CHELM04
				LPM ~clear~
				SET gradient = 209				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 223			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm31.itm~) BEGIN
		COPY_EXISTING ~helm31.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H0
				WRITE_ASCII 0x3A ~1HELM25~ #8	// Replace IHELM31
				WRITE_ASCII 0x58 ~CHELM04~ #8	// Replace PHELM31
				LPM ~clear~
				SET gradient = 226				// Replace colour index 30
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm32.itm~) BEGIN
		COPY_EXISTING ~helm32.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H1
				WRITE_ASCII 0x3A ~1HELM26~ #8	// Replace IHELM32
				WRITE_ASCII 0x58 ~CHELM04~ #8	// Replace PHELM32
				LPM ~clear~
				SET gradient = 226				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 207				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 228				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Gold Horned Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm33.itm~) BEGIN
		COPY_EXISTING ~helm33.itm~ ~override~	// fix typo (was copying helm32 instead of helm33)
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H0
				LPM ~clear~
				SET gradient = 223				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 208				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 208				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 0			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Roranach's Horn
	ACTION_IF (FILE_EXISTS_IN_GAME ~compon05.itm~) BEGIN
		COPY_EXISTING ~compon05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H3
				LPM ~clear~
				SET gradient = 223				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 208				// Replace colour index 51
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 208				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 0			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Vhailor's Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~wa2helm.itm~) BEGIN
		COPY_EXISTING ~wa2helm.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H0
				WRITE_ASCII 0x3A ~1HELM24~ #8	// Replace IHELM17
				WRITE_ASCII 0x58 ~CHELM04~ #8	// Replace CHELM17
				LPM ~clear~
				SET gradient = 223				// Replace colour index 100
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// Replace colour index 106
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

END	// of ACTION_IF (1pp_helmets_appearance = 3) = BG2 style HELMETS



/* ================================================================================================================================================================================ *
 *                                                               ADD CIRCLETS                                                                                                       *
 * ================================================================================================================================================================================ *
 *  change-log:                                                                                                                                                                     *
 *  -----------                                                                                                                                                                     *
 *      - Lollorian's BWP Fixpack patch for Ashes of Embers compatibility (400_1pp_update_bgii.tph.patch): Renames 1PPv4 BAND0X.ITMs to XOBAND0X.ITMs, using Lollorian's prefix     *
 *        (according to BWL: XO, submitted by Chaplain, 11.03.2010, Prefix owner also known as Lollorian).                                                                          *
 *        Source: http://www.shsforums.net/topic/56643-1pp-circlets-and-bg2tweaks-issue/?p=561849                                                                                   *
 *                                                                                                                                                                                  *
 *  Fix wrong coding:                                                                                                                                                               *
 *  -----------------                                                                                                                                                               *
 *  - #2715 ==> xoband02.itm (Silver Circlet). Opcodes #33, 34 & 35: parameter2 originally set to 1 should be 0, adds #36 & 37 to match item description = +1 to saving throws.     *
 *  - #2770 ==> xoband03.itm (Eilistraee's Boon +1). Same fix for Opcodes #33, 34, 35, 36 & 37.                                                                                     *
 *  			Opcode #31: parameter1 originally set to 110 should be 10, and parameter2 switched from 2 to 0 to match item description (+10% magic damage resistance).            *
 *  - #2808 ==> xoband04.itm (Circlet of the Archmagi). Same fix for Opcodes #33, 34, 35, 36 & 37. Adds one missing equipped effects (LPM ADD_ITEM_EQEFFECT #19).                   *
 * ================================================================================================================================================================================ */

// Silver Circlet
ACTION_IF (FILE_EXISTS_IN_GAME ~amul02.itm~) BEGIN
	COPY_EXISTING ~amul02.itm~ ~override/xoband02.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME1 @400601 /* Circlet */
			SAY NAME2 @400602 /* Silver Circlet */
			SAY UNIDENTIFIED_DESC @400603 /* A circlet is a circular band, typically made of precious metal, worn on the head as an ornament or symbol of status. Circlets carrying low-level enchantments are commonly worn by mages across Faerun. */
			SAY DESC  @400604 /* A circlet is a circular band, typically made of precious metal, worn on the head as an ornament or symbol of status. This silver circlet is enchanted to bring the wearer luck in battle, slightly improving the chance of successful saving throws.

STATISTICS:

Special: +1 to saving throws
Weight: 1 */
			WRITE_ASCII 0x22 ~JB~
			WRITE_ASCII 0x3A ~1BAND01~ #8
			WRITE_ASCII 0x58 ~1CBAND01~ #8
			WRITE_LONG	0x18 0x6c			// Flags : Droppable - Displayable - Not copyable - Magical
			WRITE_SHORT 0x1c 0x07			// Category
			WRITE_LONG  0x34 920			// Price
			WRITE_SHORT 0x38 1				// Gwen fix: Stack (for safety!)
			WRITE_SHORT 0x42 40				// Lore to identify
			LPM ~clear~
			SET gradient = 27				// colour index
			SET location = hred				// location
			LPM ~colour~
			// Gwen wrong coding fixed: parameter2 originaly set to 1 should be 0 to match item description (+1 to saving throws).
			PATCH_FOR_EACH op IN 33 34 35 36 37 BEGIN
				LPF ADD_ITEM_EQEFFECT INT_VAR opcode = op target = 1 timing = 2 parameter1 = 1 END
			END
		END
	BUT_ONLY
END

// Circlet
ACTION_IF (FILE_EXISTS_IN_GAME ~amul02.itm~) BEGIN
	COPY_EXISTING ~amul02.itm~ ~override/xoband01.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400601 /* Circlet */
			SAY DESC  @400603 /* A circlet is a circular band, typically made of precious metal, worn on the head as an ornament or symbol of status. Circlets carrying low-level enchantments are commonly worn by mages across Faerun. */
			WRITE_ASCII 0x22 ~JB~
			WRITE_ASCII 0x3A ~1BAND02~ #8
			WRITE_ASCII 0x58 ~1CBAND01~ #8
			WRITE_SHORT 0x1c 0x07			// Category
			WRITE_LONG  0x34 12				// Price
			WRITE_SHORT 0x38 1				// Gwen fix: Stack (for safety!)
			LPM ~clear~
			SET gradient = 98				// colour index
			SET location = hred				// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Eilistraee's Boon +1
ACTION_IF (FILE_EXISTS_IN_GAME ~amul02.itm~) BEGIN
	COPY_EXISTING ~amul02.itm~ ~override/xoband03.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME1 @400601 /* Circlet */
			SAY NAME2 @400605 /* Eilistraee's Boon +1 */
			SAY UNIDENTIFIED_DESC @400603
			SAY DESC  @400606 /* This circlet is made of the purest silver, and embedded with a green and shimmering jewel that seems to emit a faint glow when caught by moonlight. It was blessed by the Drow goddess Eilistraee, granting the wearer increased protection against harmful magic.

STATISTICS:

Special:
+1 to saving throws
+10% resistance to magic damage
Weight: 1 */
			WRITE_ASCII 0x22 ~JB~
			WRITE_ASCII 0x3A ~1BAND03~ #8
			WRITE_ASCII 0x58 ~1CBAND03~ #8
			WRITE_LONG	0x18 0x6c			// Flags : Droppable - Displayable - Not copyable - Magical
			WRITE_SHORT 0x1c 0x07			// Category
			WRITE_LONG  0x34 2100			// Price
			WRITE_SHORT 0x38 1				// Gwen fix: Stack (for safety!)
			WRITE_SHORT 0x42 85				// Lore to identify
			LPM ~clear~
			SET gradient = 245				// colour index
			SET location = hred				// location
			LPM ~colour~
			// Gwen wrong coding fixed: parameter1 originaly set to 110 should be 10, and parameter2 switched from 2 to 0 to match item description (+10% magic damage resistance).
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 31 target = 1 timing = 2 parameter1 = 10 END
			PATCH_FOR_EACH op IN 33 34 35 36 37 BEGIN // wrong coding: +1 to saving throws (parameter2 originaly set to 1 should be 0).
				LPF ADD_ITEM_EQEFFECT INT_VAR opcode = op target = 1 timing = 2 parameter1 = 1 END
			END
		END
	BUT_ONLY
END

// Circlet of the Archmagi
ACTION_IF (FILE_EXISTS_IN_GAME ~amul02.itm~) BEGIN
	COPY_EXISTING ~amul02.itm~ ~override/xoband04.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME1 @400601 /* Circlet */
			SAY NAME2 @400607 /* Circlet of the Archmagi */
			SAY UNIDENTIFIED_DESC @400603
			SAY DESC  @400608 /* This powerful circlet was enchanted to complement the robes customarily worn by arch mages, building even further on their magical protection and benefits. Due to the nature of the enchantment, it can only be worn by mages.

STATISTICS:

Special:
+1 to saving throws
+1 to intelligence
+1 to armour class
Weight: 1 */
			WRITE_ASCII 0x22 ~JB~
			WRITE_ASCII 0x3A ~1BAND04~ #8
			WRITE_ASCII 0x58 ~1CBAND04~ #8
			WRITE_LONG	0x18 0x6c			// Flags : Droppable - Displayable - Not copyable - Magical
			WRITE_SHORT 0x1c 0x07			// Category
			WRITE_LONG  0x1e 0x60725ec0		// Usability
			WRITE_LONG  0x34 5100			// Price
			WRITE_SHORT 0x38 1				// Gwen fix: Stack (for safety!)
			WRITE_SHORT 0x42 85				// Lore to identify
			LPM ~clear~
			SET gradient = 228				// colour index
			SET location = hred				// location
			LPM ~colour~
			// Gwen wrong coding fixed: one LPM ADD_ITEM_EQEFFECT was missing.
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 19 target = 10 timing = 2 parameter1 = 1 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 1 END
			// Gwen wrong coding fixed: parameter2 originaly set to 1 should be 0 to match item description (+1 to saving throws).
			PATCH_FOR_EACH op IN 33 34 35 36 37 BEGIN
				LPF ADD_ITEM_EQEFFECT INT_VAR opcode = op target = 1 timing = 2 parameter1 = 1 END
			END
		END
	BUT_ONLY
END

// Circlet of Netheril
ACTION_IF (FILE_EXISTS_IN_GAME ~compon17.itm~) BEGIN
	COPY_EXISTING ~compon17.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~JB~			// Replace None
			WRITE_ASCII 0x3A ~1BAND05~ #8	// Replace ICOMPO17
			WRITE_ASCII 0x58 ~1CBAND05~ #8	// Replace PCOMPO17
			WRITE_SHORT 0x38 1				// Gwen fix: Stack (for safety!)
			LPM ~clear~
			SET gradient = 208				// colour index
			SET location = hred				// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Circlet of Netheril
ACTION_IF (FILE_EXISTS_IN_GAME ~helm28.itm~) BEGIN
	COPY_EXISTING ~helm28.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~JB~			// Replace None
			WRITE_ASCII 0x3A ~1BAND06~ #8	// Replace ICOMPO17
			WRITE_ASCII 0x58 ~1CBAND06~ #8	// Replace PCOMPO17
			WRITE_SHORT 0x38 1				// Gwen fix: Stack (for safety!)
			LPM ~clear~
			SET gradient = 227				// colour index
			SET location = hred				// location
			LPM ~colour~
		END
	BUT_ONLY
END

//END of COMPONENT