/* ================================================================================================================================================================================ *
 *  v 4.2.0                                                                                                                                                                         *
 *                                      C O M P O N E N T   :   C o r e   u p d a t e s   a n d   i t e m   p a t c h e s   ( h e l m e t s )                                       *
 *                                                                                                                                                                                  *
 * ================================================================================================================================================================================ *
 *  This part installs helmets stuff.                                                                                                                                               *
 * ================================================================================================================================================================================ *
 *  change-log:                                                                                                                                                                     *
 *  -----------                                                                                                                                                                     *
 *      - Replaced macros with functions whenever possible.                                                                                                                         *
 *      - Coding simplification:                                                                                                                                                    *
 *  		Replaced WRITE_LONG 0x3E 0 and WRITE_ASCII 0x3A ~ISHLDS01~ with WRITE_ASCII 0x3A ~ISHLDS01~ #8. Id. with offsets 0x48 0x44, and 0x5C 0x58.                              *
 *  		Grouped actions or patches with ACTION_FOR_EACH and PATCH_FOR_EACH whenever possible.                                                                                   *
 *          Used new 1pp_compatibility.tph library to improve 1PP crossmods compatibility (Stuff of the Magi).                                                                      *
 *                                                                                                                                                                                  *
 *  specific fixes:                                                                                                                                                                 *
 *  ---------------                                                                                                                                                                 *
 *      - #826  ==> helm33.itm (Gold Horned Helm): fixed a typo (was patching helm22 instead of helm33). Id. #2610.                                                                 *
 *      - #2713 ==> Circlets: Added Lollorian's patch for Ashes of Embers compatibility.                                                                                            *
 * ================================================================================================================================================================================ */

/* =============================== *
 *          HELMETS BEGIN          *
 * =============================== */

ACTION_IF (1pp_helmets_shadows = 2) BEGIN // shadow helmets on paperdolls (1 = No - 2 = Yes [Default])

	ACTION_FOR_EACH resource IN ~wplj0inv~ ~wplj1inv~ ~wplj2inv~ ~wplj3inv~ ~wplj4inv~ ~wplj5inv~ ~wplj6inv~ ~wplj7inv~ ~wplj8inv~ ~wplj9inv~ ~wpljainv~ ~wpljcinv~ ~wpmj0inv~ ~wpmj1inv~ ~wpmj2inv~ ~wpmj3inv~ ~wpmj4inv~ ~wpmj5inv~ ~wpmj6inv~ ~wpmj7inv~ ~wpmj8inv~ ~wpmj9inv~ ~wpmjainv~ ~wpmjcinv~ ~wpnj0inv~ ~wpnj1inv~ ~wpnj2inv~ ~wpnj3inv~ ~wpnj4inv~ ~wpnj5inv~ ~wpnj6inv~ ~wpnj7inv~ ~wpnj8inv~ ~wpnj9inv~ ~wpnjainv~ ~wpnjcinv~ ~wpsj0inv~ ~wpsj1inv~ ~wpsj2inv~ ~wpsj3inv~ ~wpsj4inv~ ~wpsj5inv~ ~wpsj6inv~ ~wpsj7inv~ ~wpsj8inv~ ~wpsj9inv~ ~wpsjainv~ ~wpsjcinv~ BEGIN
		COPY ~1pp/additions/obj_1pp_h/%resource%.bam~ ~override~
	END

END

ACTION_IF (1pp_armours_appearance = 2) BEGIN	// Faux Baldur's Gate I style (use BG1 icons but not animations)
	OUTER_SET 1pp_helmets_compatibility = 2		// based on Baldur's Gate I style 
END

/* -------------------------------- *
 *  Updated Baldur's Gate II style  *
 * -------------------------------- */

ACTION_IF (1pp_helmets_compatibility = 1) BEGIN

	PRINT @400022 // ~Installing helmet compatibility (Updated Baldur's Gate II style)...~
	SILENT

	ACTION_FOR_EACH set IN ~0~ ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%j%set%%sequence%.bam~ ~override/wq%category%h%set%%sequence%.bam~
			END
			COPY_EXISTING ~wp%category%j%set%inv.bam~ ~override/wp%category%h%set%inv.bam~
		END
	END

/* DEPRECATED as of v4.2.0
	ACTION_FOR_EACH set IN ~H0~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J0%sequence%.bam~ ~override/WQ%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H0~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J0%sequence%.bam~ ~override/WP%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H1~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J1%sequence%.bam~ ~override/WQ%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H1~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J1%sequence%.bam~ ~override/WP%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H2~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J2%sequence%.bam~ ~override/WQ%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H2~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J2%sequence%.bam~ ~override/WP%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H3~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J3%sequence%.bam~ ~override/WQ%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H3~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J3%sequence%.bam~ ~override/WP%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H4~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J4%sequence%.bam~ ~override/WQ%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H4~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J4%sequence%.bam~ ~override/WP%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H5~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J5%sequence%.bam~ ~override/WQ%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H5~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~INV~ BEGIN
				COPY_EXISTING ~WP%category%J5%sequence%.bam~ ~override/WP%category%%set%%sequence%.bam~
			END
		END
	END
*/
END // of ACTION_IF (1pp_helmets_compatibility = 1) = updated Baldur's Gate II style


/* -------------------------------- *
 *  Based on Baldur's Gate I style  *
 * -------------------------------- */

ACTION_IF (1pp_helmets_compatibility = 2) BEGIN

	PRINT @400023 // ~Installing helmet compatibility (Based on Baldur's Gate I style)...~
	SILENT

	ACTION_FOR_EACH set IN ~h0~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%j6%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~h1~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%j7%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~h2~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%j8%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~h3~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%j9%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~h4~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%j8%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~h5~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%ja%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

END // of ACTION_IF (1pp_helmets_compatibility = 2) = based on Baldur's Gate I style


/* --------------------- *
 *  1ppv4 style HELMETS  *
 * --------------------- */

ACTION_IF (1pp_helmets_appearance = 1) BEGIN

	PRINT @400024 // ~Patching helmets (1ppv4 style)...~
	SILENT

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm01.itm~) BEGIN
		COPY_EXISTING ~helm01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J6~			// replaces H0
				WRITE_ASCII 0x3A ~1HELM01~ #8	// replaces IHELM00
				WRITE_ASCII 0x58 ~CHELM01~ #8
				LPM ~clear~
				SET gradient = 14				// 14 DARK_PURE_SILVER replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 28				// sets colour index 28 BLUISH_SILVER
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 202			// sets colour index 202 HAIR2-LIBERTY_BLUE 
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of Opposite Alignment
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm02.itm~) BEGIN
		COPY_EXISTING ~helm02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H3
				WRITE_ASCII 0x3A ~1HELM26~ #8	// replaces IHELM04
				WRITE_ASCII 0x58 ~CHELM04~ #8
				LPM ~clear~
				SET gradient = 14				// 14 DARK_PURE_SILVER replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 21				// sets colour index 21 DARK_IRON_GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 21				// 21 DARK_IRON_GRAY replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 90				// sets colour index 90 MOLDY_GOLD
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 21				// sets colour index 21 DARK_IRON_GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Noble +1
	ACTION_FOR_EACH helmet IN ~helm03~ ~palhelm~ BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%helmet%.itm~) BEGIN
			COPY_EXISTING ~%helmet%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
					WRITE_ASCII 0x22 ~J8~			// replaces H1
					WRITE_ASCII 0x3A ~1HELM07~ #8	// replaces IHELM02
					WRITE_ASCII 0x58 ~1CHELMX6~ #8	// replaces CHELM02
					LPM ~clear~
					SET gradient = 207				// 207 NOBLE_MINOR2-CHROME_GOLD replaces colour index 27 GRAY
					SET location = hgrey			// location (Wings)
					LPM ~colour~
					SET gradient = 21				// sets colour index 21 DARK_IRON_GRAY
					SET location = hpink			// location (Plume)
					LPM ~colour~
					SET gradient = 184				// 184 CADET_BLUE replaces colour index 27 GRAY
					SET location = hblue			// location (Exterior)
					LPM ~colour~
					SET gradient = 21				// 21 DARK_IRON_GRAY replaces colour index 27 GRAY
					SET location = hred				// location (Face)
					LPM ~colour~
					//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
					SET gradient = 223				// sets colour index 223 DROW_SKIN-MOSS_GREEN
					SET location = hteal			// location (Detail)
					LPM ~colour~
					//END
				END
			BUT_ONLY
		END
	END

	// Gift of Peace
	ACTION_FOR_EACH helmet IN ~helm04~ ~chalhelm~ BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%helmet%.itm~) BEGIN
			COPY_EXISTING ~%helmet%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
					WRITE_ASCII 0x22 ~J1~			// replaces H2
					WRITE_ASCII 0x3A ~1HELM21~ #8	// replaces IHELM03
					WRITE_ASCII 0x58 ~1CHELM21~ #8	// replaces CHELM03
					LPM ~clear~
					SET gradient = 21				// 21 DARK_IRON_GRAY replaces colour index 27 GRAY
					SET location = hgrey			// location (Wings)
					LPM ~colour~
					SET gradient = 6				// sets colour index 6 DARK_SILVER
					SET location = hpink			// location (Plume)
					LPM ~colour~
					SET gradient = 142				// 142 DARK_POWDER_BLUE replaces colour index 27 GRAY
					SET location = hblue			// location (Exterior)
					LPM ~colour~
					SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
					SET location = hred				// location (Face)
					LPM ~colour~
					//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
					SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
					SET location = hteal			// location (Detail)
					LPM ~colour~
					//END
				END
			BUT_ONLY
		END
	END

	// The Eyes of Truth
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm05.itm~) BEGIN
		COPY_EXISTING ~helm05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM19~ #8	// replaces IHELM06
				WRITE_ASCII 0x58 ~1CHELM18~ #8	// replaces CHELM06
				LPM ~clear~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 47 PURE_DARK_RED
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER 
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// 224 DROW_MAJOR-MAIZE replaces colour index 47 PURE_DARK_RED
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 159				// sets colour index 159 MAUVE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Charm Protection
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm06.itm~) BEGIN
		COPY_EXISTING ~helm06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// replaces H2
				WRITE_ASCII 0x3A ~1HELM18~ #8	// replaces IHELM03
				WRITE_ASCII 0x58 ~1CHELM18~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 119				// sets colour index 119 DARKEST_ORCHID
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE 
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 118				// sets colour index 118 DARKER_ORCHID
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Balduran
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm07.itm~) BEGIN
		COPY_EXISTING ~helm07.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// replaces H1
				WRITE_ASCII 0x58 ~CHELM07~ #8
				LPM ~clear~
				SET gradient = 98				// 98 LEAF_GREEN replaces colour index 42 BEIGE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 114				// sets colour index 114 YET_ANOTHER_BROWN
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 241				// 241 THIEF_MAJOR-OLIVE replaces colour index 99 GOLDEN_BROWN
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 241				// sets colour index 241 THIEF_MAJOR-OLIVE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm08.itm~) BEGIN
		COPY_EXISTING ~helm08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// replaces H3
				WRITE_ASCII 0x3A ~1HELM05~ #8	// replaces IHELM04
				WRITE_ASCII 0x58 ~1CHELMX4~ #8	// replaces CHELM04
				LPM ~clear~
				SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 223			// sets colour index 223 DROW_SKIN-MOSS_GREEN
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm09.itm~) BEGIN
		COPY_EXISTING ~helm09.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// replaces H2
				WRITE_ASCII 0x3A ~1HELM17~ #8	// replaces IHELM03
				WRITE_ASCII 0x58 ~1CHELM17~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// sets colour index 195 CHROME_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm10.itm~) BEGIN
		COPY_EXISTING ~helm10.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// replaces H4
				WRITE_ASCII 0x3A ~1HELM20~ #8	// replaces IHELM05
				WRITE_ASCII 0x58 ~1CHELM20~ #8	// replaces CHELM05
				LPM ~clear~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 47 PURE_DARK_RED
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 99				// sets colour index 99 GOLDEN_BROWN
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// sets colour index 195 CHROME_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 210			// sets colour index 210 MERCHANT_MAJOR-AMBER 
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm11.itm~) BEGIN
		COPY_EXISTING ~helm11.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J6~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM08~ #8	// replaces IHELM06
				WRITE_ASCII 0x58 ~1CHELM01~ #8	// replaces CHELM06
				LPM ~clear~
				SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 47 PURE_DARK_RED
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 102				// 102 SEA_BLUE replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 102				// sets colour index 102 SEA_BLUE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 98			// sets colour index 98 LEAF_GREEN
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 102			// sets colour index 102 SEA_BLUE
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm12.itm~) BEGIN
		COPY_EXISTING ~helm12.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// replaces H1
				WRITE_ASCII 0x3A ~1HELM02~ #8	// replaces IHELM02
				WRITE_ASCII 0x58 ~1CHELMX2~ #8	// replaces CHELM02
				LPM ~clear~
				SET gradient = 195				// 195 CHROME_RED replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 21				// 21 DARK_IRON_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 242				// 242 THIEF_MINOR-PALE_OLIVE replaces colour index 24 BROWN_GOLD
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 109			// sets colour index 109 TERRA_COTTA
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm13.itm~) BEGIN
		COPY_EXISTING ~helm13.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J5~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM12~ #8	// replaces IHELM06
				WRITE_ASCII 0x58 ~CHELM05~ #8	// replaces CHELM06
				LPM ~clear~
				SET gradient = 210				// 210 MERCHANT_MAJOR-AMBER replaces colour index 47 PURE_DARK_RED
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 102				// 102 SEA_BLUE replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 248				// sets colour index 248 OGRE_MAJOR-BATTLESHIP_GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// sets colour index 195 CHROME_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Kiel's Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm14.itm~) BEGIN
		COPY_EXISTING ~helm14.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// replaces H1
				WRITE_ASCII 0x3A ~1HELM22~ #8	// replaces IHELM14
				WRITE_ASCII 0x58 ~CHELM07~ #8
				LPM ~clear~
				SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 42 BEIGE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 182				// 182 DEEP_BLACK replaces colour index 99 GOLDEN_BROWN
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 98 LEAF_GREEN
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 21				// sets colour index 21 DARK_IRON_GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 225				// sets colour index 225 DROW_MINOR-CORNSILK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm15.itm~) BEGIN
		COPY_EXISTING ~helm15.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J0~			// replaces H4
				WRITE_ASCII 0x3A ~1HELM15~ #8	// replaces IHELM05
				WRITE_ASCII 0x58 ~1CHELM11~ #8	// replaces CHELM05
				LPM ~clear~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 232			// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of Brilliance
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm16.itm~) BEGIN
		COPY_EXISTING ~helm16.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J4~			// replaces H2
				WRITE_ASCII 0x3A ~1HELM16~ #8	// replaces IHELM03
				WRITE_ASCII 0x58 ~CHELM16~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 205				// 205 NOBLE_MINOR2-CHROME_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 226				// sets colour index 226 METAL_NORMAL-EIGENGRAU
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Skull of Death
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm17.itm~) BEGIN
		COPY_EXISTING ~helm17.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H0
				LPM ~clear~
				SET gradient = 98				// 98 LEAF_GREEN replaces colour index 100 DARK_ASH_GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 3				// 3 LIGHT_GOLD replaces colour index 106 PALE_PINK
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 253				// sets colour index 253 DUERGAR_MINOR-PALE_TAUPE
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Dragon Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm21.itm~) BEGIN
		COPY_EXISTING ~helm21.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// replaces H2
				LPM ~clear~
				SET gradient = 227				// 227 METAL_WILD-CORAL replaces colour index 33 CHROME_MAGENTA
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 88				// 88 CHROME_PINK replaces colour index 33 CHROME_MAGENTA
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 70				// sets colour index 70 LIGHT_METALLIC_RED
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm22.itm~) BEGIN
		COPY_EXISTING ~helm22.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// replaces H3
				WRITE_ASCII 0x3A ~1HELM03~ #8	// replaces IHELM04
				WRITE_ASCII 0x58 ~1CHELMX3~ #8	// replaces CHELM04
				LPM ~clear~
				SET gradient = 119				// 119 DARKEST_ORCHID replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 205				// 205 NOBLE_MINOR2-CHROME_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 209				// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 102				// sets colour index 102 SEA_BLUE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm31.itm~) BEGIN
		COPY_EXISTING ~helm31.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// replaces H0
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// replaces PHELM31
				LPM ~clear~
				SET gradient = 66				// 66 FADED_BLACK replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 183				// 183 CHARCOAL replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 183				// 183 CHARCOAL replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm32.itm~) BEGIN
		COPY_EXISTING ~helm32.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// replaces H1 (Gwen todo: check J3 in EE)
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// replaces PHELM32
				LPM ~clear~
				SET gradient = 207				// 207 NOBLE_MINOR2-CHROME_GOLD replaces colour index 27 GRAY7 (Gwen todo: check 233 in EE)
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 199				// 199 BLACK_TEAL replaces colour index 30 (Gwen todo: check 208 ATH_PEASANT_MAJOR-FADED_WHEAT in EE)
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 199				// 199 BLACK_TEAL replaces colour index 27 GRAY (Gwen todo: check 208 ATH_PEASANT_MAJOR-FADED_WHEAT in EE)
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Gold Horned Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm33.itm~) BEGIN
		COPY_EXISTING ~helm33.itm~ ~override~	// fix typo (was patching helm32 instead of helm33)
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H3 (not modified in EE)
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 42 BEIGE (not modified in EE)
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 208				// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 99 GOLDEN_BROWN (not modified in EE)
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 208				// sets colour index 208 ATH_PEASANT_MAJOR-FADED_WHEAT
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Roranach's Horn
	ACTION_IF (FILE_EXISTS_IN_GAME ~compon05.itm~) BEGIN
		COPY_EXISTING ~compon05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// replaces H3
				LPM ~clear~
				SET gradient = 225				// 225 DROW_MINOR-CORNSILK replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 250				// 250 SHADOW_DRUID_MAJOR-YELLOW_ORANGE replaces colour index 51 DARK_OLIVE_GREEN
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 47				// sets colour index 47 PURE_DARK_RED
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER 
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 250				// sets colour index 250 SHADOW_DRUID_MAJOR-YELLOW_ORANGE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Vhailor's Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~wa2helm.itm~) BEGIN
		COPY_EXISTING ~wa2helm.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H0
				WRITE_ASCII 0x3A ~1HELM24~ #8	// replaces IHELM17
				WRITE_ASCII 0x58 ~CHELM04~ #8	// replaces CHELM17
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 100 DARK_ASH_GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// 27 GRAY replaces colour index 106 PALE_PINK
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

END	// of ACTION_IF (1pp_helmets_appearance = 1) = END of 1ppv4 style HELMETS


/* -------------- *
 *  TUTU HELMETS  *
 * -------------- */

ACTION_IF (is_tutu) BEGIN
	PRINT @400025 // ~Patching Tutu helmets...~
	SILENT

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm01.itm~) BEGIN
		COPY_EXISTING ~_helm01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H0~			// replaces H
				WRITE_ASCII 0x58 ~1CHELM01~ #8
				LPM ~clear~
				SET gradient = 223				// sets colour index 223 DROW_SKIN-MOSS_GREEN
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Noble +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm03.itm~) BEGIN
		COPY_EXISTING ~_helm03.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H2~			// replaces H
				WRITE_ASCII 0x58 ~1CHELM03~ #8
				LPM ~clear~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 90				// sets colour index 90 MOLDY_GOLD
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 30				// sets colour index 30 LIGHT_IRON_GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 30				// sets colour index 30 LIGHT_IRON_GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 30				// sets colour index 30 LIGHT_IRON_GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Gift of Peace
	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm04.itm~) BEGIN
		COPY_EXISTING ~_helm04.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H5~			// replaces H
				WRITE_ASCII 0x58 ~1CHELM04~ #8
				LPM ~clear~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 202				// sets colour index 202 HAIR2-LIBERTY_BLUE 
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 5				// sets colour index 5 MEDIUM_SILVER
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 5				// sets colour index 5 MEDIUM_SILVER
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// The Eyes of Truth
	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm05.itm~) BEGIN
		COPY_EXISTING ~_helm05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// replaces H
				WRITE_ASCII 0x3A ~1HELM20~ #8
				WRITE_ASCII 0x58 ~1CHELM20~ #8
				LPM ~clear~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 99				// sets colour index 99 GOLDEN_BROWN
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER 
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Charm Protection
	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm06.itm~) BEGIN
		COPY_EXISTING ~_helm06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~
				WRITE_ASCII 0x3A ~1HELM18~ #8
				WRITE_ASCII 0x58 ~1CHELM18~ #8
				LPM ~clear~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 119				// sets colour index 119 DARKEST_ORCHID
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 118				// sets colour index 118 DARKER_ORCHID
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Balduran
	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm07.itm~) BEGIN
		COPY_EXISTING ~_helm07.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~
				WRITE_ASCII 0x3A ~1HELM00~ #8
				WRITE_ASCII 0x58 ~CHELM07~ #8
				LPM ~clear~
				SET gradient = 223				// sets colour index 223 DROW_SKIN-MOSS_GREEN
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 66				// sets colour index 66 FADED_BLACK
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 173				// sets colour index 173 MOSSY_GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmets
	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm08.itm~) BEGIN
		COPY_EXISTING ~_helm08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~
				WRITE_ASCII 0x3A ~1HELM03~ #8
				WRITE_ASCII 0x58 ~1CHELMX3~ #8
				LPM ~clear~
				SET gradient = 119				// sets colour index 119 DARKEST_ORCHID
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 205				// sets colour index 205 NOBLE_MINOR2-CHROME_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 209				// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 102				// sets colour index 102 SEA_BLUE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm09.itm~) BEGIN
		COPY_EXISTING ~_helm09.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H3~
				//WRITE_ASCII 0x3A ~1HELM03~ #8
				WRITE_ASCII 0x58 ~1CHELM06~ #8
				LPM ~clear~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// sets colour index 195 CHROME_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm10.itm~) BEGIN
		COPY_EXISTING ~_helm10.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H5~
				//WRITE_ASCII 0x3A ~1HELM03~ #8
				WRITE_ASCII 0x58 ~1CHELM05~ #8
				LPM ~clear~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 47			// sets colour index 47 PURE_DARK_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 127			// sets colour index 127 DARK_BRICK_RED
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm11.itm~) BEGIN
		COPY_EXISTING ~_helm11.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~
				WRITE_ASCII 0x3A ~1HELM04~ #8
				WRITE_ASCII 0x58 ~1CHELMX4~ #8
				LPM ~clear~
				SET gradient = 248				// sets colour index 248 OGRE_MAJOR-BATTLESHIP_GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY sets colour index
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 202			// sets colour index 202 HAIR2-LIBERTY_BLUE 
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 202			// sets colour index 202 HAIR2-LIBERTY_BLUE 
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm12.itm~) BEGIN
		COPY_EXISTING ~_helm12.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~
				WRITE_ASCII 0x3A ~IHELM04~ #8
				WRITE_ASCII 0x58 ~1CHELM02~ #8
				LPM ~clear~
				SET gradient = 235				// sets colour index 235 CLERIC_GOOD_MAJOR-GLAUCOUS_GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 102				// sets colour index 102 SEA_BLUE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 232			// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 232			// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm13.itm~) BEGIN
		COPY_EXISTING ~_helm13.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~
				WRITE_ASCII 0x3A ~1HELM17~ #8
				WRITE_ASCII 0x58 ~1CHELM17~ #8
				LPM ~clear~
				SET gradient = 223				// sets colour index 223 DROW_SKIN-MOSS_GREEN
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// sets colour index 195 CHROME_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Kiel's Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm14.itm~) BEGIN
		COPY_EXISTING ~_helm14.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~
				WRITE_ASCII 0x58 ~CHELM07~ #8
				LPM ~clear~
				SET gradient = 98				// sets colour index 98 LEAF_GREEN
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 114				// sets colour index 114 YET_ANOTHER_BROWN
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 241				// sets colour index 241 THIEF_MAJOR-OLIVE
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 241				// sets colour index 241 THIEF_MAJOR-OLIVE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~_helm15.itm~) BEGIN
		COPY_EXISTING ~_helm15.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~
				WRITE_ASCII 0x3A ~1HELM09~ #8
				WRITE_ASCII 0x58 ~1CHELMX9~ #8
				LPM ~clear~
				SET gradient = 226				// sets colour index 226 METAL_NORMAL-EIGENGRAU
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				SET gradient = 232				// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 102				// sets colour index 102 SEA_BLUE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 208			// sets colour index 208 ATH_PEASANT_MAJOR-FADED_WHEAT
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

END // of ACTION_IF (is_tutu)


/* ------------------------ *
 *  Faux BG1 style HELMETS  *
 * ------------------------ */

ACTION_IF (1pp_helmets_appearance = 2) BEGIN

	PRINT @400026 // ~Patching helmets (Faux Baldur's Gate I style - use BG1 icons but not animations)...~
	SILENT

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm01.itm~) BEGIN
		COPY_EXISTING ~helm01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H0~			// replaces H0
				WRITE_ASCII 0x58 ~1CHELM01~ #8	// replaces CHELM01
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// 27 GRAY replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Opposite Alignment
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm02.itm~) BEGIN
		COPY_EXISTING ~helm02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// replaces H3
				WRITE_ASCII 0x3A ~1HELM06~ #8	// replaces IHELM04
				WRITE_ASCII 0x58 ~1CHELMX6~ #8	// replaces CHELM04
				LPM ~clear~
				SET gradient = 249				// 249 OGRE_MINOR-METALLIC_SLATE replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Noble +1
	ACTION_FOR_EACH helmet IN ~helm03~ ~palhelm~ BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%helmet%.itm~) BEGIN
			COPY_EXISTING ~%helmet%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
					WRITE_ASCII 0x22 ~H2~			// replaces H1
					//WRITE_ASCII 0x3A ~1HELM06~ #8
					WRITE_ASCII 0x58 ~1CHELM03~ #8	// replaces CHELM02
					LPM ~clear~
					SET gradient = 224				// 224 DROW_MAJOR-MAIZE replaces colour index 27 GRAY
					SET location = hgrey			// location (Wings)
					LPM ~colour~
					SET gradient = 90				// 90 MOLDY_GOLD replaces colour index 27 GRAY
					SET location = hblue			// location (Exterior)
					LPM ~colour~
					SET gradient = 30				// 30 LIGHT_IRON_GRAY replaces colour index 27 GRAY
					SET location = hred				// location (Face)
					LPM ~colour~
					SET gradient = 30				// sets colour index 30 LIGHT_IRON_GRAY
					SET location = hteal			// location (Detail)
					LPM ~colour~
					//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
					SET gradient = 30				// sets colour index 30 LIGHT_IRON_GRAY
					SET location = hpink			// location (Plume)
					LPM ~colour~
					//END
				END
			BUT_ONLY
		END
	END

	// Gift of Peace
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm04.itm~) BEGIN
		COPY_EXISTING ~helm04.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H5~			// replaces H2
				//WRITE_ASCII 0x3A ~1HELM06~ #8
				WRITE_ASCII 0x58 ~1CHELM04~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 5				// sets colour index 5 MEDIUM_SILVER
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 5				// sets colour index 5 MEDIUM_SILVER
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// The Eyes of Truth
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm05.itm~) BEGIN
		COPY_EXISTING ~helm05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM20~ #8	// replaces IHELM06
				WRITE_ASCII 0x58 ~1CHELM20~ #8	// replaces CHELM06
				LPM ~clear~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 47 PURE_DARK_RED
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 99				// 99 GOLDEN_BROWN replaces colour index 47 PURE_DARK_RED
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER 
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Charm Protection
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm06.itm~) BEGIN
		COPY_EXISTING ~helm06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// replaces H2
				WRITE_ASCII 0x3A ~1HELM18~ #8	// replaces IHELM03
				WRITE_ASCII 0x58 ~1CHELM18~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 119				// sets colour index 119 DARKEST_ORCHID
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 118				// sets colour index 118 DARKER_ORCHID
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Balduran
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm07.itm~) BEGIN
		COPY_EXISTING ~helm07.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// replaces H1
				WRITE_ASCII 0x3A ~1HELM00~ #8	// replaces IHELM14
				WRITE_ASCII 0x58 ~CHELM07~ #8	// replaces CHELM07
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 42 BEIGE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 66				// 66 FADED_BLACK replaces colour index 99 GOLDEN_BROWN
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 173				// sets colour index 173 MOSSY_GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm08.itm~) BEGIN
		COPY_EXISTING ~helm08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// replaces H3
				WRITE_ASCII 0x3A ~1HELM03~ #8	// replaces IHELM04
				WRITE_ASCII 0x58 ~1CHELMX3~ #8	// replaces CHELM04
				LPM ~clear~
				SET gradient = 119				// 119 DARKEST_ORCHID replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 205				// 205 NOBLE_MINOR2-CHROME_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 209				// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 102				// sets colour index 102 SEA_BLUE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm09.itm~) BEGIN
		COPY_EXISTING ~helm09.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H3~			// replaces H2
				//WRITE_ASCII 0x3A ~1HELM03~ #8
				WRITE_ASCII 0x58 ~1CHELM06~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// sets colour index 195 CHROME_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm10.itm~) BEGIN
		COPY_EXISTING ~helm10.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H5~			// replaces H4
				//WRITE_ASCII 0x3A ~1HELM03~ #8
				WRITE_ASCII 0x58 ~1CHELM05~ #8	// replaces CHELM05
				LPM ~clear~
				SET gradient = 27				// 27 GRAY replaces colour index 47 PURE_DARK_RED
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 47			// sets colour index 47 PURE_DARK_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 127			// sets colour index 127 DARK_BRICK_RED
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm11.itm~) BEGIN
		COPY_EXISTING ~helm11.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM04~ #8	// replaces IHELM06
				WRITE_ASCII 0x58 ~1CHELMX4~ #8	// replaces CHELM06
				LPM ~clear~
				SET gradient = 248				// 248 OGRE_MAJOR-BATTLESHIP_GRAY replaces colour index 47
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 202			// sets colour index 202 HAIR2-LIBERTY_BLUE
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 202			// sets colour index 202 HAIR2-LIBERTY_BLUE
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm12.itm~) BEGIN
		COPY_EXISTING ~helm12.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// replaces H1
				WRITE_ASCII 0x3A ~IHELM04~ #8	// replaces IHELM02
				WRITE_ASCII 0x58 ~1CHELM02~ #8	// replaces CHELM02
				LPM ~clear~
				SET gradient = 235				// 235 CLERIC_GOOD_MAJOR-GLAUCOUS_GRAY replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 102				// 102 SEA_BLUE replaces colour index 24 BROWN_GOLD
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 232			// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 232			// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm13.itm~) BEGIN
		COPY_EXISTING ~helm13.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM17~ #8	// replaces IHELM06
				WRITE_ASCII 0x58 ~1CHELM17~ #8	// replaces CHELM6
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 47 PURE_DARK_RED
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// sets colour index 195 CHROME_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Kiel's Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm14.itm~) BEGIN
		COPY_EXISTING ~helm14.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// replaces H1
				WRITE_ASCII 0x58 ~CHELM07~ #8	// replaces CHELM07
				LPM ~clear~
				SET gradient = 98				// 98 LEAF_GREEN replaces colour index 42 BEIGE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 114				// sets colour index 114 YET_ANOTHER_BROWN
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 241				// 241 THIEF_MAJOR-OLIVE replaces colour index 99 GOLDEN_BROWN
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 98 LEAF_GREEN
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 241				// sets colour index 241 THIEF_MAJOR-OLIVE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm15.itm~) BEGIN
		COPY_EXISTING ~helm15.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// replaces H4
				WRITE_ASCII 0x3A ~1HELM09~ #8	// replaces IHELM05
				WRITE_ASCII 0x58 ~1CHELMX9~ #8	// replaces CHELM05
				LPM ~clear~
				SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 102				// 102 SEA_BLUE replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 208			// sets colour index 208 ATH_PEASANT_MAJOR-FADED_WHEAT
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of Brilliance
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm16.itm~) BEGIN
		COPY_EXISTING ~helm16.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// replaces H2
				WRITE_ASCII 0x3A ~1HELM02~ #8	// replaces IHELM03
				WRITE_ASCII 0x58 ~1CHELMX2~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 195				// 195 CHROME_RED replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 21				// 21 DARK_IRON_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 242				// sets colour index 242 THIEF_MINOR-PALE_OLIVE
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 109				// sets colour index 109 TERRA_COTTA
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Skull of Death
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm17.itm~) BEGIN
		COPY_EXISTING ~helm17.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H0
				LPM ~clear~
				SET gradient = 98				// 98 LEAF_GREEN replaces colour index 100 DARK_ASH_GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 3				// 3 LIGHT_GOLD replaces colour index 106 PALE_PINK
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 253				// sets colour index 253 DUERGAR_MINOR-PALE_TAUPE
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Dragon Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm21.itm~) BEGIN
		COPY_EXISTING ~helm21.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// replaces H2
				LPM ~clear~
				SET gradient = 227				// 227 METAL_WILD-CORAL replaces colour index 33 CHROME_MAGENTA
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 88				// 88 CHROME_PINK replaces colour index 33 CHROME_MAGENTA
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 70				// sets colour index 70 LIGHT_METALLIC_RED
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm22.itm~) BEGIN
		COPY_EXISTING ~helm22.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H0~			// replaces H3
				WRITE_ASCII 0x3A ~1HELM08~ #8	// replaces IHELM04
				WRITE_ASCII 0x58 ~1CHELM01~ #8	// replaces CHELM04
				LPM ~clear~
				SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm31.itm~) BEGIN
		COPY_EXISTING ~helm31.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// replaces H0
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// replaces PHELM31
				LPM ~clear~
				SET gradient = 66				// 66 FADED_BLACK replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 183				// 183 CHARCOAL replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 183				// 183 CHARCOAL replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm32.itm~) BEGIN
		COPY_EXISTING ~helm32.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// replaces H1
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// replaces PHELM32
				LPM ~clear~
				SET gradient = 207				// 207 NOBLE_MINOR2-CHROME_GOLD replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 199				// 199 BLACK_TEAL replaces colour index 30
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 199				// 199 BLACK_TEAL replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Gold Horned Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm33.itm~) BEGIN
		COPY_EXISTING ~helm33.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// replaces H3
				LPM ~clear~
				SET gradient = 225				// 225 DROW_MINOR-CORNSILK replaces colour index 42 BEIGE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 250				// 250 SHADOW_DRUID_MAJOR-YELLOW_ORANGE replaces colour index 99 GOLDEN_BROWN
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 47				// sets colour index 47 PURE_DARK_RED
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER 
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 250				// sets colour index 250 SHADOW_DRUID_MAJOR-YELLOW_ORANGE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Roranach's Horn
	ACTION_IF (FILE_EXISTS_IN_GAME ~compon05.itm~) BEGIN
		COPY_EXISTING ~compon05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// replaces H3
				LPM ~clear~
				SET gradient = 225				// 225 DROW_MINOR-CORNSILK replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 250				// 250 SHADOW_DRUID_MAJOR-YELLOW_ORANGE replaces colour index 51 DARK_OLIVE_GREEN
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 47				// sets colour index 47 PURE_DARK_RED
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 250				// sets colour index 250 SHADOW_DRUID_MAJOR-YELLOW_ORANGE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Vhailor's Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~wa2helm.itm~) BEGIN
		COPY_EXISTING ~wa2helm.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H0
				WRITE_ASCII 0x3A ~1HELM24~ #8	// replaces IHELM17
				WRITE_ASCII 0x58 ~CHELM04~ #8	// replaces CHELM17
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 100 DARK_ASH_GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// 27 GRAY replaces colour index 106 PALE_PINK
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

END	// of ACTION_IF (1pp_helmets_appearance = 2) = faux BG1 style HELMETS


/* ------------------- *
 *  BG2 style HELMETS  *
 * ------------------- */

ACTION_IF (1pp_helmets_appearance = 3) BEGIN

	PRINT @400027 // ~Patching helmets (Baldur's Gate II style)...~
	SILENT

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm01.itm~) BEGIN
		COPY_EXISTING ~helm01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J6~			// replaces H0
				WRITE_ASCII 0x3A ~1HELM01~ #8	// replaces IHELM00
				WRITE_ASCII 0x58 ~CHELM01~ #8
				LPM ~clear~
				SET gradient = 14				// 14 DARK_PURE_SILVER replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 28				// sets colour index 28 BLUISH_SILVER
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 202			// sets colour index 202 HAIR2-LIBERTY_BLUE 
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of Opposite Alignment
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm02.itm~) BEGIN
		COPY_EXISTING ~helm02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// replaces H3
				WRITE_ASCII 0x3A ~1HELM02~ #8	// replaces IHELM04
				WRITE_ASCII 0x58 ~1CHELMX2~ #8	// replaces CHELM04
				LPM ~clear~
				SET gradient = 195				// 195 CHROME_RED replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 21				// 21 DARK_IRON_GRAY replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 242				// sets colour index 242 THIEF_MINOR-PALE_OLIVE
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 109				// sets colour index 109 TERRA_COTTA
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Noble +1
	ACTION_FOR_EACH helmet IN ~helm03~ ~palhelm~ BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%helmet%.itm~) BEGIN
			COPY_EXISTING ~%helmet%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
					WRITE_ASCII 0x22 ~J1~			// replaces H1
					WRITE_ASCII 0x3A ~1HELM21~ #8	// replaces IHELM02
					WRITE_ASCII 0x58 ~1CHELM21~ #8	// replaces CHELM02
					LPM ~clear~
					SET gradient = 21				// 21 DARK_IRON_GRAY replaces colour index 27 GRAY
					SET location = hgrey			// location (Wings)
					LPM ~colour~
					SET gradient = 6				// sets colour index 6 DARK_SILVER
					SET location = hpink			// location (Plume)
					LPM ~colour~
					SET gradient = 142				// 142 DARK_POWDER_BLUE replaces colour index 27 GRAY
					SET location = hblue			// location (Exterior)
					LPM ~colour~
					SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 27 GRAY
					SET location = hred				// location (Face)
					LPM ~colour~
					//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
					SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
					SET location = hteal			// location (Detail)
					LPM ~colour~
					//END
				END
			BUT_ONLY
		END
	END

	// Gift of Peace
	ACTION_FOR_EACH helmet IN ~helm04~ ~chalhelm~ BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%helmet%.itm~) BEGIN
			COPY_EXISTING ~%helmet%.itm~ ~override~
				PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
					WRITE_ASCII 0x22 ~J4~			// replaces H2
					WRITE_ASCII 0x3A ~1HELM10~ #8	// replaces IHELM03
					WRITE_ASCII 0x58 ~CHELM06~ #8	// replaces CHELM03
					LPM ~clear~
					SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 27 GRAY
					SET location = hgrey			// location (Wings)
					LPM ~colour~
					SET gradient = 195				// sets colour index 195 CHROME_RED
					SET location = hpink			// location (Plume)
					LPM ~colour~
					SET gradient = 192				// 192 CHROME_TEAL replaces colour index 27 GRAY
					SET location = hblue			// location (Exterior)
					LPM ~colour~
					SET gradient = 209				// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
					SET location = hred				// location (Face)
					LPM ~colour~
					//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
					SET gradient = 200				// sets colour index 200 HAIR1-WHITE_TEAL
					SET location = hteal			// location (Detail)
					LPM ~colour~
					//END
				END
			BUT_ONLY
		END
	END

	// The Eyes of Truth
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm05.itm~) BEGIN
		COPY_EXISTING ~helm05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J4~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM16~ #8	// replaces IHELM06
				WRITE_ASCII 0x58 ~CHELM16~ #8	// replaces CHELM06
				LPM ~clear~
				SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 47 PURE_DARK_RED
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 205				// 205 NOBLE_MINOR2-CHROME_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 47 PURE_DARK_RED
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Charm Protection
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm06.itm~) BEGIN
		COPY_EXISTING ~helm06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J5~			// replaces H2
				WRITE_ASCII 0x3A ~1HELM12~ #8	// replaces IHELM03
				WRITE_ASCII 0x58 ~CHELM05~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 210				// 210 MERCHANT_MAJOR-AMBER replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 102				// 102 SEA_BLUE replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 248				// sets colour index 248 OGRE_MAJOR-BATTLESHIP_GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// sets colour index 195 CHROME_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of Balduran
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm07.itm~) BEGIN
		COPY_EXISTING ~helm07.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// replaces H1
				WRITE_ASCII 0x58 ~CHELM07~ #8	// replaces CHELM07
				LPM ~clear~
				SET gradient = 98				// 98 LEAF_GREEN replaces colour index 42 BEIGE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 114				// sets colour index 114 YET_ANOTHER_BROWN
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 241				// 241 THIEF_MAJOR-OLIVE replaces colour index 99 GOLDEN_BROWN
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 241				// sets colour index 241 THIEF_MAJOR-OLIVE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm08.itm~) BEGIN
		COPY_EXISTING ~helm08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H3
				WRITE_ASCII 0x3A ~1HELM23~ #8	// replaces IHELM04
				WRITE_ASCII 0x58 ~CHELM04~ #8	// replaces CHELM04
				LPM ~clear~
				SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 202				// sets colour index 202 HAIR2-LIBERTY_BLUE 
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm09.itm~) BEGIN
		COPY_EXISTING ~helm09.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J6~			// replaces H2
				WRITE_ASCII 0x3A ~1HELM08~ #8	// replaces IHELM03
				WRITE_ASCII 0x58 ~1CHELM01~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 102				// 102 SEA_BLUE replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 102				// sets colour index 102 SEA_BLUE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 98			// sets colour index 98 LEAF_GREEN
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 102			// sets colour index 102 SEA_BLUE
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm10.itm~) BEGIN
		COPY_EXISTING ~helm10.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J0~			// replaces H4
				WRITE_ASCII 0x3A ~1HELM14~ #8	// replaces IHELM05
				WRITE_ASCII 0x58 ~1CHELM11~ #8	// replaces CHELM05
				LPM ~clear~
				SET gradient = 98				// 98 LEAF_GREEN replaces colour index 47 PURE_DARK_RED
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 91				// sets colour index 91 DARK_CHOCOLATE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 98			// sets colour index 98 LEAF_GREEN
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 232			// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm11.itm~) BEGIN
		COPY_EXISTING ~helm11.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J5~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM12~ #8	// replaces IHELM06
				WRITE_ASCII 0x58 ~CHELM05~ #8	// replaces CHELM06
				LPM ~clear~
				SET gradient = 210				// 210 MERCHANT_MAJOR-AMBER replaces colour index 47 PURE_DARK_RED
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 249				// 249 OGRE_MINOR-METALLIC_SLATE replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 91				// sets colour index 91 DARK_CHOCOLATE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 195			// sets colour index 195 CHROME_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm12.itm~) BEGIN
		COPY_EXISTING ~helm12.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J0~			// replaces H1
				WRITE_ASCII 0x3A ~1HELM11~ #8	// replaces IHELM02
				WRITE_ASCII 0x58 ~1CHELM11~ #8	// replaces CHELM02
				LPM ~clear~
				SET gradient = 21				// 21 DARK_IRON_GRAY replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 27				// 27 GRAY replaces colour index 24 BROWN_GOLD
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 27			// sets colour index 27 GRAY
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 200			// sets colour index 200 HAIR1-WHITE_TEAL
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm13.itm~) BEGIN
		COPY_EXISTING ~helm13.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J0~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM15~ #8	// replaces IHELM06
				WRITE_ASCII 0x58 ~1CHELM11~ #8	// replaces CHELM06
				LPM ~clear~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 47 PURE_DARK_RED
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 232				// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 98			// sets colour index 98 LEAF_GREEN
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 232			// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Kiel's Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm14.itm~) BEGIN
		COPY_EXISTING ~helm14.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// replaces H1
				WRITE_ASCII 0x3A ~1HELM22~ #8	// replaces IHELM14
				WRITE_ASCII 0x58 ~CHELM07~ #8
				LPM ~clear~
				SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 42 BEIGE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 182				// 182 DEEP_BLACK replaces colour index 99 GOLDEN_BROWN
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 98 LEAF_GREEN
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 21				// sets colour index 21 DARK_IRON_GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 225				// sets colour index 225 DROW_MINOR-CORNSILK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm15.itm~) BEGIN
		COPY_EXISTING ~helm15.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H4
				WRITE_ASCII 0x3A ~1HELM25~ #8	// replaces IHELM05
				WRITE_ASCII 0x58 ~CHELM04~ #8	// replaces CHELM05
				LPM ~clear~
				SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Brilliance
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm16.itm~) BEGIN
		COPY_EXISTING ~helm16.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J4~			// replaces H2
				WRITE_ASCII 0x3A ~1HELM16~ #8	// replaces IHELM03
				WRITE_ASCII 0x58 ~CHELM16~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 205				// 205 NOBLE_MINOR2-CHROME_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 226				// sets colour index 226 METAL_NORMAL-EIGENGRAU
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Skull of Death
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm17.itm~) BEGIN
		COPY_EXISTING ~helm17.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H0
				LPM ~clear~
				SET gradient = 98				// 98 LEAF_GREEN replaces colour index 100 DARK_ASH_GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 3				// 3 LIGHT_GOLD replaces colour index 106 PALE_PINK
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 253				// sets colour index 253 DUERGAR_MINOR-PALE_TAUPE
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Dragon Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm21.itm~) BEGIN
		COPY_EXISTING ~helm21.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J2~			// replaces H2
				LPM ~clear~
				SET gradient = 227				// 227 METAL_WILD-CORAL replaces colour index 33 CHROME_MAGENTA
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 88				// 88 CHROME_PINK replaces colour index 33 CHROME_MAGENTA
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 70				// sets colour index 70 LIGHT_METALLIC_RED
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm22.itm~) BEGIN
		COPY_EXISTING ~helm22.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// replaces H3
				WRITE_ASCII 0x3A ~1HELM05~ #8	// replaces IHELM04
				WRITE_ASCII 0x58 ~1CHELMX4~ #8	// replaces CHELM04
				LPM ~clear~
				SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 223			// sets colour index 223 DROW_SKIN-MOSS_GREEN
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm31.itm~) BEGIN
		COPY_EXISTING ~helm31.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H0
				WRITE_ASCII 0x3A ~1HELM25~ #8	// replaces IHELM31
				WRITE_ASCII 0x58 ~CHELM04~ #8	// replaces PHELM31
				LPM ~clear~
				SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of the Rock
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm32.itm~) BEGIN
		COPY_EXISTING ~helm32.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H1
				WRITE_ASCII 0x3A ~1HELM26~ #8	// replaces IHELM32
				WRITE_ASCII 0x58 ~CHELM04~ #8	// replaces PHELM32
				LPM ~clear~
				SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 207				// 207 NOBLE_MINOR2-CHROME_GOLD replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 228				// 228 LEATHER-SPECTRAL_GREEN replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Gold Horned Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm33.itm~) BEGIN
		COPY_EXISTING ~helm33.itm~ ~override~	// fix typo (was copying helm32 instead of helm33)
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H0
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 208				// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 208				// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Roranach's Horn
	ACTION_IF (FILE_EXISTS_IN_GAME ~compon05.itm~) BEGIN
		COPY_EXISTING ~compon05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H3
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 208				// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 51 DARK_OLIVE_GREEN
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 208				// sets colour index 208 ATH_PEASANT_MAJOR-FADED_WHEAT
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Vhailor's Helm
	ACTION_IF (FILE_EXISTS_IN_GAME ~wa2helm.itm~) BEGIN
		COPY_EXISTING ~wa2helm.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// replaces H0
				WRITE_ASCII 0x3A ~1HELM24~ #8	// replaces IHELM17
				WRITE_ASCII 0x58 ~CHELM04~ #8	// replaces CHELM17
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 100 DARK_ASH_GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// 27 GRAY replaces colour index 106 PALE_PINK
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

END	// of ACTION_IF (1pp_helmets_appearance = 3) = BG2 style HELMETS



/* ================================================================================================================================================================================= *
 *                                                               ADD CIRCLETS                                                                                                        *
 * ================================================================================================================================================================================= *
 *  change-log:                                                                                                                                                                      *
 *  -----------                                                                                                                                                                      *
 *      - Lollorian's BWP Fixpack patch for Ashes of Embers compatibility (400_1pp_update_bgii.tph.patch): Renames 1PPv4 BAND0X.ITMs to XOBAND0X.ITMs, using Lollorian's prefix      *
 *        (according to BWL: XO, submitted by Chaplain, 11.03.2010, Prefix owner also known as Lollorian).                                                                           *
 *        Source: http://www.shsforums.net/topic/56643-1pp-circlets-and-bg2tweaks-issue/?p=561849                                                                                    *
 *      - Added ToBEx compatibility: item flag EE/Ex: Toggle critical hits flag (BIT25).                                                                                             *
 *                                                                                                                                                                                   *
 *  Fix wrong coding:                                                                                                                                                                *
 *  -----------------                                                                                                                                                                *
 *  - #2735 ==> Silver Circlet (xoband02.itm): Opcodes #33, 34 & 35: parameter2 originally set to 1 should be 0, adds #36 & 37 to match item description = +1 to all saving throws.  *
 *  - #2785 ==> Eilistraee's Boon +1 (xoband03.itm). Same fix for opcodes #33, 34, 35, 36 & 37.                                                                                      *
 *              Op#31: parameter1 originally set to 110 should be 10, and parameter2 switched from 2 to 0 to match item description (+10% Magic damage Resistance).                  *
 *  - #2815 ==> Circlet of the Archmagi (xoband04.itm): Same fix for opcodes #33, 34, 35, 36 & 37. Added one missing equipped effects (`LPM ADD_ITEM_EQEFFECT #19`).                 *
 * ================================================================================================================================================================================= */

PRINT @400028 // ~Installing and patching circlets...~
SILENT

ACTION_IF (FILE_EXISTS_IN_GAME ~amul02.itm~) BEGIN

	// Silver Circlet
	COPY_EXISTING ~amul02.itm~ ~override/xoband02.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME1 @400601 /* Circlet */
			SAY NAME2 @400602
			SAY UNIDENTIFIED_DESC @400603
			SAY DESC  @400604
			WRITE_ASCII 0x22 ~JB~
			WRITE_ASCII 0x3A ~1BAND01~ #8
			WRITE_ASCII 0x58 ~1CBAND01~ #8
			WRITE_LONG	0x18 0x6c				// Flags : Droppable - Displayable - Not copyable - Magical
			WRITE_SHORT 0x1c 0x07				// Category
			WRITE_LONG  0x34 920				// Price
			WRITE_SHORT 0x38 1					// Gwen fix: Stack (for safety!)
			WRITE_SHORT 0x42 40					// Lore to identify
			PATCH_IF (is_tobex) BEGIN
				WRITE_LONG 0x18 THIS | BIT25	// Adds EE/Ex: Toggle critical hits flag
			END
			LPM ~clear~
			SET gradient = 27					// sets colour index 27 GRAY
			SET location = hred					// location (Face)
			LPM ~colour~
			// Gwen wrong coding fixed: parameter2 originally set to 1 should be 0 to match item description (+1 to saving throws).
			PATCH_FOR_EACH op IN 33 34 35 36 37 BEGIN
				LPF ADD_ITEM_EQEFFECT INT_VAR opcode = op target = 1 timing = 2 parameter1 = 1 END
			END
		END
	BUT_ONLY

	// Circlet
	COPY_EXISTING ~amul02.itm~ ~override/xoband01.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400601
			SAY DESC  @400603
			WRITE_ASCII 0x22 ~JB~
			WRITE_ASCII 0x3A ~1BAND02~ #8
			WRITE_ASCII 0x58 ~1CBAND01~ #8
			WRITE_SHORT 0x1c 0x07				// Category
			WRITE_LONG  0x34 12					// Price
			WRITE_SHORT 0x38 1					// Gwen fix: Stack (for safety!)
			PATCH_IF (is_tobex) BEGIN
				WRITE_LONG 0x18 THIS | BIT25	// Adds EE/Ex: Toggle critical hits flag
			END
			LPM ~clear~
			SET gradient = 98					// sets colour index 98 LEAF_GREEN
			SET location = hred					// location (Face)
			LPM ~colour~
		END
	BUT_ONLY

	// Eilistraee's Boon +1
	COPY_EXISTING ~amul02.itm~ ~override/xoband03.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME1 @400601
			SAY NAME2 @400605
			SAY UNIDENTIFIED_DESC @400603
			SAY DESC  @400606
			WRITE_ASCII 0x22 ~JB~
			WRITE_ASCII 0x3A ~1BAND03~ #8
			WRITE_ASCII 0x58 ~1CBAND03~ #8
			WRITE_LONG	0x18 0x6c				// Flags : Droppable - Displayable - Not copyable - Magical
			WRITE_SHORT 0x1c 0x07				// Category
			WRITE_LONG  0x34 2100				// Price
			WRITE_SHORT 0x38 1					// Gwen fix: Stack (for safety!)
			WRITE_SHORT 0x42 85					// Lore to identify
			PATCH_IF (is_tobex) BEGIN
				WRITE_LONG 0x18 THIS | BIT25	// Adds EE/Ex: Toggle critical hits flag
			END
			LPM ~clear~
			SET gradient = 245					// sets colour index 245 MAGE_MAJOR-CHROME_SEA_GRAY
			SET location = hred					// location (Face)
			LPM ~colour~
			// Gwen wrong coding fixed: parameter1 originally set to 110 should be 10, and parameter2 switched from 2 to 0 to match item description (+10% magic damage resistance).
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 31 target = 1 timing = 2 parameter1 = 10 END
			PATCH_FOR_EACH op IN 33 34 35 36 37 BEGIN // wrong coding: +1 to saving throws (parameter2 originally set to 1 should be 0).
				LPF ADD_ITEM_EQEFFECT INT_VAR opcode = op target = 1 timing = 2 parameter1 = 1 END
			END
		END
	BUT_ONLY

	// Circlet of the Archmagi
	COPY_EXISTING ~amul02.itm~ ~override/xoband04.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME1 @400601
			SAY NAME2 @400607
			SAY UNIDENTIFIED_DESC @400603
			SAY DESC  @400608
			WRITE_ASCII 0x22 ~JB~
			WRITE_ASCII 0x3A ~1BAND04~ #8
			WRITE_ASCII 0x58 ~1CBAND04~ #8
			WRITE_LONG	0x18 0x6c				// Flags : Droppable - Displayable - Not copyable - Magical
			WRITE_SHORT 0x1c 0x07				// Category
			WRITE_LONG  0x1e 0x60725ec0			// Usability
			WRITE_LONG  0x34 5100				// Price
			WRITE_SHORT 0x38 1					// Gwen fix: Stack (for safety!)
			WRITE_SHORT 0x42 85					// Lore to identify
			PATCH_IF (is_tobex) BEGIN
				WRITE_LONG 0x18 THIS | BIT25	// Adds EE/Ex: Toggle critical hits flag
			END
			LPM ~clear~
			SET gradient = 228					// sets colour index 228 LEATHER-SPECTRAL_GREEN
			SET location = hred					// location (Face)
			LPM ~colour~
			// Gwen wrong coding fixed: one LPM ADD_ITEM_EQEFFECT was missing.
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 19 target = 1 timing = 2 parameter1 = 1 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 1 END
			// Gwen wrong coding fixed: parameter2 originally set to 1 should be 0 to match item description (+1 to saving throws).
			PATCH_FOR_EACH op IN 33 34 35 36 37 BEGIN
				LPF ADD_ITEM_EQEFFECT INT_VAR opcode = op target = 1 timing = 2 parameter1 = 1 END
			END
		END
	BUT_ONLY

END

// Circlet of Netheril
ACTION_IF (FILE_EXISTS_IN_GAME ~compon17.itm~) BEGIN
	COPY_EXISTING ~compon17.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN		// protects against invalid files
			WRITE_ASCII 0x22 ~JB~				// replaces None
			WRITE_ASCII 0x3A ~1BAND05~ #8		// replaces ICOMPO17
			WRITE_ASCII 0x58 ~1CBAND05~ #8		// replaces PCOMPO17
			WRITE_SHORT 0x38 1					// Gwen fix: Stack (for safety!)
			PATCH_IF (is_tobex) BEGIN
				WRITE_LONG 0x18 THIS | BIT25	// Adds EE/Ex: Toggle critical hits flag
			END
			LPM ~clear~
			SET gradient = 208					// sets colour index 208 ATH_PEASANT_MAJOR-FADED_WHEAT
			SET location = hred					// location (Face)
			LPM ~colour~
		END
	BUT_ONLY
END

// Circlet of Netheril
ACTION_IF (FILE_EXISTS_IN_GAME ~helm28.itm~) BEGIN
	COPY_EXISTING ~helm28.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN		// protects against invalid files
			WRITE_ASCII 0x22 ~JB~				// replaces None
			WRITE_ASCII 0x3A ~1BAND06~ #8		// replaces ICOMPO17
			WRITE_ASCII 0x58 ~1CBAND06~ #8		// replaces PCOMPO17
			WRITE_SHORT 0x38 1					// Gwen fix: Stack (for safety!)
			PATCH_IF (is_tobex) BEGIN
				WRITE_LONG 0x18 THIS | BIT25	// Adds EE/Ex: Toggle critical hits flag
			END
			LPM ~clear~
			SET gradient = 227					// sets colour index 227 METAL_WILD-CORAL
			SET location = hred					// location (Face)
			LPM ~colour~
		END
	BUT_ONLY
END


/* ----------------------- *
 *  Stuff of the Magi mod  *
 * ----------------------- */

// Circlet of the Magi
ACTION_IF (FILE_EXISTS_IN_GAME ~wzrdhelm.itm~) BEGIN
	COPY_EXISTING ~wzrdhelm.itm~ ~override~
		WRITE_ASCII 0x22 ~JB~	// Circlet
		LPF CLONE_EFFECT INT_VAR silent = 1 check_headers = 0 multi_match = 1 match_opcode = 101 opcode = 7 parameter1 = 207 parameter2 = 52 STR_VAR insert = first END	// Set Color: 207 NOBLE_MINOR2-CHROME_GOLD
	BUT_ONLY
END

// END of COMPONENT SECTION