/* ================================================================================================================================================================================ *
 *                                                                                                                                                                                  *
 *                                          C O M P O N E N T   :   C o r e   u p d a t e s   a n d   i t e m   p a t c h e s   ( B G 2 )                                           *
 *                                                                                                                                                                                  *
 * ================================================================================================================================================================================ *
 *  This is where things get... 'interesting'. This is the main 1ppv4 update component.                                                                                             *
 *  (Just a short little thing... right!)                                                                                                                                           *
 * ================================================================================================================================================================================ *
 *  change-log:                                                                                                                                                                     *
 *  -----------                                                                                                                                                                     *
 *      - Variables needed for installation (1pp_forced_item_colours_iwd and 1pp_gemlore) are read from 1pp-config-default.ini or 1pp-config.ini files.                             *
 *        The previous version interrupted installation with plain text prompts allowing players to customise components to their liking (depending on which IE game the mod is     *
 *        installed for and already installed components). All those variables set during installation have been moved into 1pp-config-default.ini file in 1pp folder. This file    *
 *        provides a standard installation. If players want to define their own customized installation, they have to modify the variables involved in 1pp-config-default.ini and   *
 *        save this file as 1pp-config.ini. The installation process will read both ini files and prioritize user values. If a value is not set or mismatched in 1pp-config.ini,    *
 *        the installation process will prevent any installation failure by reverting it back to its default value.                                                                 *
 *      - Gems sub-component (#989) : code simplified and re-written to avoid overwriting files when selecting option no lore needed for identification (1pp_gemlore = 2). Builds  *
 *        an array to define new gems lore values to identify. Same tph used for IWD and BG2 games.                                                                                *
 *      - Replace macros with functions whenever possible.                                                                                                                          *
 *      - Coding simplification:                                                                                                                                                    *
 *          Replaced WRITE_LONG 0x3E 0 and WRITE_ASCII 0x3A ~ISHLDS01~ with WRITE_ASCII 0x3A ~ISHLDS01~ #8. Id. with offsets 0x48 0x44, and 0x5C 0x58.                              *
 *          Grouped actions or patches with ACTION_FOR_EACH and PATCH_FOR_EACH whenever possible.                                                                                   *
 * ================================================================================================================================================================================ */

/* ============================= *
 *                               *
 *         BEGIN INSTALL         *
 *                               *
 * ============================= */

PRINT @400001 // ~Copying resources...~
SILENT

ACTION_FOR_EACH resource IN ~gbow02~ ~gbshld~ ~glshld~ ~gmshld~ ~gquiver0~ ~gsshld~ ~1helm00~ ~1helm03~ ~1helm04~ ~1helm06~ ~1helm17~ ~1helm18~ ~1helm20~ ~idart01~ BEGIN
	COPY ~1pp/item/1ppv4_update/bam/%resource%.bam~ ~override~
END

COPY ~1pp/additions/carried_1pp~ ~override~ // ~1chelm01~ ~1chelm02~ ~1chelm03~ ~1chelm04~ ~1chelm05~ ~1chelm06~ ~1chelm07~


/* ========= *
 *  SHIELDS  *
 * ========= */

PRINT @400012 // ~Patching shields...~
SILENT

// Small Shield
ACTION_IF (FILE_EXISTS_IN_GAME ~shld01.itm~) BEGIN
	COPY_EXISTING ~shld01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			SET gradient = 22			// sets colour index 22 DARK_BROWN
			SET location = sred			// location (Grip)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 92		// sets colour index 92 LIGHT_CHOCOLATE
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Small Shield +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld02.itm~) BEGIN
	COPY_EXISTING ~shld02.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			SET gradient = 109			// sets colour index 109 TERRA_COTTA
			SET location = sred			// location (Grip)
			LPM ~colour~
		END
	BUT_ONLY
END

// Medium Shield
ACTION_IF (FILE_EXISTS_IN_GAME ~shld03.itm~) BEGIN
	COPY_EXISTING ~shld03.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 94			// sets colour index 94 RHUBARB
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 100			// sets colour index 100 DARK_ASH_GRAY
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 215			// 215 GYPSY_MINOR-CHROME_VERMILLION replaces colour index 70 LIGHT_METALLIC_RED
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 66		// sets colour index 66 FADED_BLACK
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Medium Shield +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld04.itm~) BEGIN
	COPY_EXISTING ~shld04.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 81			// sets colour index 81 FADED_GOLD
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 250			// 250 SHADOW_DRUID_MAJOR-YELLOW_ORANGE replaces colour index 99 GOLDEN_BROWN
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			SET gradient = 98			// 98 LEAF_GREEN replaces colour index 30 LIGHT_IRON_GRAY
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 160			// sets colour index 160 DEEP_BROWN
			SET location = spink		// location (Panel)
			LPM ~colour~
		END
	BUT_ONLY
END

// Large Shield
ACTION_IF (FILE_EXISTS_IN_GAME ~shld05.itm~) BEGIN
	COPY_EXISTING ~shld05.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 91			// sets colour index 91 DARK_CHOCOLATE
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 6			// 6 DARK_SILVER replaces colour index 28 BLUISH_SILVER
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 26			// 26 WOOD replaces colour index 111 BURNT_SIENNA
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 87		// sets colour index 87 SADDLE_BROWN
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Large Shield +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld06.itm~) BEGIN
	COPY_EXISTING ~shld06.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 99			// sets colour index 99 GOLDEN_BROWN
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 30			// sets colour index 30 LIGHT_IRON_GRAY
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 112			// 112 SEA_FOAM replaces colour index 7 LIGHT_METALLIC_GREEN
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			SET gradient = 237			// 237 CLERIC_NEUTRAL_MAJOR-TAUPE replaces colour index 8 DARK_MUDDISH_BROWN
			SET location = spink		// location (Panel)
			LPM ~colour~
		END
	BUT_ONLY
END

// Large Shield +1, +4 vs. Missiles
ACTION_IF (FILE_EXISTS_IN_GAME ~shld07.itm~) BEGIN
	COPY_EXISTING ~shld07.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 3			// sets colour index 3 LIGHT_GOLD
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 16			// 16 SILVERISH_GOLD replaces colour index 25 DARK_PURE_GOLD
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 208			// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 25 DARK_PURE_GOLD
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			SET gradient = 66			// sets colour index 66 FADED_BLACK
			SET location = spink		// location (Panel)
			LPM ~colour~
		END
	BUT_ONLY
END

// Bucklers
ACTION_IF (FILE_EXISTS_IN_GAME ~shld08.itm~) BEGIN
	COPY_EXISTING ~shld08.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 27			// sets colour index 27 GRAY
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 28			// sets colour index 28 BLUISH_SILVER
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 30			// sets colour index 30 LIGHT_IRON_GRAY
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 92		// sets colour index 92 LIGHT_CHOCOLATE
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld09.itm~) BEGIN
	COPY_EXISTING ~shld09.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 209			// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 22			// sets colour index 22 DARK_BROWN
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 23			// sets colour index 23 LIGHT_COPPER
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 209		// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld10.itm~) BEGIN
	COPY_EXISTING ~shld10.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 26			// sets colour index 26 WOOD
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 28			// sets colour index 28 BLUISH_SILVER
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 26			// sets colour index 26 WOOD
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 179		// sets colour index 179 PALE_INDIGO
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Small Shields
ACTION_IF (FILE_EXISTS_IN_GAME ~shld11.itm~) BEGIN
	COPY_EXISTING ~shld11.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 81			// sets colour index 81 FADED_GOLD
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 28			// sets colour index 28 BLUISH_SILVER
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 30			// 30 LIGHT_IRON_GRAY sets colour index 30 LIGHT_IRON_GRAY
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 188		// sets colour index 188 MEDIUM_GRAY
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld12.itm~) BEGIN
	COPY_EXISTING ~shld12.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 72			// sets colour index 72 STEEL_GRAY
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 27			// sets colour index 27 GRAY
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 30			// sets colour index 30 LIGHT_IRON_GRAY
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 99		// sets colour index 99 GOLDEN_BROWN
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Medium shields
ACTION_IF (FILE_EXISTS_IN_GAME ~shld13.itm~) BEGIN
	COPY_EXISTING ~shld13.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 174			// sets colour index 174 PALE_SLATE
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 100			// sets colour index 100 DARK_ASH_GRAY
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 176			// 176 STEEL_BLUE replaces colour index 59 LIGHT_PURPLE
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 183		// sets colour index 183 CHARCOAL
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld14.itm~) BEGIN
	COPY_EXISTING ~shld14.itm~ ~override/shld14A.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 92			// sets colour index 92 LIGHT_CHOCOLATE
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 30			// sets colour index 30 LIGHT_IRON_GRAY
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 242			// 242 THIEF_MINOR-PALE_OLIVE replaces colour index 10 LIGHT_PURE_GOLD
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 39		// sets colour index 39 DARK_DIRT_BROWN
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Large Shields
ACTION_IF (FILE_EXISTS_IN_GAME ~shld15.itm~) BEGIN
	COPY_EXISTING ~shld15.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 92			// sets colour index 92 LIGHT_CHOCOLATE
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 27			// sets colour index 27 GRAY
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 215			// 215 GYPSY_MINOR-CHROME_VERMILLION replaces colour index 19 DARK_ROSE_RED
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 254		// sets colour index 254 EBONY
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld16.itm~) BEGIN
	COPY_EXISTING ~shld16.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 100			// sets colour index 100 DARK_ASH_GRAY
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 248			// 248 OGRE_MAJOR-BATTLESHIP_GRAY replaces colour index 28 BLUISH_SILVER
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 109			// 109 TERRA_COTTA replaces colour index 19 DARK_ROSE_RED
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 238		// sets colour index 238 CLERIC_NEUTRAL_MINOR-RUSSET_BROWN
				SET location = spink	// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Gwen: does not exist in the game?
ACTION_IF (FILE_EXISTS_IN_GAME ~shld17.itm~) BEGIN
	COPY_EXISTING ~shld17.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 66			// sets colour index 66 FADED_BLACK
			SET location = sred			// location (Grip)
			LPM ~colour~
			SET gradient = 90			// sets colour index 90 MOLDY_GOLD
			SET location = sblue		// location (Body/trim)
			LPM ~colour~
			SET gradient = 208			// sets colour index 208 ATH_PEASANT_MAJOR-FADED_WHEAT
			SET location = sgrey		// location (Hub)
			LPM ~colour~
			SET gradient = 66			// sets colour index 66 FADED_BLACK
			SET location = spink		// location (Panel)
			LPM ~colour~
		END
	BUT_ONLY
END


/* ------------------------------------------------------------------ *
 *  Content related to Additional Shield Animations (core) component  *
 * ------------------------------------------------------------------ */

ACTION_IF (MOD_IS_INSTALLED ~1pp.tp2~ 206) BEGIN

PRINT @400081 // ~Patching content related to additional shield animations component...~
SILENT

	// The Bitch Queen's Envoy
	ACTION_IF (FILE_EXISTS_IN_GAME ~shldbch.itm~) BEGIN
		COPY_EXISTING ~shldbch.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
				WRITE_ASCII 0x22 ~C5~			// replaces D3 Medium shield
				WRITE_ASCII 0x44 ~GLSHLD~ #8	// replaces GSHLD01
				LPM ~clear~
				SET gradient = 236				// 236 CLERIC_GOOD_MINOR-DARK_PINE replaces colour index 15 PASTEL_GREEN
				SET location = sgrey			// location (Hub)
				LPM ~colour~
				SET gradient = 105				// 105 OFF_WHITE replaces colour index 57 LIGHT_BLUE
				SET location = steal			// location (Interior)
				LPM ~colour~
				SET gradient = 220				// 220 ELF_MAJOR-MIDNIGHT_BLUE replaces colour index 57 LIGHT_BLUE
				SET location = spink			// location (Panel)
				LPM ~colour~
				SET gradient = 220				// 220 ELF_MAJOR-MIDNIGHT_BLUE replaces colour index 0 RUST-TINTED_BLACK
				SET location = sblue			// location (Body/trim)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// The Red Knight's Shield
	ACTION_IF (FILE_EXISTS_IN_GAME ~shldred.itm~) BEGIN
		COPY_EXISTING ~shldred.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
				WRITE_ASCII 0x22 ~C5~			// replaces D3 Medium shield
				WRITE_ASCII 0x44 ~GLSHLD~ #8	// replaces GSHLD03
				LPM ~clear~
				SET gradient = 249				// 249 OGRE_MINOR-METALLIC_SLATE replaces colour index 101 METALLIC_RED
				SET location = sgrey			// location (Hub)
				LPM ~colour~
				SET gradient = 99				// 99 GOLDEN_BROWN replaces colour index 47 PURE_DARK_RED
				SET location = steal			// location (Interior)
				LPM ~colour~
				SET gradient = 195				// 195 CHROME_RED replaces colour index 47 PURE_DARK_RED
				SET location = spink			// location (Panel)
				LPM ~colour~
				SET gradient = 99				// 99 GOLDEN_BROWN replaces colour index 43 DARK_BEIGE
				SET location = sblue			// location (Body/trim)
				LPM ~colour~
			END
		BUT_ONLY
	END

END

/* ================================================================== *
 *  Content related to Additional Helmet Animations (core) component  *
 * ================================================================== */
ACTION_IF (MOD_IS_INSTALLED ~1pp.tp2~ 208) BEGIN

	PRINT @400082 // ~Installing helmet compatibility...~
	SILENT

	ACTION_FOR_EACH set IN ~h0~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%j6%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~h1~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%j7%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~h2~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%j8%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~h3~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%j9%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~h4~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%j8%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

	ACTION_FOR_EACH set IN ~h5~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~n~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a2~ ~a3~ ~a4~ ~a5~ ~a6~ ~a7~ ~a8~ ~a9~ ~ca~ ~g1~ ~sa~ ~ss~ ~sx~ BEGIN
				COPY_EXISTING ~wq%category%ja%sequence%.bam~ ~override/wq%category%%set%%sequence%.bam~
			END
		END
	END

	PRINT @400083 // ~Patching content related to additional helmet animations component...~
	SILENT

	// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm01.itm~) BEGIN
		COPY_EXISTING ~helm01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H0~			// replaces H0
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 42 BEIGE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// 27 GRAY replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 27				// 27 GRAY replaces colour index 42 BEIGE
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet of Opposite Alignment
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm02.itm~) BEGIN
		COPY_EXISTING ~helm02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// replaces H4
				WRITE_ASCII 0x3A ~1HELM06~ #8	// replaces IHELM04
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// replaces CHELM02
				LPM ~clear~
				SET gradient = 249				// 249 OGRE_MINOR-METALLIC_SLATE replaces colour index 97 LIGHT_MINTY_BLUE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helm of Glory
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm03.itm~) BEGIN
		COPY_EXISTING ~helm03.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H2~			// replaces H2
				//WRITE_ASCII 0x3A ~1HELM06~ #8
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 224				// 224 DROW_MAJOR-MAIZE replaces colour index 25 DARK_PURE_GOLD
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 90				// 90 MOLDY_GOLD replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 30				// 30 LIGHT_IRON_GRAY replaces colour index 27 GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 30				// sets colour index 30 LIGHT_IRON_GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 30				// sets colour index 30 LIGHT_IRON_GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet of Defense
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm04.itm~) BEGIN
		COPY_EXISTING ~helm04.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H5~			// replaces H5
				//WRITE_ASCII 0x3A ~1HELM06~ #8
				WRITE_ASCII 0x58 ~1CHELM04~ #8	// replaces CHELM04
				LPM ~clear~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 59 LIGHT_PURPLE
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 5				// sets colour index 5 MEDIUM_SILVER
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 5				// sets colour index 5 MEDIUM_SILVER
				SET location = hpink			// location (Plume)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet of Infravision
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm05.itm~) BEGIN
		COPY_EXISTING ~helm05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM20~ #8	// replaces IHELM05
				WRITE_ASCII 0x58 ~1CHELM02~ #8	// replaces CHELM05
				LPM ~clear~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 99				// sets colour index 99 GOLDEN_BROWN
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 195				// sets colour index 195 CHROME_RED
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 210				// sets colour index = 210 MERCHANT_MAJOR-AMBER 
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmet of Charm Protection
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm06.itm~) BEGIN
		COPY_EXISTING ~helm06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// replaces H3
				WRITE_ASCII 0x3A ~1HELM18~ #8	// replaces IHELM03
				WRITE_ASCII 0x58 ~1CHELM02~ #8	// replaces CHELM06
				LPM ~clear~
				SET gradient = 0				// 0 RUST-TINTED_BLACK replaces colour index 39 DARK_DIRT_BROWN
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 119				// sets colour index 119 DARKEST_ORCHID
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 118				// sets colour index 118 DARKER_ORCHID
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
				END
		BUT_ONLY
	END

	// Helm of Balduran
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm07.itm~) BEGIN
		COPY_EXISTING ~helm07.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// replaces H1
				WRITE_ASCII 0x3A ~1HELM00~ #8	// replaces IHELM01
				WRITE_ASCII 0x58 ~CHELM07~ #8	// replaces CHELM07
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 42 BEIGE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hpink			// location (Plume)
				LPM ~colour~
				SET gradient = 66				// 66 FADED_BLACK replaces colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 173				// sets colour index 173 MOSSY_GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

	// Helmets
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm08.itm~) BEGIN
		COPY_EXISTING ~helm08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// replaces H4
				WRITE_ASCII 0x3A ~1HELM03~ #8	// replaces IHELM04
				LPM ~clear~
				SET gradient = 119				// 119 DARKEST_ORCHID replaces colour index 25 DARK_PURE_GOLD
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 205				// 205 NOBLE_MINOR2-CHROME_GRAY replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 209				// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 102				// sets colour index 102 SEA_BLUE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 0			// sets colour index 0 RUST-TINTED_BLACK
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm09.itm~) BEGIN
		COPY_EXISTING ~helm09.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H3~			// replaces H3
				//WRITE_ASCII 0x3A ~1HELM03~ #8
				WRITE_ASCII 0x58 ~1CHELM06~ #8	// replaces CHELM06
				LPM ~clear~
				SET gradient = 27				// 27 GRAY replaces colour index 39 DARK_DIRT_BROWN
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hteal			// location (Detail)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 195			// sets colour index 195 CHROME_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm10.itm~) BEGIN
		COPY_EXISTING ~helm10.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H5~			// replaces H5
				//WRITE_ASCII 0x3A ~1HELM03~ #8
				WRITE_ASCII 0x58 ~1CHELM05~ #8	// replaces CHELM05
				LPM ~clear~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 47			// sets colour index 47 PURE_DARK_RED
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 127			// sets colour index 127 DARK_BRICK_RED
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm11.itm~) BEGIN
		COPY_EXISTING ~helm11.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM04~ #8	// replaces IHELM05
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// replaces CHELM05
				LPM ~clear~
				SET gradient = 248				// 248 OGRE_MAJOR-BATTLESHIP_GRAY replaces colour index 104 DARK_CHROME_PURPLE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 104 DARK_CHROME_PURPLE
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 202			// sets colour index 202 HAIR2-LIBERTY_BLUE
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 202			// sets colour index 202 HAIR2-LIBERTY_BLUE
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm12.itm~) BEGIN
		COPY_EXISTING ~helm12.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// replaces H2
				WRITE_ASCII 0x3A ~IHELM04~ #8	// replaces IHELM02
				WRITE_ASCII 0x58 ~1CHELM02~ #8	// replaces CHELM03
				LPM ~clear~
				SET gradient = 235				// 235 CLERIC_GOOD_MAJOR-GLAUCOUS_GRAY replaces colour index 24 BROWN_GOLD
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 24 BROWN_GOLD
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 102				// 102 SEA_BLUE replaces colour index 24 BROWN_GOLD
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 232			// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
					SET location = hpink		// location (Plume)
					LPM ~colour~
					SET gradient = 232			// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
					SET location = hteal		// location (Detail)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm13.itm~) BEGIN
		COPY_EXISTING ~helm13.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// replaces H5
				WRITE_ASCII 0x3A ~1HELM17~ #8	// replaces IHELM05
				WRITE_ASCII 0x58 ~CHELM06~ #8	// replaces CHELM05
				LPM ~clear~
				SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 94 RHUBARB
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 27				// 27 GRAY replaces colour index 94 RHUBARB
				SET location = hteal			// location (Detail)
				LPM ~colour~
				SET gradient = 27				// 27 GRAY replaces colour index 94 RHUBARB
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 224				// sets colour index 224 DROW_MAJOR-MAIZE
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 195			// 195 CHROME_RED replaces colour index 94 RHUBARB
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helmblk.itm~) BEGIN
		COPY_EXISTING ~helmblk.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H4~			// replaces H4
				LPM ~clear~
				SET gradient = 254				// 254 EBONY replaces colour index 21 DARK_IRON_GRAY
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 248				// 248 OGRE_MAJOR-BATTLESHIP_GRAY sets colour index 248 OGRE_MAJOR-BATTLESHIP_GRAY
				SET location = hteal			// location (Detail)
				LPM ~colour~
				SET gradient = 191				// 191 VIRIDIAN_GRAY replaces colour index 21 DARK_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 254				// 254 EBONY replaces colour index 21 DARK_IRON_GRAY
				SET location = hred				// location (Face)
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 136			// sets colour index
					SET location = hpink		// location (Plume)
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	// Dead Man's Face
	ACTION_IF (FILE_EXISTS_IN_GAME ~helmded.itm~) BEGIN
		COPY_EXISTING ~helmded.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replaces H2
				LPM ~clear~
				SET gradient = 254				// 254 EBONY replaces colour index 42 BEIGE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 43 DARK_BEIGE
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 239				// sets colour index 239 CLERIC_EVIL_MAJOR-PALE_BRONZ
				SET location = hred				// location (Face)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Blessed Helm of Lathander
	ACTION_IF (FILE_EXISTS_IN_GAME ~helmla.itm~) BEGIN
		COPY_EXISTING ~helmla.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J6~			// Replaces H0
				LPM ~clear~
				SET gradient = 2				// 2 DARK_GOLD replaces colour index 42 BEIGE
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 127				// sets colour index 127 DARK_BRICK_RED
				SET location = hteal			// location (Detail)
				LPM ~colour~
				SET gradient = 92				// 92 LIGHT_CHOCOLATE replaces colour index 98 LEAF_GREEN
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 91				// 91 DARK_CHOCOLATE replaces colour index 42 BEIGE
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 127				// sets colour index 127 DARK_BRICK_RED
				SET location = hpink			// location (Plume)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Helm of Shouting
	ACTION_IF (FILE_EXISTS_IN_GAME ~helmsh.itm~) BEGIN
		COPY_EXISTING ~helmsh.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// replaces H0
				LPM ~clear~
				SET gradient = 25				// 25 DARK_PURE_GOLD replaces colour index 99 GOLDEN_BROWN
				SET location = hgrey			// location (Wings)
				LPM ~colour~
				SET gradient = 66				// sets colour index 66 FADED_BLACK
				SET location = hteal			// location (Detail)
				LPM ~colour~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 30 LIGHT_IRON_GRAY
				SET location = hblue			// location (Exterior)
				LPM ~colour~
				SET gradient = 249				// 249 OGRE_MINOR-METALLIC_SLATE replaces colour index 99 GOLDEN_BROWN
				SET location = hred				// location (Face)
				LPM ~colour~
				SET gradient = 127				// sets colour index 127 DARK_BRICK_RED
				SET location = hpink			// location (Plume)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Sune's Laurel of Favor
	ACTION_IF (FILE_EXISTS_IN_GAME ~helmsun.itm~) BEGIN
		COPY_EXISTING ~helmsun.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JB~			// replaces None
				LPM ~clear~
				SET gradient = 201				// sets colour index 201 SKIN1-AVOCADO
				SET location = hred				// location (Face)
				LPM ~colour~
			END
		BUT_ONLY
	END

END // HELMETS END


/* ====== *
 *  GEMS  *
 * ====== */

INCLUDE ~%MOD_FOLDER%/components/400_update_gemlore.tpa~


/* =========== *
 *  LAUNCHERS  *
 * =========== */

PRINT @400041 // ~Patching slings...~
SILENT

// Sling
ACTION_IF (FILE_EXISTS_IN_GAME ~slng01.itm~) BEGIN
	COPY_EXISTING ~slng01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~SL~
			LPM ~clear~
			SET gradient = 99				// 99 GOLDEN_BROWN replaces colour index 22 DARK_BROWN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 91				// sets colour index 91 DARK_CHOCOLATE
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Sling +1
ACTION_IF (FILE_EXISTS_IN_GAME ~slng02.itm~) BEGIN
	COPY_EXISTING ~slng02.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~SL~
			LPM ~clear~
			SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 28 BLUISH_SILVER
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 90				// sets colour index 90 MOLDY_GOLD
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Edley's Sling
 ACTION_IF (FILE_EXISTS_IN_GAME ~slinged.itm~) BEGIN
	COPY_EXISTING ~slinged.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~SL~
			LPM ~clear~
			SET gradient = 240				// 240 CLERIC_EVIL_MINOR-PALE_RUST replaces colour index 22 DARK_BROWN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 238				// sets colour index 238 CLERIC_NEUTRAL_MINOR-RUSSET_BROWN
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Heavy Crossbow
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow01.itm~) BEGIN
	COPY_EXISTING ~xbow01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 6				// 6 DARK_SILVER replaces colour index 27 GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 92				// 92 LIGHT_CHOCOLATE replaces colour index 40 DARK_DIRTY_COPPER
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 28				// sets colour index 28 BLUISH_SILVER
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Heavy Crossbow +1
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow02.itm~) BEGIN
	COPY_EXISTING ~xbow02.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 159				// 159 MAUVE replaces colour index 31 LIGHT_SEA_BLUE
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 27				// sets colour index 27 GRAY
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 27 GRAY
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Heavy Crossbow of Accuracy 
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow03.itm~) BEGIN
	COPY_EXISTING ~xbow03.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 83				// 83 DARK_BLUISH_GRAY replaces colour index 25 DARK_PURE_GOLD
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 240				// 240 CLERIC_EVIL_MINOR-PALE_RUST replaces colour index 29 RED-TINTED_BLACK
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 25				// sets colour index 25 DARK_PURE_GOLD
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Light Crossbow
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow04.itm~) BEGIN
	COPY_EXISTING ~xbow04.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 27				// sets colour index 27 GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 99				// 99 GOLDEN_BROWN replaces colour index 9 LIGHT_MUDDISH_BROWN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 10				// sets colour index 10 LIGHT_PURE_GOLD
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Light Crossbow +1
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow05.itm~) BEGIN
	COPY_EXISTING ~xbow05.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 138				// 138 DARK_SAND replaces colour index 27 GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 184				// 184 CADET_BLUE replaces colour index 27 GRAY
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 27				// sets colour index 27 GRAY
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Light Crossbow of Speed 
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow06.itm~) BEGIN
	COPY_EXISTING ~xbow06.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 91				// 91 DARK_CHOCOLATE replaces colour index 100 DARK_ASH_GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 27 GRAY
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 248				// 248 OGRE_MAJOR-BATTLESHIP_GRAY replaces colour index 30 LIGHT_IRON_GRAY
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END


/* ======================================================================== *
 *  Content related to Increased paperdoll object variety (core) component  *
 * ======================================================================== */

ACTION_IF (MOD_IS_INSTALLED ~1pp.tp2~ 210) BEGIN

	PRINT @400084 // ~Patching content related to Increased paperdoll object variety...~
	SILENT

	// Amaunator's Legacy
	ACTION_IF (FILE_EXISTS_IN_GAME ~amaunat.itm~) BEGIN
		COPY_EXISTING ~amaunat.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Bastard Sword 
	ACTION_IF (FILE_EXISTS_IN_GAME ~ranbswd.itm~) BEGIN
		COPY_EXISTING ~ranbswd.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// The Snow Maiden's Reaver
	ACTION_IF (FILE_EXISTS_IN_GAME ~reaver.itm~) BEGIN
		COPY_EXISTING ~reaver.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces FS Flaming sword
			END
		BUT_ONLY
	END

	// Fang
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd1a.itm~) BEGIN
		COPY_EXISTING ~ubswd1a.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Phasing Bastard Sword +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd2a.itm~) BEGIN
		COPY_EXISTING ~ubswd2a.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Flaming Bastard Sword +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd2b.itm~) BEGIN
		COPY_EXISTING ~ubswd2b.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Bastard Sword +2: Life Giver
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd3a.itm~) BEGIN
		COPY_EXISTING ~ubswd3a.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Bastard Sword of Action +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd3b.itm~) BEGIN
		COPY_EXISTING ~ubswd3b.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword	
			END
		BUT_ONLY
	END

	// Bastard Sword +3: Defender
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd4a.itm~) BEGIN
		COPY_EXISTING ~ubswd4a.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Bastard Sword of Greater Phasing
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd4b.itm~) BEGIN
		COPY_EXISTING ~ubswd4b.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Bastard Sword +2: Conflagration
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd4c.itm~) BEGIN
		COPY_EXISTING ~ubswd4c.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Cancerous Bastard Sword +4
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd5a.itm~) BEGIN
		COPY_EXISTING ~ubswd5a.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Bastard Sword +3: Incinerator
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd5b.itm~) BEGIN
		COPY_EXISTING ~ubswd5b.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Trollslayer
	ACTION_IF (FILE_EXISTS_IN_GAME ~zzg7ts.itm~) BEGIN
		COPY_EXISTING ~zzg7ts.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces FS Flaming sword
			END
		BUT_ONLY
	END

	// The Blade of Bael
	ACTION_IF (FILE_EXISTS_IN_GAME ~bael.itm~) BEGIN
		COPY_EXISTING ~bael.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Cynicism
	ACTION_IF (FILE_EXISTS_IN_GAME ~cynicis.itm~) BEGIN
		COPY_EXISTING ~cynicis.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Erevain's Broad Sword
	ACTION_IF (FILE_EXISTS_IN_GAME ~erevain.itm~) BEGIN
		COPY_EXISTING ~erevain.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Dead God's Dreaming
	ACTION_IF (FILE_EXISTS_IN_GAME ~zz36dgd.itm~) BEGIN
		COPY_EXISTING ~zz36dgd.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Hell's Bane
	ACTION_IF (FILE_EXISTS_IN_GAME ~zzc8hb.itm~) BEGIN
		COPY_EXISTING ~zzc8hb.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// High Quality Short Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~hqsbow.itm~) BEGIN
		COPY_EXISTING ~hqsbow.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - replaces BW Long bow
			END
		BUT_ONLY
	END

	// Short Bow of Ebullience
	ACTION_IF (FILE_EXISTS_IN_GAME ~sbowebu.itm~) BEGIN
		COPY_EXISTING ~sbowebu.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - replaces BW Long bow
			END
		BUT_ONLY
	END

	// Storm Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~storm.itm~) BEGIN
		COPY_EXISTING ~storm.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - replaces BW Long bow
			END
		BUT_ONLY
	END

	// Bastard Sword
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h01.itm~) BEGIN
		COPY_EXISTING ~sw1h01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
				LPM ~clear~
				SET gradient = 99				// sets colour index 99 GOLDEN_BROWN
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 248				// 248 OGRE_MAJOR-BATTLESHIP_GRAY replaces colour index 5 MEDIUM_SILVER
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 94				// sets colour index 94 RHUBARB
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// High Quality Bastard Sword
	ACTION_IF (FILE_EXISTS_IN_GAME ~hqbswrd.itm~) BEGIN
		COPY_EXISTING ~hqbswrd.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
			END
		BUT_ONLY
	END

	// Bastard Sword +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h02.itm~) BEGIN
		COPY_EXISTING ~sw1h02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
				LPM ~clear~
				SET gradient = 50				// sets colour index 50 DARK_YELLOW
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 97 LIGHT_MINTY_BLUE
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 230				// KOBOLD_MAJOR-DEEP_AVOCADO replaces colour index 93 DARK_CEMENT_GRAY
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Bastard Sword +1, +3 vs. Shapeshifters
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h03.itm~) BEGIN
		COPY_EXISTING ~sw1h03.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - replaces S1 Long sword
				LPM ~clear~
				SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 60 DARK_PURPLE
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 231				// 231 KOBOLD_MINOR-CHROME_COOL_GRAY replaces colour index 59 LIGHT_PURPLE
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 183				// 183 CHARCOAL replaces colour index 45 DARK_MAGENTA
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Long Sword
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h04.itm~) BEGIN
		COPY_EXISTING ~sw1h04.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 99				// sets colour index 99 GOLDEN_BROWN
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 248				// 248 OGRE_MAJOR-BATTLESHIP_GRAY replaces colour index 5 MEDIUM_SILVER
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 22				// sets colour index 22 DARK_BROWN
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Long Sword +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h05.itm~) BEGIN
		COPY_EXISTING ~sw1h05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 6				// sets colour index 6 DARK_SILVER
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 110				// 110 ASH replaces colour index 27 GRAY
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 94				// sets colour index 94 RHUBARB
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Long Sword +2
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h06.itm~) BEGIN
		COPY_EXISTING ~sw1h06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 207				// 207 NOBLE_MINOR2-CHROME_GOLD replaces colour index 50 DARK_YELLOW
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 254				// 254 EBONY replaces colour index 6 DARK_SILVER
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 93				// sets colour index 93 DARK_CEMENT_GRAY
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Short Sword +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h08.itm~) BEGIN
		COPY_EXISTING ~sw1h08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 245				// 245 MAGE_MAJOR-CHROME_SEA_GRAY replaces colour index 27 GRAY
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 138				// 138 DARK_SAND replaces colour index 74
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Short Sword +2
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h09.itm~) BEGIN
		COPY_EXISTING ~sw1h09.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 90				// 90 MOLDY_GOLD replaces colour index 99 GOLDEN_BROWN
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 93				// sets colour index 93 DARK_CEMENT_GRAY
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Short Sword of Backstabbing
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h10.itm~) BEGIN
		COPY_EXISTING ~sw1h10.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET setr = 37					// 37 DARK_DIRTY_YELLOW replaces colour index 57 LIGHT_BLUE
				SET setg = 0
				SET setb = 0
				SET speed = 0x2d
				SET location = wblue			// location (Head/Blade minor)
				LPM ~pulse~
				SET gradient = 29				// sets colour index 29 RED-TINTED_BLACK
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 6				// sets colour index 6 DARK_SILVER
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
				SET gradient = 195				// 195 CHROME_RED replaces colour index 76 SOLID_RED
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Composite Long Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow01.itm~) BEGIN
		COPY_EXISTING ~bow01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				//WRITE_ASCII 0x22 ~BW~
				LPM ~clear~
				SET gradient = 13				// sets colour index 13 LIGHT_PINKISH_SILVER
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 95				// sets colour index 95 LIGHT_DIRTISH_BROWN
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 164				// sets colour index 164 RAW_UMBER
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Composite Long Bow +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow02.itm~) BEGIN
		COPY_EXISTING ~bow02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				//WRITE_ASCII 0x22 ~BW~
				LPM ~clear~
				SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 240				// 240 CLERIC_EVIL_MINOR-PALE_RUST replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 174				// sets colour index 174 PALE_SLATE
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Long Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow03.itm~) BEGIN
		COPY_EXISTING ~bow03.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				//WRITE_ASCII 0x22 ~BW~
				LPM ~clear~
				SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 85 PURE_GOLD
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 95				// sets colour index 95 LIGHT_DIRTISH_BROWN
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 90				// sets colour index 90 MOLDY_GOLD
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Long Bow +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow04.itm~) BEGIN
		COPY_EXISTING ~bow04.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				//WRITE_ASCII 0x22 ~BW~
				LPM ~clear~
				SET gradient = 228				// 228 LEATHER-SPECTRAL_GREEN replaces colour index 65 REALLY_DARK_GRAY
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 65 REALLY_DARK_GRAY
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 90				// sets colour index 90 MOLDY_GOLD
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Short Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow05.itm~) BEGIN
		COPY_EXISTING ~bow05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - replaces BW Long bow
				WRITE_ASCII 0x44 ~GBOW02~ #8	// replaces GBOW01
				LPM ~clear~
				SET gradient = 13				// sets colour index 13 LIGHT_PINKISH_SILVER
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 95				// sets colour index 95 LIGHT_DIRTISH_BROWN
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 237				// 237 CLERIC_NEUTRAL_MAJOR-TAUPE replaces colour index 95 LIGHT_DIRTISH_BROWN
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Short Bow +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow06.itm~) BEGIN
		COPY_EXISTING ~bow06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - replaces BW Long bow
				WRITE_ASCII 0x3A ~IBOW06~ #8
				WRITE_ASCII 0x44 ~GBOW02~ #8	// replaces GBOW01
				WRITE_ASCII 0x76 ~IBOW06~ #8
				LPM ~clear~
				SET gradient = 13				// 13 LIGHT_PINKISH_SILVER replaces colour index 75 SOLID_BLACK
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 238				// 238 CLERIC_NEUTRAL_MINOR-RUSSET_BROWN replaces colour index 29 RED-TINTED_BLACK
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 172				// sets colour index 172 PALE_GOLD
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Long Bow of Marksmanship
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow07.itm~) BEGIN
		COPY_EXISTING ~bow07.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				//WRITE_ASCII 0x22 ~BW~
				LPM ~clear~
				SET gradient = 222				// 222 DROW_HAIR-PLATINUM_GRAY replaces colour index 61 LAVENDER
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 6				// 6 DARK_SILVER replaces colour index 61 LAVENDER
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 142				// sets colour index 142 DARK_POWDER_BLUE
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
			END
		BUT_ONLY
	END

	// Eagle Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow08.itm~) BEGIN
		COPY_EXISTING ~bow08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - replaces BW Long bow
				WRITE_ASCII 0x44 ~GBOW02~ #8	// replaces GBOW01
				LPM ~clear~
				SET gradient = 248				// 248 OGRE_MAJOR-BATTLESHIP_GRAY replaces colour index 13 LIGHT_PINKISH_SILVER
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 235				// 235 CLERIC_GOOD_MAJOR-GLAUCOUS_GRAY replaces colour index 59 LIGHT_PURPLE
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 250				// sets colour index 250 SHADOW_DRUID_MAJOR-YELLOW_ORANGE
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
			END
		BUT_ONLY
	END

END // of Increased paperdoll object variety (core) component installed


/* ============= *
 *  AMMUNITIONS  *
 * ============= */

PRINT @400085 // ~Patching ammunitions...~
SILENT

// Bolt
ACTION_IF (FILE_EXISTS_IN_GAME ~bolt01.itm~) BEGIN
	COPY_EXISTING ~bolt01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 27				// sets colour index 27 GRAY
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
		END
	BUT_ONLY
END

// Bolt +1
ACTION_IF (FILE_EXISTS_IN_GAME ~bolt02.itm~) BEGIN
	COPY_EXISTING ~bolt02.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 90				// sets colour index 90 MOLDY_GOLD
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
		END
	BUT_ONLY
END

// Bolt of Lightning
ACTION_IF (FILE_EXISTS_IN_GAME ~bolt03.itm~) BEGIN
	COPY_EXISTING ~bolt03.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 218				// sets colour index 218 ELF_HAIR-CHROME_BLUE_GRAY
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
		END
	BUT_ONLY
END

// Bolt of Biting 
ACTION_IF (FILE_EXISTS_IN_GAME ~bolt04.itm~) BEGIN
	COPY_EXISTING ~bolt04.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 252				// sets colour index 252 DUERGAR_MAJOR-GHOULISH_GREEN
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
		END
	BUT_ONLY
END

// Bolt of Polymorphing
ACTION_IF (FILE_EXISTS_IN_GAME ~bolt05.itm~) BEGIN
	COPY_EXISTING ~bolt05.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 227				// sets colour index 227 METAL_WILD-CORAL
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
		END
	BUT_ONLY
END

// Bolt +2
ACTION_IF (FILE_EXISTS_IN_GAME ~bolt06.itm~) BEGIN
	COPY_EXISTING ~bolt06.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 81				// sets colour index 81 FADED_GOLD
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
		END
	BUT_ONLY
END

// Bullet
ACTION_IF (FILE_EXISTS_IN_GAME ~bull01.itm~) BEGIN
	COPY_EXISTING ~bull01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 27				// sets colour index 27 GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
		END
	BUT_ONLY
END

// Bullet +1
ACTION_IF (FILE_EXISTS_IN_GAME ~bull02.itm~) BEGIN
	COPY_EXISTING ~bull02.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 218				// sets colour index 218 ELF_HAIR-CHROME_BLUE_GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
		END
	BUT_ONLY
END

// Bullet +2
ACTION_IF (FILE_EXISTS_IN_GAME ~bull03.itm~) BEGIN
	COPY_EXISTING ~bull03.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 70				// sets colour index 70 LIGHT_METALLIC_RED
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
		END
	BUT_ONLY
END

// Bullets of Fire +2
ACTION_IF (FILE_EXISTS_IN_GAME ~ubull4a.itm~) BEGIN
	COPY_EXISTING ~Ubull4A.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 115				// sets colour index 115 SUNKISSED
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
		END
	BUT_ONLY
END


ACTION_FOR_EACH resource IN ~ARARROW.BAM~ ~MAGICSTN.BAM~ BEGIN
	COPY ~1pp/additions/projectiles_1pp/%resource%~ ~override~
END


/* =========== *
 *  SCIMITARS  *
 * =========== */

PRINT @400086 // ~Installing scimitar animations and patching items...~
SILENT

ACTION_IF (NOT FILE_EXISTS_IN_GAME ~wplsca1.bam~) BEGIN

	ACTION_FOR_EACH set IN ~sc~ BEGIN
		ACTION_FOR_EACH category IN ~l~ ~m~ ~s~ BEGIN
			ACTION_FOR_EACH sequence IN ~a1~ ~a1e~ ~a3~ ~a3e~ ~a5~ ~a5e~ ~g1~ ~g1e~ ~w2~ ~w2e~ BEGIN
				COPY_EXISTING ~wp%category%s1%sequence%.bam~ ~override/wp%category%%set%%sequence%.bam~
			END
		END
	END

END

// The Lucky Scimitar
ACTION_IF (FILE_EXISTS_IN_GAME ~lucky.itm~) BEGIN
	COPY_EXISTING ~lucky.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - replaces S1 Long sword
		END
	BUT_ONLY
END

// Cradle of Mielikki
ACTION_IF (FILE_EXISTS_IN_GAME ~mielikk.itm~) BEGIN
	COPY_EXISTING ~mielikk.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - replaces S1 Long sword
		END
	BUT_ONLY
END

// Scimitar
ACTION_IF (FILE_EXISTS_IN_GAME ~scimita.itm~) BEGIN
	COPY_EXISTING ~scimita.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - replaces S1 Long sword
		END
	BUT_ONLY
END

// Scimitar +3, Frostbrand
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h15.itm~) BEGIN
	COPY_EXISTING ~sw1h15.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - replaces S1 Long sword
		END
	BUT_ONLY
END

// Talon of the Gloomfrost
ACTION_IF (FILE_EXISTS_IN_GAME ~talongf.itm~) BEGIN
	COPY_EXISTING ~talongf.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - replaces S1 Long sword
		END
	BUT_ONLY
END

// Valiant
ACTION_IF (FILE_EXISTS_IN_GAME ~valiant.itm~) BEGIN
	COPY_EXISTING ~valiant.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - replaces S1 Long sword
		END
	BUT_ONLY
END

// Wind of Heaven
ACTION_IF (FILE_EXISTS_IN_GAME ~zzd5woh.itm~) BEGIN
	COPY_EXISTING ~zzd5woh.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - replaces S1 Long sword
		END
	BUT_ONLY
END

//END of COMPONENT