/* ================================================================================================================================================================================ *
 *                                                                                                                                                                                  *
 *                                C O M P O N E N T   :   C o r e   u p d a t e s   a n d   i t e m   p a t c h e s   (b l u n t    w e a p o n s )                                 *
 *                                                                                                                                                                                  *
 * ================================================================================================================================================================================ *
 *  This part installs blunt weapons stuff (Blunty, the skull that met this!).                                                                                                      *
 * ================================================================================================================================================================================ *
 *  change-log:                                                                                                                                                                     *
 *  -----------                                                                                                                                                                     *
 *      - Variable needed for installation (1pp_sleeper) is read from 1pp-config-default.ini or 1pp-config-user.ini files. This new setting allows to make alternate the turning    *
 *        of The Sleeper into a flail. In any case, 1PP does not overwrite its original inventory bam with a new one, but installs a new icon (IBLUN16B) as an alternate, and       *
 *        saves the vanilla icon for compatibility with other mods purpose.                                                                                                         *
 *        The previous version interrupted installation with plain text prompts allowing players to customise components to their liking (depending on which IE game the mod is     *
 *        installed for and already installed components). All those variables set during installation have been moved into 1pp-config-default.ini file in 1pp folder. This file    *
 *        provides a standard installation. If players want to define their own customized installation, they have to modify the variables involved in 1pp-config-default.ini and   *
 *        save it as 1pp-config-user.ini. The installation process will read both .ini files and prioritize user values. If a value is not set or mismatched in user's file         *
 *        1pp-config-user.ini, the installation process will prevent any installation failure by reverting it back to its default value.                                            *
 *      - Replaced macros with functions whenever possible.                                                                                                                         *
 *      - Coding simplification:                                                                                                                                                    *
 *          Replaced WRITE_LONG 0x3E 0 and WRITE_ASCII 0x3A ~ISHLDS01~ with WRITE_ASCII 0x3A ~ISHLDS01~ #8. Id. with offsets 0x48 0x44, and 0x5C 0x58.                              *
 *          Grouped actions or patches with ACTION_FOR_EACH and PATCH_FOR_EACH whenever possible.                                                                                   *
 *                                                                                                                                                                                  *
 *  specific fixes:                                                                                                                                                                 *
 *  ---------------                                                                                                                                                                 *
 *      - #624  ==> blun16.itm (The Sleeper +2): if turned into a flail, modified minimum strength and damage values and used a new icon (IBLUN16B) to avoid overwriting the        *
 *                  vanilla one (let's keep it for modders!).                                                                                                                       *
 * ================================================================================================================================================================================ */

/* ======================= *
 *  		BLUNT          *
 * ======================= */

PRINT @400053 // ~Patching blunt weapons...~
SILENT

// Club
ACTION_FOR_EACH blunt IN ~blun01~ ~_blun01~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%blunt%.itm~) BEGIN
		COPY_EXISTING ~%blunt%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 22				// sets colour index 22 DARK_BROWN
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 209				// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
				SET location = wpink			// location (Bolt-Mace-Staff)
				LPM ~colour~
				SET gradient = 22				// sets colour index 22 DARK_BROWN
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 163				// replaces colour index 23 LIGHT_COPPER
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
 			END
		BUT_ONLY
	END
END

// Flail +1
ACTION_FOR_EACH blunt IN ~blun03~ ~_blun03~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%blunt%.itm~) BEGIN
		COPY_EXISTING ~%blunt%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 99				// 99 GOLDEN_BROWN replaces colour index 23 LIGHT_COPPER
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 27				// sets colour index 27 GRAY
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
 			END
		BUT_ONLY
	END
END

// Mace +1
ACTION_FOR_EACH blunt IN ~blun05~ ~_blun05~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%blunt%.itm~) BEGIN
		COPY_EXISTING ~%blunt%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 98 LEAF_GREEN
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 91				// 91 DARK_CHOCOLATE replaces colour index 27 GRAY
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 98 LEAF_GREEN
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
 			END
		BUT_ONLY
	END
END

// Kiel's Morning Star
ACTION_FOR_EACH blunt IN ~blun09~ ~_blun09~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%blunt%.itm~) BEGIN
		COPY_EXISTING ~%blunt%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 238				// 238 CLERIC_NEUTRAL_MINOR-RUSSET_BROWN replaces colour index 8 DARK_MUDDISH_BROWN
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 238				// 238 CLERIC_NEUTRAL_MINOR-RUSSET_BROWN replaces colour index 8 DARK_MUDDISH_BROWN
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 239				// 239 CLERIC_EVIL_MAJOR-PALE_BRONZ replaces colour index 4 AUBURN
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
 			END
		BUT_ONLY
	END
END

// The Root of the Problem +1
ACTION_FOR_EACH blunt IN ~blun10~ ~_blun10~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%blunt%.itm~) BEGIN
		COPY_EXISTING ~%blunt%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 22				// sets colour index 22 DARK_BROWN
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 230				// sets colour index 230 KOBOLD_MAJOR-DEEP_AVOCADO
				SET location = wpink			// location (Bolt-Mace-Staff)
				LPM ~colour~
				SET gradient = 22				// sets colour index 22 DARK_BROWN
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 23				// sets colour index 23 LIGHT_COPPER
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
 			END
		BUT_ONLY
	END
END

// Wyvern's Tail +2
ACTION_IF (FILE_EXISTS_IN_GAME ~blun17.itm~) BEGIN
	COPY_EXISTING ~blun17.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 213				// 213 TRADE_PEASANT_MINOR-VIRIDIAN replaces colour index 7 LIGHT_METALLIC_GREEN
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 236				// 236 CLERIC_GOOD_MINOR-DARK_PINE replaces colour index 7 LIGHT_METALLIC_GREEN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 246				// 246 MAGE_MINOR-CHROME_PINE replaces colour index 7 LIGHT_METALLIC_GREEN
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Skullcrusher +3
ACTION_IF (FILE_EXISTS_IN_GAME ~blun18.itm~) BEGIN
	COPY_EXISTING ~blun18.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~M2~			// Mace (alternate)
			LPM ~clear~
			SET gradient = 212				// 212 TRADE_PEASANT_MAJOR-CHROME_SLATE replaces colour index 28 BLUISH_SILVER
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 254				// 254 EBONY replaces colour index 28 BLUISH_SILVER
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 231				// 231 KOBOLD_MINOR-CHROME_COOL_GRAY replaces colour index 28 BLUISH_SILVER
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Mauler's Arm +2
ACTION_IF (FILE_EXISTS_IN_GAME ~blun19.itm~) BEGIN
	COPY_EXISTING ~blun19.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~M2~
			WRITE_ASCII 0x3A ~IBLUN11~ #8	// replaces IBLUN05
			WRITE_ASCII 0x76 ~IBLUN11~ #8	// replaces IBLUN05
			LPM ~clear~
			SET gradient = 222				// 222 DROW_HAIR-PLATINUM_GRAY replaces colour index 96 CHROME_BLUE
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 248				// 248 OGRE_MAJOR-BATTLESHIP_GRAY replaces colour index 38 LIGHT_DIRT_BROWN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 2				// 2 DARK_GOLD replaces colour index 96 CHROME_BLUE
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Ardulia's Fall +1
ACTION_IF (FILE_EXISTS_IN_GAME ~blun20.itm~) BEGIN
	COPY_EXISTING ~blun20.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~M2~			// Mace (alternate)
			LPM ~clear~
			SET gradient = 238				// 238 CLERIC_NEUTRAL_MINOR-RUSSET_BROWN replaces colour index 24 BROWN_GOLD
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 253				// 253 DUERGAR_MINOR-PALE_TAUPE replaces colour index 24 BROWN_GOLD
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 211				// 211 MERCHANT_MINOR-DARK_BRASS replaces colour index 24 BROWN_GOLD
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Blackblood +3
ACTION_IF (FILE_EXISTS_IN_GAME ~blun22.itm~) BEGIN
	COPY_EXISTING ~blun22.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~MS~			// Morning star
			LPM ~clear~
			SET gradient = 198				// 198 BLACK_SCARLET replaces colour index 47 PURE_DARK_RED
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 210				// 210 MERCHANT_MAJOR-AMBER replaces colour index 47 PURE_DARK_RED
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 243				// 243 FIGHTER_MAJOR-CRIMSON replaces colour index 47 PURE_DARK_RED
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Bone Club +2, +3 vs. undead
ACTION_IF (FILE_EXISTS_IN_GAME ~blun23.itm~) BEGIN
	COPY_EXISTING ~blun23.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~MS~
			LPM ~clear~
			SET gradient = 223				// 223 DROW_SKIN-MOSS_GREEN replaces colour index 10 LIGHT_PURE_GOLD
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 138				// sets colour index 138 DARK_SAND
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 222				// 222 DROW_HAIR-PLATINUM_GRAY replaces colour index 22 DARK_BROWN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 222				// 222 DROW_HAIR-PLATINUM_GRAY replaces colour index 10 LIGHT_PURE_GOLD
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Gnasher +2
ACTION_IF (FILE_EXISTS_IN_GAME ~blun24.itm~) BEGIN
	COPY_EXISTING ~blun24.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~MS~
			LPM ~clear~
			SET gradient = 247				// 247 OGRE_SKIN-CHROME_CRIMSON replaces colour index 22 DARK_BROWN
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 211				// sets colour index 211 MERCHANT_MINOR-DARK_BRASS
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 198				// 198 BLACK_SCARLET replaces colour index 22 DARK_BROWN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 247				// 247 OGRE_SKIN-CHROME_CRIMSON replaces colour index 22 DARK_BROWN
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Club of Detonation +3 - Club of Detonation +5
ACTION_FOR_EACH blunt IN ~blun26~ ~blun27~ BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%blunt%.itm~) BEGIN
		COPY_EXISTING ~%blunt%.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				//WRITE_ASCII 0x22 ~MS~
				LPM ~clear~
				SET gradient = 247				// 247 OGRE_SKIN-CHROME_CRIMSON replaces colour index 6 DARK_SILVER and 30 LIGHT_IRON_GRAY
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 235				// sets colour index 235 CLERIC_GOOD_MAJOR-GLAUCOUS_GRAY
				SET location = wpink			// location (Bolt-Mace-Staff)
				LPM ~colour~
				SET gradient = 210				// 210 MERCHANT_MAJOR-AMBER replaces colour index 92 LIGHT_CHOCOLATE and 91 DARK_CHOCOLATE
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 247				// 247 OGRE_SKIN-CHROME_CRIMSON replaces colour index 6 DARK_SILVER and 30 LIGHT_IRON_GRAY
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
			END
		BUT_ONLY
	END
END

// Mace of Disruption +1
ACTION_IF (FILE_EXISTS_IN_GAME ~blun12.itm~) BEGIN
	COPY_EXISTING ~blun12.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~M2~			// Mace (alternate)
			LPM ~clear~
			SET gradient = 248				// 248 OGRE_MAJOR-BATTLESHIP_GRAY replaces colour index 97 LIGHT_MINTY_BLUE
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 245				// 245 MAGE_MAJOR-CHROME_SEA_GRAY replaces colour index 97 LIGHT_MINTY_BLUE
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET setr = 54					// replaces colour index 0
			SET setg = 202
			SET setb = 255
			SET speed = 0x6e
			SET location = wblue			// location (Head/Blade minor)
			LPM ~pulse~
			SET gradient = 231				// 231 KOBOLD_MINOR-CHROME_COOL_GRAY replaces colour index 97 LIGHT_MINTY_BLUE
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Mace of Disruption +2
ACTION_IF (FILE_EXISTS_IN_GAME ~blun25.itm~) BEGIN
	COPY_EXISTING ~blun25.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~M2~			// Mace (alternate)
			WRITE_ASCII 0x3A ~IBLUN12~ #8	// replaces IBLUN05
			WRITE_ASCII 0x76 ~IBLUN12~ #8	// replaces IBLUN05
			LPM ~clear~
			SET gradient = 199				// 199 BLACK_TEAL replaces colour index 96 CHROME_BLUE
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 245				// 245 MAGE_MAJOR-CHROME_SEA_GRAY replaces colour index 38 LIGHT_DIRT_BROWN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET setr = 84
			SET setg = 232
			SET setb = 255
			SET speed = 0x7e
			SET location = wblue			// location (Head/Blade minor)
			LPM ~pulse~
			SET gradient = 249				// 249 OGRE_MINOR-METALLIC_SLATE replaces colour index 96 CHROME_BLUE
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Flail of Ages +3
ACTION_IF (FILE_EXISTS_IN_GAME ~blun14.itm~) BEGIN
	COPY_EXISTING ~blun14.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F3~			// Flail (alternate 3)
			LPM ~clear~
			SET setr = 229
			SET setg = 215
			SET setb = 83
			SET speed = 0x64
			SET location = wblue			// location (Head/Blade minor)
			LPM ~pulse~
			SET gradient = 245				// 245 MAGE_MAJOR-CHROME_SEA_GRAY replaces colour index 25 DARK_PURE_GOLD
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 243				// sets colour index 243 FIGHTER_MAJOR-CRIMSON
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 244				// 244 FIGHTER_MINOR-DARK_CADET_GRAY replaces colour index 99 GOLDEN_BROWN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 252				// 252 DUERGAR_MAJOR-GHOULISH_GREEN replaces colour index 25 DARK_PURE_GOLD
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Flail of Ages +2
ACTION_IF (FILE_EXISTS_IN_GAME ~blun14d.itm~) BEGIN
	COPY_EXISTING ~blun14d.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F1~			// Flail (alternate 2)
			LPM ~clear~
			SET gradient = 243				// 243 FIGHTER_MAJOR-CRIMSON replaces colour index 27 GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 91				// 91 DARK_CHOCOLATE replaces colour index 23 LIGHT_COPPER
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 245				// 245 MAGE_MAJOR-CHROME_SEA_GRAY replaces colour index 27 GRAY
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Flail of Ages +2
ACTION_IF (FILE_EXISTS_IN_GAME ~blun14e.itm~) BEGIN
	COPY_EXISTING ~blun14e.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F1~			// Flail (alternate 2)
			LPM ~clear~
			SET gradient = 252				// 252 DUERGAR_MAJOR-GHOULISH_GREEN replaces colour index 27 GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 91				// 91 DARK_CHOCOLATE replaces colour index 23 LIGHT_COPPER
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 245				// 245 MAGE_MAJOR-CHROME_SEA_GRAY replaces colour index 27 GRAY
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Flail of Ages +2
ACTION_IF (FILE_EXISTS_IN_GAME ~blun14f.itm~) BEGIN
	COPY_EXISTING ~blun14f.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F1~			// Flail (alternate 2)
			LPM ~clear~
			SET gradient = 246				// 246 MAGE_MINOR-CHROME_PINE replaces colour index 27 GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 91				// 91 DARK_CHOCOLATE replaces colour index 23 LIGHT_COPPER
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 243				// 243 FIGHTER_MAJOR-CRIMSON replaces colour index 27 GRAY
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Flail of Ages +1
ACTION_IF (FILE_EXISTS_IN_GAME ~blun14g.itm~) BEGIN
	COPY_EXISTING ~blun14g.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F0~			// Flail (alternate 1)
			LPM ~clear~
			SET gradient = 246				// 246 MAGE_MINOR-CHROME_PINE replaces colour index 27 GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 91				// 91 DARK_CHOCOLATE replaces colour index 23 LIGHT_COPPER
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 245				// 245 MAGE_MAJOR-CHROME_SEA_GRAY replaces colour index 27 GRAY
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Flail of Ages +1
ACTION_IF (FILE_EXISTS_IN_GAME ~blun14h.itm~) BEGIN
	COPY_EXISTING ~blun14h.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F0~			// Flail (alternate 1)
			LPM ~clear~
			SET gradient = 246				// 246 MAGE_MINOR-CHROME_PINE replaces colour index 27 GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 91				// 91 DARK_CHOCOLATE replaces colour index 23 LIGHT_COPPER
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 243				// 243 FIGHTER_MAJOR-CRIMSON replaces colour index 27 GRAY
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Flail of Ages +1
ACTION_IF (FILE_EXISTS_IN_GAME ~blun14i.itm~) BEGIN
	COPY_EXISTING ~blun14i.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F0~			// Flail (alternate 1)
			LPM ~clear~
			SET gradient = 246				// 246 MAGE_MINOR-CHROME_PINE replaces colour index 27 GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 91				// 91 DARK_CHOCOLATE replaces colour index 23 LIGHT_COPPER
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 246				// 246 MAGE_MINOR-CHROME_PINE replaces colour index 27 GRAY
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Flail +2
ACTION_IF (FILE_EXISTS_IN_GAME ~blun13.itm~) BEGIN
	COPY_EXISTING ~blun13.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F0~			// Flail (alternate 1)
			WRITE_ASCII 0x3A ~IBLUN13B~ #8	// replaces IBLUN13
			WRITE_ASCII 0x76 ~IBLUN13B~ #8	// replaces IBLUN13
			LPM ~clear~
			SET gradient = 90				// 90 MOLDY_GOLD replaces colour index 27 GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 99				// 99 GOLDEN_BROWN replaces colour index 23 LIGHT_COPPER
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 247				// 247 OGRE_SKIN-CHROME_CRIMSON replaces colour index 27 GRAY
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Flail of Ages +5
ACTION_IF (FILE_EXISTS_IN_GAME ~blun30.itm~) BEGIN
	COPY_EXISTING ~blun30.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F3~			// Flail (alternate 3)
			LPM ~clear~
			SET setr = 229
			SET setg = 215
			SET setb = 83
			SET speed = 0x64
			SET location = wblue			// location (Head/Blade minor)
			LPM ~pulse~
			SET gradient = 218				// 218 ELF_HAIR-CHROME_BLUE_GRAY replaces colour index 25 DARK_PURE_GOLD
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 216				// sets colour index 216 PIRATE_MAJOR-CHROME_GOLDENROD
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 244				// 244 FIGHTER_MINOR-DARK_CADET_GRAY replaces colour index 99 GOLDEN_BROWN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 228				// 228 LEATHER-SPECTRAL_GREEN replaces colour index 25 DARK_PURE_GOLD
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Drow Flail +3
ACTION_IF (FILE_EXISTS_IN_GAME ~dwblun01.itm~) BEGIN
	COPY_EXISTING ~dwblun01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F0~			// Flail (alternate 1)
			LPM ~clear~
			SET gradient = 218				// 218 ELF_HAIR-CHROME_BLUE_GRAY replaces colour index 30 LIGHT_IRON_GRAY
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 183				// 183 CHARCOAL replaces colour index 23 LIGHT_COPPER
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 212				// 212 TRADE_PEASANT_MAJOR-CHROME_SLATE replaces colour index 30 LIGHT_IRON_GRAY
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Flail of Ages +4
ACTION_IF (FILE_EXISTS_IN_GAME ~blun30c.itm~) BEGIN
	COPY_EXISTING ~blun30c.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F3~			// Flail (alternate 3)
			LPM ~clear~
			SET setr = 229
			SET setg = 215
			SET setb = 83
			SET speed = 0x64
			SET location = wblue			// location (Head/Blade minor)
			LPM ~pulse~
			SET gradient = 245				// 245 MAGE_MAJOR-CHROME_SEA_GRAY replaces colour index 25 DARK_PURE_GOLD
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 243				// sets colour index 243 FIGHTER_MAJOR-CRIMSON
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 244				// 244 FIGHTER_MINOR-DARK_CADET_GRAY replaces colour index 99 GOLDEN_BROWN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 228				// 228 LEATHER-SPECTRAL_GREEN replaces colour index 25 DARK_PURE_GOLD
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// Flail of Ages +4
ACTION_IF (FILE_EXISTS_IN_GAME ~blun30d.itm~) BEGIN
	COPY_EXISTING ~blun30d.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~F3~			// Flail (alternate 3)
			LPM ~clear~
			SET setr = 229
			SET setg = 215
			SET setb = 83
			SET speed = 0x64
			SET location = wblue			// location (Head/Blade minor)
			LPM ~pulse~
			SET gradient = 245				// 245 MAGE_MAJOR-CHROME_SEA_GRAY replaces colour index 25 DARK_PURE_GOLD
			SET location = wgrey			// location (Head/Blade/Staff major)
			LPM ~colour~
			SET gradient = 243				// sets colour index 243 FIGHTER_MAJOR-CRIMSON
			SET location = wpink			// location (Bolt-Mace-Staff)
			LPM ~colour~
			SET gradient = 244				// 244 FIGHTER_MINOR-DARK_CADET_GRAY replaces colour index 99 GOLDEN_BROWN
			SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
			LPM ~colour~
			SET gradient = 228				// 228 LEATHER-SPECTRAL_GREEN replaces colour index 25 DARK_PURE_GOLD
			SET location = wblue			// location (Head/Blade minor)
			LPM ~colour~
		END
	BUT_ONLY
END

// The Sleeper +2
// Gwen fix: modified minimum strength, damages, and used a new icon (IBLUN16B) to avoid overwriting the vanilla one (let's keep it for modders!).
ACTION_IF (1pp_sleeper = 1) BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~blun16.itm~) BEGIN
		COPY_EXISTING ~blun16.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				SAY DESC @400804
				WRITE_ASCII 0x22 ~F0~			// Flail (alternate 1) replace MS
				WRITE_ASCII 0x3A ~IBLUN16B~ #8	// replaces IBLUN16
				WRITE_ASCII 0x76 ~IBLUN16B~ #8
				WRITE_ASCII 0x58 ~CBLUN13~ #8	// replaces CBLUN16
				WRITE_LONG  0x08 6704			// replaces General name
				WRITE_LONG  0x50 6706			// replaces General description
				WRITE_SHORT 0x1c 0x17			// Category
				WRITE_SHORT 0x26 13				// Minimum strength
				LPF ALTER_ITEM_HEADER INT_VAR dicesize = 6 dicenumber = 1 END
				LPM ~clear~
				SET gradient = 90				// 90 MOLDY_GOLD replaces colour index 27 GRAY
				SET location = wgrey			// location (Head/Blade/Staff major)
				LPM ~colour~
				SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 27 GRAY
				SET location = wred				// location (Grip/Staff minor - vanilla = whole staff)
				LPM ~colour~
				SET gradient = 245				// 245 MAGE_MAJOR-CHROME_SEA_GRAY replaces colour index 25 DARK_PURE_GOLD
				SET location = wblue			// location (Head/Blade minor)
				LPM ~colour~
			END
		BUT_ONLY
	END
END

//END of COMPONENT