/* ================================================================================================================================================================================== *
 *  v 4.2.0                                                                                                                                                                           *
 *                                       C O M P O N E N T   :   C o r e   u p d a t e s   a n d   i t e m   p a t c h e s   ( s h i e l d s )                                        *
 *                                                                                                                                                                                    *
 * ================================================================================================================================================================================== *
 *  This part installs shields stuff.                                                                                                                                                 *
 * ================================================================================================================================================================================== *
 *  change-log:                                                                                                                                                                       *
 *  -----------                                                                                                                                                                       *
 *      - Replaced macros with functions whenever possible.                                                                                                                           *
 *      - Coding simplification:                                                                                                                                                      *
 *          Replaced WRITE_LONG 0x3E 0 and WRITE_ASCII 0x3A ~ISHLDS01~ with WRITE_ASCII 0x3A ~ISHLDS01~ #8. Id. with offsets 0x48 0x44, and 0x5C 0x58.                                *
 *          Grouped actions or patches with ACTION_FOR_EACH and PATCH_FOR_EACH whenever possible.                                                                                     *
 *          Used new 1pp_compatibility.tph library to improve 1PP crossmods compatibility (BG1 NPC Project, Rolles, Song and Silence, The Unusual Oddities Shop).                     *
 *                                                                                                                                                                                    *
 *  specific fixes:                                                                                                                                                                   *
 *  ---------------                                                                                                                                                                   *
 *      - #82   ==> shld02.itm (Small Shield +1): LPM ~clear~ was missing, and the code stacked opcode #7 global effects.                                                             *
 *      - #1456 ==> shld31a.itm (Gorm's Arm +3): fixed wrong coding (WRITE_SHORT instead of WRITE_BYTE for Minimum strength).                                                         *
 *      - #1475 ==> shld01p.itm (Buckler +2): fixed wrong coding (opcode #0 parameter1 0xfffffe - 16777214 ?? - should be -3), add opcode #0 with parameter1 = -3 and parameter2 = 4  *
 *                  to add missing protection vs piercing weapons, added missing price, and fix item description to fit ITM file.                                                     *
 *      - #1622 ==> shld06p.itm (Redshield +1, +4 vs. Monstrous): fixed wrong coding (opcode #219: switch parameter1 and 2, and parameter2 2 - EA.IDS - should be 3 - GENERAL.IDS),   *
 *                  added an external effect (shld06p.eff) and replaced opcode #178 with opcode #177, otherwise opcode #178 won't work.                                               *
 *      - #1657 ==> shld07p.itm (Sartessa's Vengeance +1): fixed wrong coding for add magical flag [replaced WRITE_BYTE 0x1b 0x6c with WRITE_LONG 0x18 (THIS | BIT6)].                *
 *      - #1707 ==> shld08p.itm (Tarloc's Contingency +1): code simplified (1tarsp.spl) and fixed wrong coding for Casting sound (1tarss.spl).                                        *
 *      - #1762 ==> shld09p.itm (Shield of Devotion +1): fixed wrong coding (op#62: parameter2 should be 4, not 3).                                                                   *
 *      - #1812 ==> x#ajshld.itm (Ilvastarr Family Shield - The BG1 NPC Project mod): fixed typo (was patching #AJSHLD instead of X#AJSHLD).                                          *
 * ================================================================================================================================================================================== */

/* =============================== *
 *          SHIELDS BEGIN          *
 * =============================== */

ACTION_IF (1pp_shields_shadows = 2) BEGIN	// shadow shields on paperdolls (1 = No - 2 = Yes [Default])

	ACTION_FOR_EACH resource IN ~wphc0inv~ ~wphc1inv~ ~wphc2inv~ ~wphc3inv~ ~wphc4inv~ ~wphc5inv~ ~wphc6inv~ ~wphc7inv~ ~wplc0inv~ ~wplc1inv~ ~wplc2inv~ ~wplc3inv~ ~wplc4inv~ ~wplc5inv~ ~wplc6inv~ ~wplc7inv~ ~wpmc0inv~ ~wpmc1inv~ ~wpmc2inv~ ~wpmc3inv~ ~wpmc4inv~ ~wpmc5inv~ ~wpmc6inv~ ~wpmc7inv~ ~wpnc0inv~ ~wpnc1inv~ ~wpnc2inv~ ~wpnc3inv~ ~wpnc4inv~ ~wpnc5inv~ ~wpnc6inv~ ~wpnc7inv~ ~wpsc0inv~ ~wpsc1inv~ ~wpsc2inv~ ~wpsc3inv~ ~wpsc4inv~ ~wpsc5inv~ ~wpsc6inv~ ~wpsc7inv~ BEGIN

		COPY ~1pp/additions/obj_1pp_a/%resource%.bam~ ~override~

	END

END

PRINT @400012 // ~Patching shields...~
SILENT

// Small Shield
ACTION_IF (FILE_EXISTS_IN_GAME ~shld01.itm~) BEGIN
	COPY_EXISTING ~shld01.itm~ ~override/shld01a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SET gradient = 22				// sets colour index 22 DARK_BROWN
			SET location = sred				// location (Grip)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 92			// sets colour index 92 LIGHT_CHOCOLATE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C0~			// replaces D2 Small shield
			WRITE_ASCII 0x3A ~ISHLDS01~ #8
			WRITE_ASCII 0x44 ~GSSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD25~ #8	// replaces CSHLD28
			LPM ~clear~
			SET gradient = 200				// 200 HAIR1-WHITE_TEAL replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 21				// 21 DARK_IRON_GRAY replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 238			// sets colour index 238 CLERIC_NEUTRAL_MINOR-RUSSET_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Small Shield +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld02.itm~) BEGIN
	COPY_EXISTING ~shld02.itm~ ~override/shld02a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 109				// sets colour index 109 TERRA_COTTA
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 24				// 24 BROWN_GOLD replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 25				// 25 DARK_PURE_GOLD replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 29			// sets colour index 29 RED-TINTED_BLACK
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld02.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C0~			// replaces D2 Small shield
			WRITE_ASCII 0x3A ~ISHLDS04~ #8	// replaces ISHLDS02
			WRITE_ASCII 0x44 ~GSSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD25~ #8	// replaces CSHLD28
			// Gwen fix: the following line was missing
			LPM ~clear~
			SET gradient = 24				// 24 BROWN_GOLD replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 211				// 211 MERCHANT_MINOR-DARK_BRASS replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 237			// sets colour index 237 CLERIC_NEUTRAL_MAJOR-TAUPE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Medium Shield
ACTION_IF (FILE_EXISTS_IN_GAME ~shld03.itm~) BEGIN
	COPY_EXISTING ~shld03.itm~ ~override/shld03a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 94				// sets colour index 94 RHUBARB
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 100				// 100 DARK_ASH_GRAY replaces colour index 104 DARK_CHROME_PURPLE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 215				// 215 GYPSY_MINOR-CHROME_VERMILLION replaces colour index 27 GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 66			// sets colour index 66 FADED_BLACK
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld03.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C1~			// replaces D3 Medium shield
			WRITE_ASCII 0x3A ~ISHLDM01~ #8
			WRITE_ASCII 0x44 ~GMSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLDM0~ #8	// replaces CSHLD29
			LPM ~clear~
			SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 27 GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 209				// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 104 DARK_CHROME_PURPLE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 87			// sets colour index 87 SADDLE_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
			BUT_ONLY
END

// Medium Shield +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld04.itm~) BEGIN
	COPY_EXISTING ~shld04.itm~ ~override/shld04a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 81				// sets colour index 81 FADED_GOLD
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 250				// 250 SHADOW_DRUID_MAJOR-YELLOW_ORANGE replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 98				// 98 LEAF_GREEN replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 160			// sets colour index 160 DEEP_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld04.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C1~			// replaces D3 Medium shield
			WRITE_ASCII 0x3A ~ISHLDM05~ #8	// replaces ISHLDM02
			WRITE_ASCII 0x44 ~GMSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLDM0~ #8	// replaces CSHLD29
			LPM ~clear~
			SET gradient = 208				// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER 
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 211				// 211 MERCHANT_MINOR-DARK_BRASS replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 66			// sets colour index 66 FADED_BLACK
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Large Shield
ACTION_IF (FILE_EXISTS_IN_GAME ~shld05.itm~) BEGIN
	COPY_EXISTING ~shld05.itm~ ~override/shld05a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 91				// sets colour index 91 DARK_CHOCOLATE
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 6				// 6 DARK_SILVER replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 26				// 26 WOOD replaces colour index 102 SEA_BLUE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 87			// sets colour index 87 SADDLE_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld05.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C2~			// replaces D4 Large shield
			WRITE_ASCII 0x3A ~ISHLDL01~ #8
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD30~ #8	// replaces CSHLD23
			LPM ~clear~
			SET gradient = 239				// 239 CLERIC_EVIL_MAJOR-PALE_BRONZ replaces colour index 102 SEA_BLUE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 233				// sets colour index 233 HOBGOBLIN_MAJOR-PERUVIAN_BROWN
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 234				// 234 HOBGOBLIN_MINOR-INDIAN_RED replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 41			// sets colour index 41 MEDIUM_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Large Shield +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld06.itm~) BEGIN
	COPY_EXISTING ~shld06.itm~ ~override/shld06a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 99				// sets colour index 99 GOLDEN_BROWN
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 30				// 30 LIGHT_IRON_GRAY replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 112				// 112 SEA_FOAM replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 237			// sets colour index 237 CLERIC_NEUTRAL_MAJOR-TAUPE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld06.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C2~			// replaces D4 Large shield
			WRITE_ASCII 0x3A ~ISHLDL04~ #8	// replaces ISHLDL02
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD30~ #8	// replaces CSHLD23
			LPM ~clear~
			SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 72				// sets colour index 72 STEEL_GRAY
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 93				// 93 DARK_CEMENT_GRAY replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 237			// sets colour index 237 CLERIC_NEUTRAL_MAJOR-TAUPE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Shield of the Falling Stars +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld07.itm~) BEGIN
	COPY_EXISTING ~shld07.itm~ ~override/shld07a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 3				// sets colour index 3 LIGHT_GOLD
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 16				// 16 SILVERISH_GOLD replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 208				// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 66			// sets colour index 66 FADED_BLACK
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld07.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C6~			// replaces D4 Large shield
			WRITE_ASCII 0x3A ~1SHLDL02~ #8
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDL2~ #8	// replaces CSHLD23
			LPM ~clear~
			SET gradient = 249				// 249 OGRE_MINOR-METALLIC_SLATE replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 66				// sets colour index 66 FADED_BLACK
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 249				// 249 OGRE_MINOR-METALLIC_SLATE replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 51			// sets colour index 51 DARK_OLIVE_GREEN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Bucklers
ACTION_IF (FILE_EXISTS_IN_GAME ~shld08.itm~) BEGIN
	COPY_EXISTING ~shld08.itm~ ~override/shld08a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 27				// sets colour index 27 GRAY
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 28				// 28 BLUISH_SILVER replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 30				// 30 LIGHT_IRON_GRAY replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 92			// sets colour index 92 LIGHT_CHOCOLATE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld08.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C4~			// replaces D2 Small shield
			WRITE_ASCII 0x3A ~ISHLDB01~ #8
			WRITE_ASCII 0x44 ~GBSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDB1~ #8	// replaces CSHLD28
			LPM ~clear~
			SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 239				// sets colour index 239 CLERIC_EVIL_MAJOR-PALE_BRONZ
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 188			// sets colour index 188 MEDIUM_GRAY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld09.itm~) BEGIN
	COPY_EXISTING ~shld09.itm~ ~override/shld09a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 209				// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 22				// 22 DARK_BROWN replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 23				// 23 LIGHT_COPPER replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 209			// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld09.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C4~			// replaces D2 Small shield
			WRITE_ASCII 0x3A ~ISHLDB02~ #8	// replaces ISHLDB01
			WRITE_ASCII 0x44 ~GBSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDB1~ #8	// replaces CSHLD28
			LPM ~clear~
			SET gradient = 192				// 192 CHROME_TEAL replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 186				// sets colour index 186 DARK_PLUM
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 192				// 192 CHROME_TEAL replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 184			// sets colour index 184 CADET_BLUE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld10.itm~) BEGIN
	COPY_EXISTING ~shld10.itm~ ~override/shld10a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 26				// sets colour index 26 WOOD
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 28				// 28 BLUISH_SILVER replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 26				// 26 WOOD replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 179			// sets colour index 179 PALE_INDIGO
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld10.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C4~			// replaces D2 Small shield
			WRITE_ASCII 0x3A ~ISHLDB03~ #8	// replaces ISHLDB01
			WRITE_ASCII 0x44 ~GBSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDB1~ #8	// replaces CSHLD28
			LPM ~clear~
			SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 160				// sets colour index 160 DEEP_BROWN
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 206			// sets colour index 206 NOBLE_MAJOR2-DARK_SEA_GRAY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Small Shields
ACTION_IF (FILE_EXISTS_IN_GAME ~shld11.itm~) BEGIN
	COPY_EXISTING ~shld11.itm~ ~override/shld11a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 81				// 81 FADED_GOLD sets colour index
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 28				// 28 BLUISH_SILVER replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 30				// 30 LIGHT_IRON_GRAY replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 188			// sets colour index 188 MEDIUM_GRAY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld11.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C0~			// replaces D2 Small shield
			WRITE_ASCII 0x3A ~ISHLDS02~ #8	// replaces ISHLDS01
			WRITE_ASCII 0x44 ~GSSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD25~ #8	// replaces CSHLD28
			LPM ~clear~
			SET gradient = 227				// 227 METAL_WILD-CORAL replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 232				// 232 HOBGOBLIN_SKIN-CINDER_GRAY replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 183			// sets colour index 183 CHARCOAL
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld12.itm~) BEGIN
	COPY_EXISTING ~shld12.itm~ ~override/shld12a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 72				// sets colour index 72 STEEL_GRAY
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 27				// 27 GRAY replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 30				// 30 LIGHT_IRON_GRAY replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 99			// sets colour index 99 GOLDEN_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld12.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C0~			// replaces D2 Small shield
			WRITE_ASCII 0x3A ~ISHLDS03~ #8	// replaces ISHLDS01
			WRITE_ASCII 0x44 ~GSSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD25~ #8	// replaces CSHLD28
			LPM ~clear~
			SET gradient = 207				// 207 NOBLE_MINOR2-CHROME_GOLD replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 87			// sets colour index 87 SADDLE_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Medium Shields
ACTION_IF (FILE_EXISTS_IN_GAME ~shld13.itm~) BEGIN
	COPY_EXISTING ~shld13.itm~ ~override/shld13a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 174				// sets colour index 174 PALE_SLATE
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 100				// 100 DARK_ASH_GRAY replaces colour index 59 LIGHT_PURPLE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 176				// 176 STEEL_BLUE replaces colour index 100 DARK_ASH_GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 183			// sets colour index 183 CHARCOAL
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld13.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C1~			// replaces D3 Medium shield
			WRITE_ASCII 0x3A ~ISHLDM02~ #8	// replaces ISHLDM01
			WRITE_ASCII 0x44 ~GMSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLDM0~ #8	// replaces CSHLD29
			LPM ~clear~
			SET gradient = 217				// 217 PIRATE_MINOR-BRIGHT_SLATE_GRAY replaces colour index 100 DARK_ASH_GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 231				// sets colour index 231 KOBOLD_MINOR-CHROME_COOL_GRAY
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 59 LIGHT_PURPLE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 186			// sets colour index 186 DARK_PLUM
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld14.itm~) BEGIN
	COPY_EXISTING ~shld14.itm~ ~override/shld14a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 92				// sets colour index 92 LIGHT_CHOCOLATE
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 30				// 30 LIGHT_IRON_GRAY replaces colour index 100 DARK_ASH_GRAY
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 242				// 242 THIEF_MINOR-PALE_OLIVE replaces colour index 59 LIGHT_PURPLE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 39			// sets colour index 39 DARK_DIRT_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld14.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C1~			// replaces D3 Medium shield
			WRITE_ASCII 0x3A ~ISHLDM03~ #8	// replaces ISHLDM01
			WRITE_ASCII 0x44 ~GMSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLDM0~ #8	// replaces CSHLD29
			LPM ~clear~
			SET gradient = 226				// 226 METAL_NORMAL-EIGENGRAU replaces colour index 59 LIGHT_PURPLE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 237				// sets colour index 237 CLERIC_NEUTRAL_MAJOR-TAUPE
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 100 DARK_ASH_GRAY
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 238			// sets colour index 238 CLERIC_NEUTRAL_MINOR-RUSSET_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Large Shields
ACTION_IF (FILE_EXISTS_IN_GAME ~shld15.itm~) BEGIN
	COPY_EXISTING ~shld15.itm~ ~override/shld15a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 92				// sets colour index 92 LIGHT_CHOCOLATE
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 27				// 27 GRAY replaces colour index 41 MEDIUM_BROWN
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 215				// 215 GYPSY_MINOR-CHROME_VERMILLION replaces colour index 102 SEA_BLUE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 254			// sets colour index 254 EBONY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld15.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C2~			// replaces D4 Large shield
			WRITE_ASCII 0x3A ~ISHLDL02~ #8	// replaces ISHLDL01
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD30~ #8	// replaces CSHLD23
			LPM ~clear~
			SET gradient = 202				// 202 HAIR2-LIBERTY_BLUE replaces colour index 102 SEA_BLUE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 235				// sets colour index 235 CLERIC_GOOD_MAJOR-GLAUCOUS_GRAY
			SET location = steal			// location (Interior) (Body/trim)
			LPM ~colour~
			SET gradient = 235				// 235 CLERIC_GOOD_MAJOR-GLAUCOUS_GRAY replaces colour index 41 MEDIUM_BROWN
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 204			// sets colour index 204 NOBLE_MAJOR1-BLACK_PLUM
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld16.itm~) BEGIN
	COPY_EXISTING ~shld16.itm~ ~override/shld16a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 100				// sets colour index 100 DARK_ASH_GRAY
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 248				// 248 OGRE_MAJOR-BATTLESHIP_GRAY replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 109				// 109 TERRA_COTTA replaces colour index 102 SEA_BLUE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2) BEGIN
				SET gradient = 238			// sets colour index 238 CLERIC_NEUTRAL_MINOR-RUSSET_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld16.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C2~			// replaces D4 Large shield
			WRITE_ASCII 0x3A ~ISHLDL03~ #8	// replaces ISHLDL01
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD30~ #8	// replaces CSHLD23
			LPM ~clear~
			SET gradient = 239				// 239 CLERIC_EVIL_MAJOR-PALE_BRONZ replaces colour index 102 SEA_BLUE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 208				// sets colour index 208 ATH_PEASANT_MAJOR-FADED_WHEAT
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 234				// 234 HOBGOBLIN_MINOR-INDIAN_RED replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 238			// sets colour index 238 CLERIC_NEUTRAL_MINOR-RUSSET_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Buckler +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld17.itm~) BEGIN
	COPY_EXISTING ~shld17.itm~ ~override/shld17a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 66				// sets colour index 66 FADED_BLACK
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 90				// 90 MOLDY_GOLD replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 208				// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 66			// sets colour index 66 FADED_BLACK
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld17.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C4~			// replaces D2 Small shield
			WRITE_ASCII 0x3A ~ISHLDB04~ #8	// replaces ISHLDB02
			WRITE_ASCII 0x44 ~GBSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDB1~ #8	// replaces CSHLD28
			LPM ~clear~
			SET gradient = 250				// 250 SHADOW_DRUID_MAJOR-YELLOW_ORANGE replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 187				// sets colour index 187 BLUE_GRAY
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 224				// 224 DROW_MAJOR-MAIZE replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 187			// sets colour index 187 BLUE_GRAY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Pellan's Shield +2
ACTION_IF (FILE_EXISTS_IN_GAME ~shld19.itm~) BEGIN
	COPY_EXISTING ~shld19.itm~ ~override/shld19a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 208				// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 211				// 211 MERCHANT_MINOR-DARK_BRASS replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 66			// sets colour index 66 FADED_BLACK
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld19.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C2~			// replaces D4 Large shield
			WRITE_ASCII 0x3A ~ISHLDL06~ #8	// replaces ISHLDL02
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD30~ #8	// replaces CSHLD23
			LPM ~clear~
			SET gradient = 208				// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 209				// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 225				// 225 DROW_MINOR-CORNSILK replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 183			// sets colour index 183 CHARCOAL
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Kiel's Buckler
ACTION_IF (FILE_EXISTS_IN_GAME ~shld20.itm~) BEGIN
	COPY_EXISTING ~shld20.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 91				// sets colour index 91 DARK_CHOCOLATE
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 42 BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 253				// 253 DUERGAR_MINOR-PALE_TAUPE replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 91			// sets colour index 91 DARK_CHOCOLATE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Dragon Scale Shield +2
ACTION_IF (FILE_EXISTS_IN_GAME ~shld21.itm~) BEGIN
	COPY_EXISTING ~shld21.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C7~			// replaces D3 Medium shield
			WRITE_ASCII 0x3A ~ISHLD21~ #8
			WRITE_ASCII 0x44 ~GMSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD21~ #8
			LPM ~clear~
			SET gradient = 26				// 26 WOOD (or colour index 216 PIRATE_MAJOR-CHROME_GOLDENROD) replaces colour index 101 METALLIC_RED
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 101				// sets colour index 101 METALLIC_RED (or 214 GYPSY_MAJOR-BRIGHT_GOLDENROD)
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 215				// 215 GYPSY_MINOR-CHROME_VERMILLION replaces colour index 101 METALLIC_RED
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER 
			SET location = spink			// colour (Panel)
			LPM ~colour~
		END
	BUT_ONLY
END

// Sentinel +4
ACTION_IF (FILE_EXISTS_IN_GAME ~shld22.itm~) BEGIN
	COPY_EXISTING ~shld22.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C3~			// replaces D3 Medium shield
			LPM ~clear~
			SET gradient = 203				// 203 SKIN2-MYRTLE_GREEN replaces colour index 52 LIGHT_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 201				// sets colour index 201 SKIN1-AVOCADO
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 30				// 30 LIGHT_IRON_GRAY replaces colour index 30 LIGHT_IRON_GRAY
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 182			// sets colour index 182 DEEP_BLACK
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Sentinel +4
ACTION_IF (FILE_EXISTS_IN_GAME ~chalshld.itm~) BEGIN
	COPY_EXISTING ~chalshld.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C3~			// replaces D3 Medium shield
			LPM ~clear~
			SET gradient = 203				// 203 SKIN2-MYRTLE_GREEN replaces colour index 76 SOLID_RED
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 201				// sets colour index 201 SKIN1-AVOCADO
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 30				// 30 LIGHT_IRON_GRAY replaces colour index 29 RED-TINTED_BLACK
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
			SET gradient = 182				// sets colour index 182 DEEP_BLACK
			SET location = spink			// location (Panel)
			LPM ~colour~
			END
		END
	BUT_ONLY
END

// Delryn Family Shield
ACTION_IF (FILE_EXISTS_IN_GAME ~npshld.itm~) BEGIN
	COPY_EXISTING ~npshld.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C3~			// replaces D3 Medium shield
			WRITE_ASCII 0x44 ~GMSHLD~ #8	// replaces GSHLD03
			LPM ~clear~
			SET gradient = 218				// 218 ELF_HAIR-CHROME_BLUE_GRAY replaces colour index 27 GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 192				// sets colour index 192 CHROME_TEAL
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 217				// 217 PIRATE_MINOR-BRIGHT_SLATE_GRAY replaces colour index 65 REALLY_DARK_GRAY
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 60			// sets colour index 60 DARK_PURPLE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Fortress Shield +3
ACTION_IF (FILE_EXISTS_IN_GAME ~shld23.itm~) BEGIN
	COPY_EXISTING ~shld23.itm~ ~override/shld23a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 192				// sets colour index 192 CHROME_TEAL
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 200				// 200 HAIR1-WHITE_TEAL replaces colour index 60 DARK_PURPLE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 213				// 213 TRADE_PEASANT_MINOR-VIRIDIAN replaces colour index 59 LIGHT_PURPLE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 220			// sets colour index 220 ELF_MAJOR-MIDNIGHT_BLUE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld23.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C2~			// replaces D4 Large shield
			WRITE_ASCII 0x3A ~ISHLD23~ #8
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD23~ #8
			LPM ~clear~
			SET gradient = 217				// 217 PIRATE_MINOR-BRIGHT_SLATE_GRAY replaces colour index 59 LIGHT_PURPLE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 96				// sets colour index 96 CHROME_BLUE
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 184				// 184 CADET_BLUE replaces colour index 60 DARK_PURPLE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 190			// sets colour index 190 DEEP_INDIGO
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Reflection Shield +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld24.itm~) BEGIN
	COPY_EXISTING ~shld24.itm~ ~override/shld24a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER 
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 109				// 109 TERRA_COTTA replaces colour index 43 DARK_BEIGE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 254				// 254 EBONY replaces colour index 43 DARK_BEIGE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 255				// sets colour index 255 ONYX
			SET location = spink			// location (Panel)
			LPM ~colour~
		END
	COPY_EXISTING ~shld24.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C6~			// replaces D2 Small shield
			WRITE_ASCII 0x3A ~1SHLDL05~ #8	// replaces ISHLD24
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDL1~ #8	// replaces CSHLD24
			LPM ~clear~
			SET gradient = 250				// 250 SHADOW_DRUID_MAJOR-YELLOW_ORANGE replaces colour index 43 DARK_BEIGE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 112				// sets colour index 112 SEA_FOAM
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 112				// sets colour index 112 SEA_FOAM
			SET location = spink			// location (Panel)
			LPM ~colour~
		END
	BUT_ONLY
END

// Shield of Harmony +2
ACTION_IF (FILE_EXISTS_IN_GAME ~shld25.itm~) BEGIN
	COPY_EXISTING ~shld25.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ISHLD25~ #8
			WRITE_ASCII 0x58 ~CSHLD17~ #8	// replaces CSHLD25
			LPM ~clear~
			SET gradient = 231				// 231 KOBOLD_MINOR-CHROME_COOL_GRAY replaces colour index 25 DARK_PURE_GOLD
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 221				// sets colour index 221 ELF_MINOR-YELLOW_GREEN
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 203				// 203 SKIN2-MYRTLE_GREEN replaces colour index 24 BROWN_GOLD
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 7			// 7 LIGHT_METALLIC_GREEN replaces colour index 29 RED-TINTED_BLACK
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Shield of the Lost +2
ACTION_IF (FILE_EXISTS_IN_GAME ~shld26.itm~) BEGIN
	COPY_EXISTING ~shld26.itm~ ~override/shld26a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 211				// sets colour index 211 MERCHANT_MINOR-DARK_BRASS
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 211				// 211 MERCHANT_MINOR-DARK_BRASS replaces colour index 31 LIGHT_SEA_BLUE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 218				// 218 ELF_HAIR-CHROME_BLUE_GRAY replaces colour index 57 LIGHT_BLUE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 125			// sets colour index
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld26.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C5~			// replaces D3 Medium shield
			WRITE_ASCII 0x3A ~1SHLDM02~ #8	// replaces ISHLD26
			WRITE_ASCII 0x44 ~GSSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDM2~ #8	// replaces CSHLD26
			LPM ~clear~
			SET gradient = 217				// 217 PIRATE_MINOR-BRIGHT_SLATE_GRAY replaces colour index 57 LIGHT_BLUE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 183				// sets colour index 183 CHARCOAL
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 183				// 183 CHARCOAL replaces colour index 31 LIGHT_SEA_BLUE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 63			// sets colour index 63 LIGHT_GRAY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Saving Grace +3
ACTION_IF (FILE_EXISTS_IN_GAME ~shld27.itm~) BEGIN
	COPY_EXISTING ~shld27.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 218				// sets colour index 218 ELF_HAIR-CHROME_BLUE_GRAY
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 217				// 217 PIRATE_MINOR-BRIGHT_SLATE_GRAY replaces colour index 41 MEDIUM_BROWN
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 218				// 218 ELF_HAIR-CHROME_BLUE_GRAY replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 58			// sets colour index 58 DARK_BLUE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld27.itm~ ~override/shld27a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C3~			// replaces D3 Medium shield
			WRITE_ASCII 0x3A ~ISHLD27~ #8
			WRITE_ASCII 0x44 ~GMSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD27~ #8
			LPM ~clear~
			SET gradient = 209				// 209 ATH_PEASANT_MINOR-ASH_GRAY replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 209				// sets colour index 209 ATH_PEASANT_MINOR-ASH_GRAY
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 6				// 6 DARK_SILVER replaces colour index 41 MEDIUM_BROWN
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 238			// sets colour index 238 CLERIC_NEUTRAL_MINOR-RUSSET_BROWN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Small Shield +2
ACTION_IF (FILE_EXISTS_IN_GAME ~shld28.itm~) BEGIN
	COPY_EXISTING ~shld28.itm~ ~override/shld28a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ISHLD28~ #8
			LPM ~clear~
			SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER 
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 215				// 215 GYPSY_MINOR-CHROME_VERMILLION replaces colour index 59 LIGHT_PURPLE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 210				// 210 MERCHANT_MAJOR-AMBER replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 237			// sets colour index 237 CLERIC_NEUTRAL_MAJOR-TAUPE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld28.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C0~			// replaces D2 Small shield
			WRITE_ASCII 0x3A ~ISHLDS05~ #8	// replaces ISHLD28
			WRITE_ASCII 0x44 ~GSSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD28~ #8	// replaces CSHLD28
			LPM ~clear~
			SET gradient = 212				// 212 TRADE_PEASANT_MAJOR-CHROME_SLATE replaces colour index 98 LEAF_GREEN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 254				// 254 EBONY replaces colour index 59 LIGHT_PURPLE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 244			// sets colour index 244 FIGHTER_MINOR-DARK_CADET_GRAY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Medium Shield +2
ACTION_IF (FILE_EXISTS_IN_GAME ~shld29.itm~) BEGIN
	COPY_EXISTING ~shld29.itm~ ~override/shld29a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~ISHLD29~ #8
			LPM ~clear~
			SET gradient = 90				// sets colour index 90 MOLDY_GOLD
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 211				// 211 MERCHANT_MINOR-DARK_BRASS replaces colour index 39 DARK_DIRT_BROWN
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 212				// 212 TRADE_PEASANT_MAJOR-CHROME_SLATE replaces colour index 27 GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 220			// sets colour index 220 ELF_MAJOR-MIDNIGHT_BLUE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld29.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C3~			// replaces D3 Medium shield
			WRITE_ASCII 0x3A ~ISHLDM09~ #8	// replaces ISHLD29
			WRITE_ASCII 0x44 ~GMSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD29~ #8
			LPM ~clear~
			SET gradient = 101				// 101 METALLIC_RED replaces colour index 27 GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 127				// sets colour index 127 DARK_BRICK_RED
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 253				// 253 DUERGAR_MINOR-PALE_TAUPE replaces colour index 39 DARK_DIRT_BROWN
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 254			// sets colour index 254 EBONY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Large Shield +2
ACTION_IF (FILE_EXISTS_IN_GAME ~shld30.itm~) BEGIN
	COPY_EXISTING ~shld30.itm~ ~override/shld30a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 0				// sets colour index 0 RUST-TINTED_BLACK
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 208				// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 208				// 208 ATH_PEASANT_MAJOR-FADED_WHEAT replaces colour index 27 GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 66			// sets colour index 66 FADED_BLACK
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld30.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C2~			// replaces D4 Large shield
			WRITE_ASCII 0x3A ~ISHLDL05~ #8	// replaces ISHLD30
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~CSHLD30~ #8
			LPM ~clear~
			SET gradient = 109				// 109 TERRA_COTTA replaces colour index 27 GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 216				// sets colour index 216 PIRATE_MAJOR-CHROME_GOLDENROD
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 211				// 211 MERCHANT_MINOR-DARK_BRASS replaces colour index 91 DARK_CHOCOLATE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 2			// sets colour index 2 DARK_GOLD
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Darksteel Shield +4
ACTION_IF (FILE_EXISTS_IN_GAME ~shld31.itm~) BEGIN
	COPY_EXISTING ~shld31.itm~ ~override/shld31a.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 219				// sets colour index 219 ELF_SKIN-CHROME_FOREST_GREEN
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 200				// 200 HAIR1-WHITE_TEAL replaces colour index 60 DARK_PURPLE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 213				// 213 TRADE_PEASANT_MINOR-VIRIDIAN replaces colour index 59 LIGHT_PURPLE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 199			// sets colour index 199 BLACK_TEAL
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	COPY_EXISTING ~shld31.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C6~			// replaces D4 Large shield
			WRITE_ASCII 0x3A ~1SHLDL03~ #8	// replaces ISHLD32
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDL3~ #8	// replaces PSHLD31
			LPM ~clear~
			SET gradient = 192				// 192 CHROME_TEAL replaces colour index 59 LIGHT_PURPLE
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 190				// sets colour index 190 DEEP_INDIGO
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 192				// 192 CHROME_TEAL replaces colour index 60 DARK_PURPLE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 59			// sets colour index 59 LIGHT_PURPLE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Shield of the Order +4
ACTION_IF (FILE_EXISTS_IN_GAME ~shld32.itm~) BEGIN
	COPY_EXISTING ~shld32.itm~ ~override~
		LPF ~1pp_shld32~ END
	BUT_ONLY
END

// Drow Shield +3
ACTION_IF (FILE_EXISTS_IN_GAME ~dwshld01.itm~) BEGIN
	COPY_EXISTING ~dwshld01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C7~			// replaces D3 Medium shield
			WRITE_ASCII 0x44 ~GMSHLD~ #8	// replaces GSHLD03
			LPM ~clear~
			SET gradient = 184				// 184 CADET_BLUE replaces colour index 61 LAVENDER
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 186				// sets colour index 186 DARK_PLUM
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 192				// 192 CHROME_TEAL replaces colour index 62 DARK_LAVENDER
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 199				// sets colour index 199 BLACK_TEAL
			SET location = spink			// location (Panel)
			LPM ~colour~
		END
	BUT_ONLY
END

// Shield of Balduran
ACTION_IF (FILE_EXISTS_IN_GAME ~wa2shiel.itm~) BEGIN
	COPY_EXISTING ~wa2shiel.itm~ ~override~
		LPF ~1pp_wa2shiel~ END
	BUT_ONLY
END



/* ============================================ *
 *          SWITCH SHIELDS AROUND HERE          *
 * ============================================ */

ACTION_IF (1pp_shields_appearance = 2) BEGIN

	PRINT @400013 // ~Switching shields to Baldur's Gate I style by exchange...~
	SILENT
	ACTION_FOR_EACH shield IN ~shld01~ ~shld02~ ~shld03~ ~shld04~ ~shld05~ ~shld06~ ~shld07~ ~shld08~ ~shld09~ ~shld10~ ~shld11~ ~shld12~ ~shld13~ ~shld14~ ~shld15~ ~shld16~ ~shld17~ ~shld19~ ~shld23~ ~shld24~ ~shld26~ ~shld27~ ~shld28~ ~shld29~ ~shld30~ ~shld31~ BEGIN
		ACTION_IF (FILE_EXISTS_IN_GAME ~%shield%a.itm~) BEGIN
			COPY_EXISTING ~%shield%a.itm~ ~1pp/temp.itm~
			COPY_EXISTING ~%shield%.itm~ ~override/%shield%a.itm~
			COPY ~1pp/temp.itm~ ~override/%shield%.itm~
		END
	END

END	// of ACTION_IF (1pp_shields_appearance = 2)



/* ============================= *
 *          NEW SHIELDS          *
 * ============================= */

PRINT @400014 // ~Installing new shields...~
SILENT

// Wall of the North +2
ACTION_IF (FILE_EXISTS_IN_GAME ~shld23a.itm~) BEGIN
	COPY_EXISTING ~shld23a.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400501
			SAY DESC  @400502
			LPF DELETE_EFFECT INT_VAR check_headers = 0 match_opcode = 0 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 3 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 5 parameter2 = 2 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 86 target = 1 timing = 2 parameter1 = 15 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 88 target = 1 timing = 2 parameter1 = 15 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 84 target = 1 timing = 2 parameter1 = 70 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 30 target = 1 timing = 2 parameter1 = 70 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 85 target = 1 timing = 2 parameter1 = "-20" END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 28 target = 1 timing = 2 parameter1 = "-20" END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 timing = 2 parameter2 = 16 END
		END
END

// Polished Shield +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld24a.itm~) BEGIN
	COPY_EXISTING ~shld24a.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400503
			SAY DESC  @400504
			LPF DELETE_EFFECT INT_VAR check_headers = 0 match_opcode = 197 END
			PATCH_FOR_EACH par2_197 IN 64 225 23 248 189 212 92 36 252 41 208 270 218 40 BEGIN
				LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 197 target = 1 timing = 2 parameter2 = EVAL "%par2_197%" END
			END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 101 target = 1 timing = 2 parameter2 = 134 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 timing = 2 parameter2 = 10 END
		END
END

// Font of Virtue +2
ACTION_IF (FILE_EXISTS_IN_GAME ~shld26a.itm~) BEGIN
	COPY_EXISTING ~shld26a.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400505
			SAY DESC  @400506
			LPF DELETE_EFFECT INT_VAR check_headers = 0 match_opcode = 142 END
			LPF DELETE_EFFECT INT_VAR check_headers = 0 match_opcode = 166 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 49 target = 1 timing = 2 parameter1 = 1 END
		END
END

// Tahcaluss +3
ACTION_IF (FILE_EXISTS_IN_GAME ~shld27a.itm~) BEGIN
	COPY_EXISTING ~shld27a.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400507
			SAY DESC  @400508
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 78 target = 1 timing = 2 parameter1 = 65 parameter2 = 3 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 10 target = 1 timing = 2 parameter1 = 80 parameter2 = 2 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 timing = 2 parameter2 = 39 END
		END
END

// Gorm's Arm +3
ACTION_IF (FILE_EXISTS_IN_GAME ~shld31a.itm~) BEGIN
	COPY_EXISTING ~shld31a.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400509
			SAY DESC  @400510
			WRITE_SHORT 0x26 17	// Minimum strength ==> Gwen fix (wrong coding): WRITE_SHORT instead of WRITE_BYTE
			WRITE_LONG  0x4c 20	// Weight
			PATCH_FOR_EACH opcode_to_delete IN 142 27 28 173 30 BEGIN
				LPM DELETE_ITEM_EQEFFECT
			END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 166 target = 1 timing = 2 parameter1 = 50 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 timing = 2 parameter2 = 28 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 145 target = 1 timing = 2 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 145 target = 1 timing = 2 parameter2 = 1 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 145 target = 1 timing = 2 parameter2 = 2 END
		END
END

// Buckler +2
ACTION_IF (FILE_EXISTS_IN_GAME ~shld17a.itm~) BEGIN
	COPY_EXISTING ~shld17a.itm~ ~override/shld01p.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400511
			SAY DESC  @400512
			WRITE_ASCII 0x3A ~1SHLD172~ #8
			WRITE_ASCII 0x58 ~CSHLD09~ #8
			WRITE_LONG  0x34 2500			// Gwen fix: add Price
			LPF DELETE_EFFECT INT_VAR check_headers = 0 match_opcode = 0 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = "-3" parameter2 = 4 END // Gwen fix: missing protection vs piercing weapons
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = "-3" parameter2 = 2 END	// Gwen fix: parameter1 (0xfffffe = 16777214???) should be -3
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 3 END
			LPM ~clear~
			SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER 
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 215				// sets colour index 215 GYPSY_MINOR-CHROME_VERMILLION
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 222				// sets colour index 222 DROW_HAIR-PLATINUM_GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 210			// sets colour index 210 MERCHANT_MAJOR-AMBER 
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
END

// High Quality Large Shield
ACTION_IF (FILE_EXISTS_IN_GAME ~shld15.itm~) BEGIN
	COPY_EXISTING ~shld15.itm~ ~override/shld02p.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400513
			SAY DESC  @400514
			WRITE_ASCII 0x22 ~C6~
			WRITE_ASCII 0x3A ~1SHLDL01~ #8
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDL1~ #8
			WRITE_SHORT 0x26 10				// Minimum strength
			WRITE_LONG  0x34 180			// Price
			WRITE_LONG  0x4c 10				// Weight
			LPM ~clear~
			SET gradient = 217				// sets colour index 217 PIRATE_MINOR-BRIGHT_SLATE_GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 244				// sets colour index 244 FIGHTER_MINOR-DARK_CADET_GRAY
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 217				// sets colour index 217 PIRATE_MINOR-BRIGHT_SLATE_GRAY
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 244				// sets colour index 244 FIGHTER_MINOR-DARK_CADET_GRAY
			SET location = spink			// location (Panel)
			LPM ~colour~
		END
	BUT_ONLY
END

// High Quality Medium Shield and Medium shield
ACTION_IF (FILE_EXISTS_IN_GAME ~shld14.itm~) BEGIN
	COPY_EXISTING ~shld14.itm~ ~override/shld03p.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400515 /* High Quality Medium Shield */
			SAY DESC  @400516
			WRITE_ASCII 0x22 ~C5~
			WRITE_ASCII 0x3A ~1SHLDM01~ #8
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDM1~ #8
			WRITE_SHORT 0x26 8				// Minimum strength
			WRITE_LONG  0x34 130			// Price
			WRITE_LONG  0x4c 4				// Weight
			LPM ~clear~
			SET gradient = 110				// sets colour index 110 ASH
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 144				// sets colour index 144 DARK_SALMON
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 144				// sets colour index 144 DARK_SALMON
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 144				// sets colour index 144 DARK_SALMON
			SET location = spink			// location (Panel)
			LPM ~colour~
		END
	BUT_ONLY

	COPY_EXISTING ~shld14.itm~ ~override/shld04p.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C3~
			WRITE_ASCII 0x3A ~ISHLDM06~ #8
			WRITE_ASCII 0x58 ~CSHLD29~ #8
			LPM ~clear~
			SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 242				// sets colour index 242 THIEF_MINOR-PALE_OLIVE
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 102				// sets colour index 102 SEA_BLUE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 93			// sets colour index 93 DARK_CEMENT_GRAY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Corvyr's Blessing
ACTION_IF (FILE_EXISTS_IN_GAME ~shld04.itm~) BEGIN
	COPY_EXISTING ~shld04.itm~ ~override/shld05p.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400517
			SAY DESC  @400518
			WRITE_ASCII 0x22 ~C3~
			WRITE_ASCII 0x3A ~ISHLDM07~ #8
			WRITE_ASCII 0x58 ~CSHLD26~ #8
			WRITE_LONG  0x34 2400			// Price
			LPF DELETE_EFFECT INT_VAR check_headers = 0 match_opcode = 0 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 1 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 33 target = 1 timing = 2 parameter1 = 150 parameter2 = 2 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 10 target = 1 timing = 2 parameter1 = 1 END
			LPM ~clear~
			SET gradient = 213				// sets colour index 213 TRADE_PEASANT_MINOR-VIRIDIAN
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 232				// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 102				// sets colour index 102 SEA_BLUE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 93			// sets colour index 93 DARK_CEMENT_GRAY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Redshield +1, +4 vs. monstrous
ACTION_IF (FILE_EXISTS_IN_GAME ~shld04.itm~) BEGIN
	COPY_EXISTING ~shld04.itm~ ~override/shld06p.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400519
			SAY DESC  @400520
			WRITE_ASCII 0x22 ~C3~
			WRITE_ASCII 0x3A ~ISHLDM08~ #8
			WRITE_ASCII 0x58 ~CSHLD27~ #8
			WRITE_LONG  0x34 6100			// Price
			// Gwen fix (wrong coding): switch parameter1 and 2, and parameter2 2 (EA.IDS) should be 3 (GENERAL.IDS)
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 219 target = 1 timing = 2 parameter1 = 255 parameter2 = 3 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 219 target = 1 timing = 2 parameter1 = 255 parameter2 = 3 END
			// Gwen fix (wrong coding): replace opcode #178 with opcode 177 and add an external effect
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 timing = 2 parameter2 = 2 STR_VAR resource = SHLD06P END
			LPM ~clear~
			SET gradient = 234				// sets colour index 234 HOBGOBLIN_MINOR-INDIAN_RED
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 211				// sets colour index 211 MERCHANT_MINOR-DARK_BRASS
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 253				// sets colour index 253 DUERGAR_MINOR-PALE_TAUPE
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 93			// sets colour index 93 DARK_CEMENT_GRAY
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
	COPY ~1pp/item/1ppv4_update/item/shld06p.eff~ ~override~
END

// Sartessa's Vengeance +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld05.itm~) BEGIN
	COPY_EXISTING ~shld05.itm~ ~override/shld07p.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400521
			SAY DESC  @400522
			WRITE_ASCII 0x22 ~C6~
			WRITE_ASCII 0x3A ~1SHLDL04~ #8
			WRITE_ASCII 0x58 ~1CSHLDL4~ #8
			WRITE_SHORT	0x26 3				// Minimum strength
			WRITE_SHORT	0x32 12				// Minimum charisma
			WRITE_LONG  0x34 14900			// Price
			WRITE_SHORT 0x42 100			// Lore to identify
			WRITE_LONG  0x4c 5				// Weight
			WRITE_LONG  0x60 7				// Enchantment
			WRITE_LONG  0x1e 0xfd5ffbda		// Usable by
			WRITE_LONG  0x18 (THIS | BIT6)	// Gwen fix (wrong coding): add magical flag - replaces WRITE_BYTE 0x1b 0x6c
			LPF DELETE_EFFECT INT_VAR check_headers = 0 match_opcode = 0 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 175 target = 1 timing = 2 parameter1 = 1 parameter2 = 7 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 2 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 timing = 2 parameter1 = 2 parameter2 = 2 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 219 target = 1 timing = 2 parameter1 = 1 parameter2 = 3 END	// GENERAL = HUMANOID
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 219 target = 1 timing = 2 parameter1 = 1 parameter2 = 7 END	// GENDER = MALE
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 219 target = 1 timing = 2 parameter1 = 5 parameter2 = 2 END	// EA = CONTROLLED
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 219 target = 1 timing = 2 parameter1 = 6 parameter2 = 2 END	// EA = CHARMED
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 188 target = 1 timing = 2 parameter2 = 1 END					// Cleansed aura
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 292 target = 1 timing = 2 parameter2 = 1 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 295 target = 1 timing = 9 parameter2 = 1 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 301 target = 1 timing = 2 parameter1 = 7 END
			LPM ~clear~
			SET gradient = 232				// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 54			// sets colour index 54 DARK_GREEN
				SET location = steal		// location
				LPM ~colour~
			END
			SET gradient = 205				// sets colour index 205 NOBLE_MINOR2-CHROME_GRAY
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 230			// sets colour index KOBOLD_MAJOR-DEEP_AVOCADO
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Tarloc's Contingency +1 : code simplified
ACTION_IF (FILE_EXISTS_IN_GAME ~shld04.itm~) BEGIN
	COPY_EXISTING ~shld04.itm~ ~override/shld08p.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400523
			SAY DESC  @400524
			WRITE_ASCII 0x22 ~C5~
			WRITE_ASCII 0x3A ~1SHLDM03~ #8
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDM3~ #8
			WRITE_SHORT	0x26 10				// Minimum strength
			WRITE_LONG  0x1E 0x6073ffc0		// Usable by
			WRITE_LONG  0x34 24700			// Price
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 232 target = 1 timing = 2 parameter2 = 11 STR_VAR resource = 1TARSS END					// Took damage
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 232 target = 1 timing = 2 probability1 = 20 parameter2 = 2 STR_VAR resource = 1TARSP END	// HP < 50 %
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 232 target = 1 timing = 2 probability1 = 5 STR_VAR resource = SPWI405 END				// Hit
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 232 target = 1 timing = 2 parameter2 = 4 STR_VAR resource = SPWI413 END					// HP < 10 %
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 232 target = 1 timing = 2 parameter2 = 5 STR_VAR resource = SPWI413 END					// Helpless
			LPM ~clear~
			SET gradient = 232				// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 50				// sets colour index 50 DARK_YELLOW
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 66				// sets colour index 66 FADED_BLACK
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 66			// sets colour index 66 FADED_BLACK
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~spin737.spl~) BEGIN
	COPY_EXISTING ~spin737.spl~ ~override/1tarsp.spl~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPF ALTER_EFFECT INT_VAR target = 2 END
		END
	BUT_ONLY
END

// Gwen fix: wrong coding for Casting sound
ACTION_IF (FILE_EXISTS_IN_GAME ~spwi403.spl~) BEGIN
	COPY_EXISTING ~spwi403.spl~ ~override/1tarss.spl~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x10 ~~ #8			// Casting sound
			WRITE_SHORT 0x22 0				// Casting animation
		END
	BUT_ONLY
END

// Shield of Devotion +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld04.itm~) BEGIN
	COPY_EXISTING ~shld04.itm~ ~override/shld09p.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			SAY NAME2 @400525
			SAY DESC  @400526
			WRITE_ASCII 0x22 ~C5~
			WRITE_ASCII 0x3A ~1SHLDM04~ #8
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDM4~ #8
			WRITE_LONG  0x1E 0x606ffb40
			WRITE_SHORT	0x26 10				// Minimum strength
			WRITE_LONG  0x34 7200			// Price
			WRITE_SHORT 0x42 65				// Lore to identify
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 62 target = 1 timing = 2 parameter1 = 1 parameter2 = 1 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 62 target = 1 timing = 2 parameter1 = 1 parameter2 = 2 END
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 62 target = 1 timing = 2 parameter1 = 1 parameter2 = 4 END	// Gwen fix (wrong coding): Level3 should be 4 (not 3)
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 18 target = 1 timing = 2 parameter1 = 110 parameter2 = 2 END
			LPM ~clear~
			SET gradient = 194				// sets colour index 194 STEEL_PINK
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 127				// sets colour index 127 DARK_BRICK_RED
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 127				// sets colour index 127 DARK_BRICK_RED
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 167			// sets colour index 167 PALE_THISTLE
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END



/* ============================= *
 *          MOD SHIELDS          *
 * ============================= */

PRINT @400015 // ~Patching mod items (if found)...~
SILENT

/* ------------------------- *
 *  The BG1 NPC Project mod  *
 * ------------------------- */

// Ilvastarr Family Shield: typo fixed (X#AJSHLD instead of #AJSHLD)
ACTION_IF (FILE_EXISTS_IN_GAME ~x#ajshld.itm~) BEGIN
	COPY_EXISTING ~x#ajshld.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C6~
			WRITE_ASCII 0x3A ~1SHLDAJ~ #8	// replaces X#ISHAJ
			WRITE_ASCII 0x44 ~GLSHLD~ #8	// replaces _GSHLD03
			WRITE_ASCII 0x58 ~1CSHLDAJ~ #8	// replaces X#CSHAJ
			LPM ~clear~
			SET gradient = 226				// sets colour index 226 METAL_NORMAL-EIGENGRAU
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 90				// sets colour index 90 MOLDY_GOLD
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 226				// sets colour index 226 METAL_NORMAL-EIGENGRAU
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 20			// sets colour index 20 DARK_MOLDY_GREEN
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Great shield White Oak
ACTION_IF (FILE_EXISTS_IN_GAME ~x#fash01.itm~) BEGIN
	COPY_EXISTING ~x#fash01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~C6~
			WRITE_ASCII 0x3A ~1SHLDL04~ #8	// replaces ISHLD01
			WRITE_ASCII 0x44 ~GLSHLD~ #8
			WRITE_ASCII 0x58 ~1CSHLDL4~ #8	// replaces CSHLD03
			LPM ~clear~
			SET gradient = 232				// sets colour index 232 HOBGOBLIN_SKIN-CINDER_GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			SET gradient = 54				// sets colour index 54 DARK_GREEN
			SET location = steal			// location (Interior)
			LPM ~colour~
			SET gradient = 205				// sets colour index 205 NOBLE_MINOR2-CHROME_GRAY
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 230			// sets colour index KOBOLD_MAJOR-DEEP_AVOCADO
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
	BUT_ONLY
END


/* ------------ *
 *  Rolles mod  *
 * ------------ */

// Enhanced Shield of Balduran
ACTION_IF (FILE_EXISTS_IN_GAME ~s#shld01.itm~) BEGIN
	COPY_EXISTING ~s#shld01.itm~ ~override~
		LPF ~1pp_wa2shiel~ END
	BUT_ONLY
END


/* ---------------------- *
 *  Song and Silence mod  *
 * ---------------------- */

// Skald's Battered Buckler
ACTION_IF (FILE_EXISTS_IN_GAME ~a!brsb.itm~) BEGIN
	COPY_EXISTING ~a!brsb.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x3A ~1SHLD172~ #8	// replaces A!IBRSB
			WRITE_ASCII 0x44 ~GSHLD08~ #8	// replaces GSSHLD
			WRITE_ASCII 0x58 ~CSHLD09~ #8	// replaces A!CBRSB
			LPM ~clear~
			SET gradient = 210				// sets colour index 210 MERCHANT_MAJOR-AMBER
			SET location = sred				// location (Grip)
			LPM ~colour~
			SET gradient = 215				// sets colour index 215 GYPSY_MINOR-CHROME_VERMILLION
			SET location = sblue			// location (Body/trim)
			LPM ~colour~
			SET gradient = 222				// sets colour index 222 DROW_HAIR-PLATINUM_GRAY
			SET location = sgrey			// location (Hub)
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours = 1 || 1pp_forced_item_colours = 2 || 1pp_forced_item_colours = 3) BEGIN
				SET gradient = 210			// sets colour index 210 MERCHANT_MAJOR-AMBER
				SET location = spink		// location (Panel)
				LPM ~colour~
			END
		END
END


/* ------------------------------- *
 *  The Unusual Oddities Shop mod  *
 * ------------------------------- */

// Shield of the Lords +4
ACTION_IF (FILE_EXISTS_IN_GAME ~r#asshld.itm~) BEGIN
	COPY_EXISTING ~r#asshld.itm~ ~override~
		LPF ~1pp_shld32~ END
	BUT_ONLY
END

// END of COMPONENT SECTION