// Just a short little thing... right

/*  ==============================================================================================================================================================================  *
 *  change-log:                                                                                                                                                                     *
 *  -----------                                                                                                                                                                     *
 *      - Variables needed for installation (1pp_forced_item_colours_iwd and 1pp_gemlore) are read from 1pp-config-default.ini or 1pp-config.ini files.                             *
 *        The previous version interrupted installation with plain text prompts allowing players to customise components to their liking (depending on which IE game the mod is     *
 *        installed for and already installed components). All those variables set during installation have been moved into 1pp-config-default.ini file in 1pp folder. This file    *
 *        provides a standard installation. If players want to define their own customized installation, they have to modify the variables involved in 1pp-config-default.ini and   *
 *        save this file as 1pp-config.ini. The installation process will read both ini files and prioritize user values. If a value is not set or mismatched in 1pp-config.ini,    *
 *        the installation process will prevent any installation failure by reverting it back to its default value.                                                                 *
 *      -  Gems sub-component (#989) : code simplified and re-written to avoid overwriting files when selecting option no lore needed for identification (1pp_gemlore = 2). Builds  *
 *         an array to define new gems lore values to identify. Same tph used for IWD and BG2 games.                                                                                *
 *      - Replace macros with functions whenever possible.                                                                                                                          *
 *      - Coding simplification:                                                                                                                                                    *
 *  		Replace WRITE_LONG 0x3E 0 and WRITE_ASCII 0x3A ~ISHLDS01~ with WRITE_ASCII 0x3A ~ISHLDS01~ #8. Id. with offsets 0x48 0x44, and 0x5C 0x58.                               *
 *  		Group actions or patches with ACTION_FOR_EACH and PATCH_FOR_EACH whenever possible.                                                                                     *
 *  ==============================================================================================================================================================================  */

PRINT @400002 /* Copying resources... */

ACTION_FOR_EACH resource IN ~GBOW02~ ~GBSHLD~ ~GLSHLD~ ~GMSHLD~ ~GQUIVER0~ ~GSSHLD~ ~1HELM00~ ~1HELM03~ ~1HELM04~ ~1HELM06~ ~1HELM17~ ~1HELM18~ ~1HELM20~ ~IDART01~ BEGIN
	COPY ~1pp/item/1ppv4_update/bam/%resource%.bam~ ~override~
END


ACTION_FOR_EACH resource IN ~1CHELM01~ ~1CHELM02~ ~1CHELM03~ ~1CHELM04~ ~1CHELM05~ ~1CHELM06~ ~1CHELM07~ BEGIN
	COPY ~1pp/additions/carried_1pp/%resource%.bam~ ~override~
END

LAM ~Locations~

/*  ========  *
 *  SHIELDS   *
 *  ========  */

// Small Shield
ACTION_IF (FILE_EXISTS_IN_GAME ~shld01.itm~) BEGIN
	COPY_EXISTING ~shld01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			SET gradient = 22			// colour index
			SET location = sred			// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 92		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Small Shield +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld02.itm~) BEGIN
	COPY_EXISTING ~shld02.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			SET gradient = 109			// colour index
			SET location = sred			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Medium Shield
ACTION_IF (FILE_EXISTS_IN_GAME ~shld03.itm~) BEGIN
	COPY_EXISTING ~shld03.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 94			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 100			// colour index
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 215			// Replace colour index 70
			SET location = sgrey		// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 66		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Medium Shield +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld04.itm~) BEGIN
	COPY_EXISTING ~shld04.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 81			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 250			// Replace colour index 99
			SET location = sgrey		// location
			LPM ~colour~
			SET gradient = 98			// Replace colour index 30
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 160			// colour index
			SET location = spink		// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Large Shield
ACTION_IF (FILE_EXISTS_IN_GAME ~shld05.itm~) BEGIN
	COPY_EXISTING ~shld05.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 91			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 6			// Replace colour index 28
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 26			// Replace colour index 111
			SET location = sgrey		// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 87		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Large Shield +1
ACTION_IF (FILE_EXISTS_IN_GAME ~shld06.itm~) BEGIN
	COPY_EXISTING ~shld06.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 99			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 30			// colour index
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 112			// Replace colour index 7
			SET location = sgrey		// location
			LPM ~colour~
			SET gradient = 237			// Replace colour index 8
			SET location = spink		// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Large Shield +1, +4 vs. Missiles
ACTION_IF (FILE_EXISTS_IN_GAME ~shld07.itm~) BEGIN
	COPY_EXISTING ~shld07.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 3			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 16			// Replace colour index 25
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 208			// Replace colour index 25
			SET location = sgrey		// location
			LPM ~colour~
			SET gradient = 66			// colour index
			SET location = spink		// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Bucklers
ACTION_IF (FILE_EXISTS_IN_GAME ~shld08.itm~) BEGIN
	COPY_EXISTING ~shld08.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 27			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 28			// colour index
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 30			// colour index
			SET location = sgrey		// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 92		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld09.itm~) BEGIN
	COPY_EXISTING ~shld09.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 209			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 22			// colour index
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 23			// colour index
			SET location = sgrey		// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 209		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld10.itm~) BEGIN
	COPY_EXISTING ~shld10.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 26			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 28			// colour index
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 26			// colour index
			SET location = sgrey		// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 179		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Small Shields
ACTION_IF (FILE_EXISTS_IN_GAME ~shld11.itm~) BEGIN
	COPY_EXISTING ~shld11.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 81			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 28			// colour index
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 30			// colour index
			SET location = sgrey		// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 188		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld12.itm~) BEGIN
	COPY_EXISTING ~shld12.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 72			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 27			// colour index
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 30			// colour index
			SET location = sgrey		// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 99		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Medium shields
ACTION_IF (FILE_EXISTS_IN_GAME ~shld13.itm~) BEGIN
	COPY_EXISTING ~shld13.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 174			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 100			// colour index
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 176			// Replace colour index 59
			SET location = sgrey		// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 183		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld14.itm~) BEGIN
	COPY_EXISTING ~shld14.itm~ ~override/shld14A.itm~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 92			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 30			// colour index
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 242			// Replace colour index 10
			SET location = sgrey		// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 39		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Large Shields
ACTION_IF (FILE_EXISTS_IN_GAME ~shld15.itm~) BEGIN
	COPY_EXISTING ~shld15.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 92			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 27			// colour index
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 215			// Replace colour index 19
			SET location = sgrey		// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 254		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~shld16.itm~) BEGIN
	COPY_EXISTING ~shld16.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 100			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 248			// Replace colour index 28
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 109			// Replace colour index 19
			SET location = sgrey		// location
			LPM ~colour~
			PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 238		// colour index
				SET location = spink	// location
				LPM ~colour~
			END
		END
	BUT_ONLY
END

// Gwen: does not exist in the game?
ACTION_IF (FILE_EXISTS_IN_GAME ~shld17.itm~) BEGIN
	COPY_EXISTING ~shld17.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
			LPM ~clear~
			SET gradient = 66			// colour index
			SET location = sred			// location
			LPM ~colour~
			SET gradient = 90			// colour index
			SET location = sblue		// location
			LPM ~colour~
			SET gradient = 208			// colour index
			SET location = sgrey		// location
			LPM ~colour~
			SET gradient = 66			// colour index
			SET location = spink		// location
			LPM ~colour~
		END
	BUT_ONLY
END


/*  ----------------------------------------------------------------  *
 *  Content related to Additional Shield Animations (core) component  *
 *  ----------------------------------------------------------------  */
ACTION_IF (MOD_IS_INSTALLED ~1pp.tp2~ 206) BEGIN

// The Bitch Queen's Envoy
	ACTION_IF (FILE_EXISTS_IN_GAME ~shldbch.itm~) BEGIN
		COPY_EXISTING ~shldbch.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
				WRITE_ASCII 0x22 ~C5~			// Replace D3 Medium shield
				WRITE_ASCII 0x44 ~GLSHLD~ #8	// Replace GSHLD01
				LPM ~clear~
				SET gradient = 236				// Replace colour index 15
				SET location = sgrey			// location
				LPM ~colour~
				SET gradient = 105				// Replace colour index 57
				SET location = steal			// location
				LPM ~colour~
				SET gradient = 220				// Replace colour index 57
				SET location = spink			// location
				LPM ~colour~
				SET gradient = 220				// Replace colour index 0
				SET location = sblue			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// The Red Knight's Shield
	ACTION_IF (FILE_EXISTS_IN_GAME ~shldred.itm~) BEGIN
		COPY_EXISTING ~shldred.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN 
				WRITE_ASCII 0x22 ~C5~			// Replace D3 Medium shield
				WRITE_ASCII 0x44 ~GLSHLD~ #8	// Replace GSHLD03
				LPM ~clear~
				SET gradient = 249				// Replace colour index 101
				SET location = sgrey			// location
				LPM ~colour~
				SET gradient = 99				// Replace colour index 47
				SET location = steal			// location
				LPM ~colour~
				SET gradient = 195				// Replace colour index 47
				SET location = spink			// location
				LPM ~colour~
				SET gradient = 99				// Replace colour index 43
				SET location = sblue			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

END

/*  ----------------------------------------------------------------  *
 *  Content related to Additional Helmet Animations (core) component  *
 *  ----------------------------------------------------------------  */
ACTION_IF (MOD_IS_INSTALLED ~1pp.tp2~ 208) BEGIN

	PRINT @400015 /* Installing helmet compatibility... */

	ACTION_FOR_EACH set IN ~H0~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J6%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H1~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J7%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H2~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J8%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H3~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J9%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H4~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%J8%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END

	ACTION_FOR_EACH set IN ~H5~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~N~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A2~ ~A3~ ~A4~ ~A5~ ~A6~ ~A7~ ~A8~ ~A9~ ~CA~ ~G1~ ~SA~ ~SS~ ~SX~ BEGIN
				COPY_EXISTING ~WQ%category%JA%sequence%.BAM~ ~override/WQ%category%%set%%sequence%.BAM~
			END
		END
	END


// Helmet
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm01.itm~) BEGIN
		COPY_EXISTING ~helm01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H0~			// Replace H0
				LPM ~clear~
				SET gradient = 223				// Replace colour index 42
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 27				// Replace colour index 42
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 27				// colour index
				SET location = hpink			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

// Helmet of Opposite Alignment
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm02.itm~) BEGIN
		COPY_EXISTING ~helm02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// Replace H4
				WRITE_ASCII 0x3A ~1HELM06~ #8	// Replace IHELM04
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// Replace CHELM02
				LPM ~clear~
				SET gradient = 249				// Replace colour index 97
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 0				// colour index
				SET location = hpink			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

// Helm of Glory
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm03.itm~) BEGIN
		COPY_EXISTING ~helm03.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H2~			// Replace H2
				//WRITE_ASCII 0x3A ~1HELM06~ #8
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 224				// Replace colour index 25
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 90				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 30				// Replace colour index 27
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 30				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 30				// colour index
				SET location = hpink			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

// Helmet of Defense
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm04.itm~) BEGIN
		COPY_EXISTING ~helm04.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H5~			// Replace H5
				//WRITE_ASCII 0x3A ~1HELM06~ #8
				WRITE_ASCII 0x58 ~1CHELM04~ #8	// Replace CHELM04
				LPM ~clear~
				SET gradient = 0				// Replace colour index 13
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 59
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 5				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 5				// colour index
				SET location = hpink			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

// Helmet of Infravision
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm05.itm~) BEGIN
		COPY_EXISTING ~helm05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM20~ #8	// Replace IHELM05
				WRITE_ASCII 0x58 ~1CHELM02~ #8	// Replace CHELM05
				LPM ~clear~
				SET gradient = 0				// Replace colour index 27
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 99				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 195				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 210				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

// Helmet of Charm Protection
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm06.itm~) BEGIN
		COPY_EXISTING ~helm06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JA~			// Replace H3
				WRITE_ASCII 0x3A ~1HELM18~ #8	// Replace IHELM03
				WRITE_ASCII 0x58 ~1CHELM02~ #8	// Replace CHELM06
				LPM ~clear~
				SET gradient = 0				// Replace colour index 39
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 119				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 118				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
				END
		BUT_ONLY
	END

// Helm of Balduran
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm07.itm~) BEGIN
		COPY_EXISTING ~helm07.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J7~			// Replace H1
				WRITE_ASCII 0x3A ~1HELM00~ #8	// Replace IHELM01
				WRITE_ASCII 0x58 ~CHELM07~ #8	// Replace CHELM07
				LPM ~clear~
				SET gradient = 223				// Replace colour index 42
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hpink			// location
				LPM ~colour~
				SET gradient = 66				// Replace colour index 27
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				//PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
				SET gradient = 173				// colour index
				SET location = hteal			// location
				LPM ~colour~
				//END
			END
		BUT_ONLY
	END

// Helmets
	ACTION_IF (FILE_EXISTS_IN_GAME ~helm08.itm~) BEGIN
		COPY_EXISTING ~helm08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// Replace H4
				WRITE_ASCII 0x3A ~1HELM03~ #8	// Replace IHELM04
				LPM ~clear~
				SET gradient = 119				// Replace colour index 25
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 205				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 209				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 102				// colour index
				SET location = hteal			// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 0			// colour index
					SET location = hpink		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm09.itm~) BEGIN
		COPY_EXISTING ~helm09.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H3~			// Replace H3
				//WRITE_ASCII 0x3A ~1HELM03~ #8
				WRITE_ASCII 0x58 ~1CHELM06~ #8	// Replace CHELM06
				LPM ~clear~
				SET gradient = 27				// Replace colour index 39
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hteal			// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 195			// colour index
					SET location = hpink		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm10.itm~) BEGIN
		COPY_EXISTING ~helm10.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H5~			// Replace H5
				//WRITE_ASCII 0x3A ~1HELM03~ #8
				WRITE_ASCII 0x58 ~1CHELM05~ #8	// Replace CHELM05
				LPM ~clear~
				SET gradient = 27				// colour index
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 47			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 127			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm11.itm~) BEGIN
		COPY_EXISTING ~helm11.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J8~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM04~ #8	// Replace IHELM05
				WRITE_ASCII 0x58 ~1CHELM03~ #8	// Replace CHELM05
				LPM ~clear~
				SET gradient = 248				// Replace colour index 104
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 104
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 0				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 202			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 202			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm12.itm~) BEGIN
		COPY_EXISTING ~helm12.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JC~			// Replace H2
				WRITE_ASCII 0x3A ~IHELM04~ #8	// Replace IHELM02
				WRITE_ASCII 0x58 ~1CHELM02~ #8	// Replace CHELM03
				LPM ~clear~
				SET gradient = 235				// Replace colour index 24
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 24
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 102				// Replace colour index 24
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 232			// colour index
					SET location = hpink		// location
					LPM ~colour~
					SET gradient = 232			// colour index
					SET location = hteal		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helm13.itm~) BEGIN
		COPY_EXISTING ~helm13.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// Replace H5
				WRITE_ASCII 0x3A ~1HELM17~ #8	// Replace IHELM05
				WRITE_ASCII 0x58 ~CHELM06~ #8	// Replace CHELM05
				LPM ~clear~
				SET gradient = 223				// Replace colour index 94
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 27				// Replace colour index 94
				SET location = hteal			// location
				LPM ~colour~
				SET gradient = 27				// Replace colour index 94
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 224				// colour index
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 195			//Replace colour index 94
					SET location = hpink		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

	ACTION_IF (FILE_EXISTS_IN_GAME ~helmblk.itm~) BEGIN
		COPY_EXISTING ~helmblk.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~H4~			// Replace H4
				LPM ~clear~
				SET gradient = 254				// Replace colour index 21
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 248				// colour index
				SET location = hteal			// location
				LPM ~colour~
				SET gradient = 191				// Replace colour index 21
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 254				// Replace colour index 21
				SET location = hred				// location
				LPM ~colour~
				PATCH_IF (1pp_forced_item_colours_iwd = 2) BEGIN
					SET gradient = 136			// colour index
					SET location = hpink		// location
					LPM ~colour~
				END
			END
		BUT_ONLY
	END

// Dead Man's Face
	ACTION_IF (FILE_EXISTS_IN_GAME ~helmded.itm~) BEGIN
		COPY_EXISTING ~helmded.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J3~			// Replace H2
				LPM ~clear~
				SET gradient = 254				// Replace colour index 42
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 226				// Replace colour index 43
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 239				// colour index
				SET location = hred				// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Blessed Helm of Lathander
	ACTION_IF (FILE_EXISTS_IN_GAME ~helmla.itm~) BEGIN
		COPY_EXISTING ~helmla.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J6~			// Replace H0
				LPM ~clear~
				SET gradient = 2				// Replace colour index 42
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 127				// colour index
				SET location = hteal			// location
				LPM ~colour~
				SET gradient = 92				// Replace colour index 98
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 91				// Replace colour index 42
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 127				// colour index
				SET location = hpink			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Helm of Shouting
	ACTION_IF (FILE_EXISTS_IN_GAME ~helmsh.itm~) BEGIN
		COPY_EXISTING ~helmsh.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~J9~			// Replace H0
				LPM ~clear~
				SET gradient = 25				// Replace colour index 99
				SET location = hgrey			// location
				LPM ~colour~
				SET gradient = 66				// colour index
				SET location = hteal			// location
				LPM ~colour~
				SET gradient = 232				// Replace colour index 30
				SET location = hblue			// location
				LPM ~colour~
				SET gradient = 249				// Replace colour index 99
				SET location = hred				// location
				LPM ~colour~
				SET gradient = 127				// colour index
				SET location = hpink			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Sune's Laurel of Favor
	ACTION_IF (FILE_EXISTS_IN_GAME ~helmsun.itm~) BEGIN
		COPY_EXISTING ~helmsun.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~JB~			// Replace None
				LPM ~clear~
				SET gradient = 201				// colour index
				SET location = hred				// location
				LPM ~colour~
			END
		BUT_ONLY
	END

END // HELMETS END


/*  ====  *
 *  GEMS  *
 *  ====  */
INCLUDE ~%MOD_FOLDER%/components/400_update_gemlore.tpa~


/*  =========  *
 *  LAUNCHERS  *
 *  =========  */

// Sling
ACTION_IF (FILE_EXISTS_IN_GAME ~slng01.itm~) BEGIN
	COPY_EXISTING ~slng01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~SL~
			LPM ~clear~
			SET gradient = 99				// Replace colour index 22
			SET location = wred				// location
			LPM ~colour~
			SET gradient = 91				// colour index
			SET location = wblue			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Sling +1
ACTION_IF (FILE_EXISTS_IN_GAME ~slng02.itm~) BEGIN
	COPY_EXISTING ~slng02.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~SL~
			LPM ~clear~
			SET gradient = 209				// Replace colour index 28
			SET location = wred				// location
			LPM ~colour~
			SET gradient = 90				// colour index
			SET location = wblue			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Edley's Sling
 ACTION_IF (FILE_EXISTS_IN_GAME ~slinged.itm~) BEGIN
	COPY_EXISTING ~slinged.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~SL~
			LPM ~clear~
			SET gradient = 240				// Replace colour index 22
			SET location = wred				// location
			LPM ~colour~
			SET gradient = 238				// colour index
			SET location = wblue			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Heavy Crossbow
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow01.itm~) BEGIN
	COPY_EXISTING ~xbow01.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 6				// Replace colour index 27
			SET location = wgrey			// location
			LPM ~colour~
			SET gradient = 92				// Replace colour index 40
			SET location = wred				// location
			LPM ~colour~
			SET gradient = 28				// colour index
			SET location = wblue			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Heavy Crossbow +1
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow02.itm~) BEGIN
	COPY_EXISTING ~xbow02.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 159				// Replace colour index 31
			SET location = wgrey			// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = wred				// location
			LPM ~colour~
			SET gradient = 202				// Replace colour index 27
			SET location = wblue			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Heavy Crossbow of Accuracy 
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow03.itm~) BEGIN
	COPY_EXISTING ~xbow03.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 83				// Replace colour index 25
			SET location = wgrey			// location
			LPM ~colour~
			SET gradient = 240				// Replace colour index 29
			SET location = wred				// location
			LPM ~colour~
			SET gradient = 25				// colour index
			SET location = wblue			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Light Crossbow
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow04.itm~) BEGIN
	COPY_EXISTING ~xbow04.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 27				// colour index
			SET location = wgrey			// location
			LPM ~colour~
			SET gradient = 99				// Replace colour index 9
			SET location = wred				// location
			LPM ~colour~
			SET gradient = 10				// colour index
			SET location = wblue			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Light Crossbow +1
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow05.itm~) BEGIN
	COPY_EXISTING ~xbow05.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 138				// Replace colour index 27
			SET location = wgrey			// location
			LPM ~colour~
			SET gradient = 184				// Replace colour index 27
			SET location = wred				// location
			LPM ~colour~
			SET gradient = 27				// colour index
			SET location = wblue			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Light Crossbow of Speed 
ACTION_IF (FILE_EXISTS_IN_GAME ~xbow06.itm~) BEGIN
	COPY_EXISTING ~xbow06.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			//WRITE_ASCII 0x22 ~XB~
			LPM ~clear~
			SET gradient = 91				// Replace colour index 100
			SET location = wgrey			// location
			LPM ~colour~
			SET gradient = 209				// Replace colour index 27
			SET location = wred				// location
			LPM ~colour~
			SET gradient = 248				// Replace colour index 30
			SET location = wblue			// location
			LPM ~colour~
		END
	BUT_ONLY
END


/*  ======================================================================  *
 *  Content related to Increased paperdoll object variety (core) component  *
 *  ======================================================================  */
ACTION_IF (MOD_IS_INSTALLED ~1pp.tp2~ 210) BEGIN

// Amaunator's Legacy
	ACTION_IF (FILE_EXISTS_IN_GAME ~amaunat.itm~) BEGIN
		COPY_EXISTING ~amaunat.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Bastard Sword 
	ACTION_IF (FILE_EXISTS_IN_GAME ~ranbswd.itm~) BEGIN
		COPY_EXISTING ~ranbswd.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// The Snow Maiden's Reaver
	ACTION_IF (FILE_EXISTS_IN_GAME ~reaver.itm~) BEGIN
		COPY_EXISTING ~reaver.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace FS Flaming sword
			END
		BUT_ONLY
	END

// Fang
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd1a.itm~) BEGIN
		COPY_EXISTING ~ubswd1a.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Phasing Bastard Sword +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd2a.itm~) BEGIN
		COPY_EXISTING ~ubswd2a.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Flaming Bastard Sword +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd2b.itm~) BEGIN
		COPY_EXISTING ~ubswd2b.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Bastard Sword +2: Life Giver
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd3a.itm~) BEGIN
		COPY_EXISTING ~ubswd3a.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Bastard Sword of Action +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd3b.itm~) BEGIN
		COPY_EXISTING ~ubswd3b.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword	
			END
		BUT_ONLY
	END

// Bastard Sword +3: Defender
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd4a.itm~) BEGIN
		COPY_EXISTING ~ubswd4a.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Bastard Sword of Greater Phasing
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd4b.itm~) BEGIN
		COPY_EXISTING ~ubswd4b.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Bastard Sword +2: Conflagration
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd4c.itm~) BEGIN
		COPY_EXISTING ~ubswd4c.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Cancerous Bastard Sword +4
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd5a.itm~) BEGIN
		COPY_EXISTING ~ubswd5a.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Bastard Sword +3: Incinerator
	ACTION_IF (FILE_EXISTS_IN_GAME ~ubswd5b.itm~) BEGIN
		COPY_EXISTING ~ubswd5b.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Trollslayer
	ACTION_IF (FILE_EXISTS_IN_GAME ~zzg7ts.itm~) BEGIN
		COPY_EXISTING ~zzg7ts.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace FS Flaming sword
			END
		BUT_ONLY
	END

// The Blade of Bael
	ACTION_IF (FILE_EXISTS_IN_GAME ~bael.itm~) BEGIN
		COPY_EXISTING ~bael.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Cynicism
	ACTION_IF (FILE_EXISTS_IN_GAME ~cynicis.itm~) BEGIN
		COPY_EXISTING ~cynicis.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Erevain's Broad Sword
	ACTION_IF (FILE_EXISTS_IN_GAME ~erevain.itm~) BEGIN
		COPY_EXISTING ~erevain.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Dead God's Dreaming
	ACTION_IF (FILE_EXISTS_IN_GAME ~zz36dgd.itm~) BEGIN
		COPY_EXISTING ~zz36dgd.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Hell's Bane
	ACTION_IF (FILE_EXISTS_IN_GAME ~zzc8hb.itm~) BEGIN
		COPY_EXISTING ~zzc8hb.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// High Quality Short Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~hqsbow.itm~) BEGIN
		COPY_EXISTING ~hqsbow.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - Replace BW Long bow
			END
		BUT_ONLY
	END

// Short Bow of Ebullience
	ACTION_IF (FILE_EXISTS_IN_GAME ~sbowebu.itm~) BEGIN
		COPY_EXISTING ~sbowebu.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - Replace BW Long bow
			END
		BUT_ONLY
	END

// Storm Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~storm.itm~) BEGIN
		COPY_EXISTING ~storm.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - Replace BW Long bow
			END
		BUT_ONLY
	END

// Bastard Sword
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h01.itm~) BEGIN
		COPY_EXISTING ~sw1h01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
				LPM ~clear~
				SET gradient = 99				// colour index
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 248				// Replace colour index 5
				SET location = wblue			// location
				LPM ~colour~
				SET gradient = 94				// colour index
				SET location = wred				// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// High Quality Bastard Sword
	ACTION_IF (FILE_EXISTS_IN_GAME ~hqbswrd.itm~) BEGIN
		COPY_EXISTING ~hqbswrd.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
			END
		BUT_ONLY
	END

// Bastard Sword +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h02.itm~) BEGIN
		COPY_EXISTING ~sw1h02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
				LPM ~clear~
				SET gradient = 50				// colour index
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 202				// Replace colour index 97
				SET location = wblue			// location
				LPM ~colour~
				SET gradient = 230				// Replace colour index 93
				SET location = wred				// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Bastard Sword +1, +3 vs. Shapeshifters
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h03.itm~) BEGIN
		COPY_EXISTING ~sw1h03.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~S0~			// Bastard sword - Replace S1 Long sword
				LPM ~clear~
				SET gradient = 232				// Replace colour index 60
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 231				// Replace colour index 59
				SET location = wblue			// location
				LPM ~colour~
				SET gradient = 183				// Replace colour index 45
				SET location = wred				// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Long Sword
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h04.itm~) BEGIN
		COPY_EXISTING ~sw1h04.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 99				// colour index
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 248				// Replace colour index 5
				SET location = wblue			// location
				LPM ~colour~
				SET gradient = 22				// colour index
				SET location = wred				// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Long Sword +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h05.itm~) BEGIN
		COPY_EXISTING ~sw1h05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 6				// colour index
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 110				// Replace colour index 27
				SET location = wblue			// location
				LPM ~colour~
				SET gradient = 94				// colour index
				SET location = wred				// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Long Sword +2
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h06.itm~) BEGIN
		COPY_EXISTING ~sw1h06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 207				// Replace colour index 50
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 254				// Replace colour index 6
				SET location = wblue			// location
				LPM ~colour~
				SET gradient = 93				// colour index
				SET location = wred				// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Short Sword +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h08.itm~) BEGIN
		COPY_EXISTING ~sw1h08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 245				// Replace colour index 27
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = wblue			// location
				LPM ~colour~
				SET gradient = 138				// Replace colour index 74
				SET location = wred				// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Short Sword +2
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h09.itm~) BEGIN
		COPY_EXISTING ~sw1h09.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET gradient = 90				// Replace colour index 99
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 27				// colour index
				SET location = wblue			// location
				LPM ~colour~
				SET gradient = 93				// colour index
				SET location = wred				// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Short Sword of Backstabbing
	ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h10.itm~) BEGIN
		COPY_EXISTING ~sw1h10.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				LPM ~clear~
				SET setr = 37					// Replace colour index 57
				SET setg = 0
				SET setb = 0
				SET speed = 0x2d
				SET location = wblue			// location
				LPM ~pulse~
				SET gradient = 29				// colour index
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 6				// colour index
				SET location = wblue			// location
				LPM ~colour~
				SET gradient = 195				// Replace colour index 76
				SET location = wred				// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Composite Long Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow01.itm~) BEGIN
		COPY_EXISTING ~bow01.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				//WRITE_ASCII 0x22 ~BW~
				LPM ~clear~
				SET gradient = 13				// colour index
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 95				// colour index
				SET location = wred				// location
				LPM ~colour~
				SET gradient = 164				// colour index
				SET location = wblue			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Composite Long Bow +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow02.itm~) BEGIN
		COPY_EXISTING ~bow02.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				//WRITE_ASCII 0x22 ~BW~
				LPM ~clear~
				SET gradient = 226				// Replace colour index 13
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 240				// Replace colour index 13
				SET location = wred				// location
				LPM ~colour~
				SET gradient = 174				// colour index
				SET location = wblue			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Long Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow03.itm~) BEGIN
		COPY_EXISTING ~bow03.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				//WRITE_ASCII 0x22 ~BW~
				LPM ~clear~
				SET gradient = 209				// Replace colour index 85
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 95				// colour index
				SET location = wred				// location
				LPM ~colour~
				SET gradient = 90				// colour index
				SET location = wblue			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Long Bow +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow04.itm~) BEGIN
		COPY_EXISTING ~bow04.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				//WRITE_ASCII 0x22 ~BW~
				LPM ~clear~
				SET gradient = 228				// Replace colour index 65
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 209				// Replace colour index 65
				SET location = wred				// location
				LPM ~colour~
				SET gradient = 90				// colour index
				SET location = wblue			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Short Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow05.itm~) BEGIN
		COPY_EXISTING ~bow05.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - Replace BW Long bow
				WRITE_ASCII 0x44 ~GBOW02~ #8	// Replace GBOW01
				LPM ~clear~
				SET gradient = 13				// colour index
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 95				// colour index
				SET location = wred				// location
				LPM ~colour~
				SET gradient = 237				// Replace colour index 95
				SET location = wblue			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Short Bow +1
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow06.itm~) BEGIN
		COPY_EXISTING ~bow06.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - Replace BW Long bow
				WRITE_ASCII 0x3A ~IBOW06~ #8
				WRITE_ASCII 0x44 ~GBOW02~ #8	// Replace GBOW01
				WRITE_ASCII 0x76 ~IBOW06~ #8
				LPM ~clear~
				SET gradient = 13				// Replace colour index 75
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 238				// Replace colour index 29
				SET location = wred				// location
				LPM ~colour~
				SET gradient = 172				// colour index
				SET location = wblue			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Long Bow of Marksmanship
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow07.itm~) BEGIN
		COPY_EXISTING ~bow07.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				//WRITE_ASCII 0x22 ~BW~
				LPM ~clear~
				SET gradient = 222				// Replace colour index 61
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 6				// Replace colour index 61
				SET location = wred				// location
				LPM ~colour~
				SET gradient = 142				// colour index
				SET location = wblue			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

// Eagle Bow
	ACTION_IF (FILE_EXISTS_IN_GAME ~bow08.itm~) BEGIN
		COPY_EXISTING ~bow08.itm~ ~override~
			PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
				WRITE_ASCII 0x22 ~BS~			// Short bow - Replace BW Long bow
				WRITE_ASCII 0x44 ~GBOW02~ #8	// Replace GBOW01
				LPM ~clear~
				SET gradient = 248				// Replace colour index 13
				SET location = wgrey			// location
				LPM ~colour~
				SET gradient = 235				// Replace colour index 59
				SET location = wred				// location
				LPM ~colour~
				SET gradient = 250				// colour index
				SET location = wblue			// location
				LPM ~colour~
			END
		BUT_ONLY
	END

END // of Increased paperdoll object variety (core) component installed


// Bolt
ACTION_IF (FILE_EXISTS_IN_GAME ~BOLT01.ITM~) BEGIN
	COPY_EXISTING ~BOLT01.ITM~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 27				// colour index
			SET location = wpink			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Bolt +1
ACTION_IF (FILE_EXISTS_IN_GAME ~BOLT02.ITM~) BEGIN
	COPY_EXISTING ~BOLT02.ITM~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 90				// colour index
			SET location = wpink			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Bolt of Lightning
ACTION_IF (FILE_EXISTS_IN_GAME ~BOLT03.ITM~) BEGIN
	COPY_EXISTING ~BOLT03.ITM~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 218				// colour index
			SET location = wpink			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Bolt of Biting 
ACTION_IF (FILE_EXISTS_IN_GAME ~BOLT04.ITM~) BEGIN
	COPY_EXISTING ~BOLT04.ITM~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 252				// colour index
			SET location = wpink			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Bolt of Polymorphing
ACTION_IF (FILE_EXISTS_IN_GAME ~BOLT05.ITM~) BEGIN
	COPY_EXISTING ~BOLT05.ITM~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 227				// colour index
			SET location = wpink			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Bolt +2
ACTION_IF (FILE_EXISTS_IN_GAME ~BOLT06.ITM~) BEGIN
	COPY_EXISTING ~BOLT06.ITM~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 81				// colour index
			SET location = wpink			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Bullet
ACTION_IF (FILE_EXISTS_IN_GAME ~BULL01.ITM~) BEGIN
	COPY_EXISTING ~BULL01.ITM~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 27				// colour index
			SET location = wgrey			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Bullet +1
ACTION_IF (FILE_EXISTS_IN_GAME ~BULL02.ITM~) BEGIN
	COPY_EXISTING ~BULL02.ITM~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 218				// colour index
			SET location = wgrey			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Bullet +2
ACTION_IF (FILE_EXISTS_IN_GAME ~BULL03.ITM~) BEGIN
	COPY_EXISTING ~BULL03.ITM~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 70				// colour index
			SET location = wgrey			// location
			LPM ~colour~
		END
	BUT_ONLY
END

// Bullets of Fire +2
ACTION_IF (FILE_EXISTS_IN_GAME ~UBULL4A.ITM~) BEGIN
	COPY_EXISTING ~UBULL4A.ITM~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			LPM ~clear~
			SET gradient = 115				// colour index
			SET location = wgrey			// location
			LPM ~colour~
		END
	BUT_ONLY
END



ACTION_FOR_EACH resource IN ~ARARROW.BAM~ ~MAGICSTN.BAM~ BEGIN
	COPY ~1pp/additions/projectiles_1pp/%resource%~ ~override~
END



ACTION_IF (NOT FILE_EXISTS_IN_GAME ~WPLSCA1.BAM~) BEGIN

	ACTION_FOR_EACH set IN ~SC~ BEGIN
		ACTION_FOR_EACH category IN ~L~ ~M~ ~S~ BEGIN
			ACTION_FOR_EACH sequence IN ~A1~ ~A1E~ ~A3~ ~A3E~ ~A5~ ~A5E~ ~G1~ ~G1E~ ~W2~ ~W2E~ BEGIN
				COPY_EXISTING ~WP%category%S1%sequence%.BAM~ ~override/WP%category%%set%%sequence%.BAM~
			END
		END
	END

END


// The Lucky Scimitar
ACTION_IF (FILE_EXISTS_IN_GAME ~lucky.itm~) BEGIN
	COPY_EXISTING ~lucky.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - Replace S1 Long sword
		END
	BUT_ONLY
END

// Cradle of Mielikki
ACTION_IF (FILE_EXISTS_IN_GAME ~mielikk.itm~) BEGIN
	COPY_EXISTING ~mielikk.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - Replace S1 Long sword
		END
	BUT_ONLY
END

// Scimitar
ACTION_IF (FILE_EXISTS_IN_GAME ~scimita.itm~) BEGIN
	COPY_EXISTING ~scimita.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - Replace S1 Long sword
		END
	BUT_ONLY
END

// Scimitar +3, Frostbrand
ACTION_IF (FILE_EXISTS_IN_GAME ~sw1h15.itm~) BEGIN
	COPY_EXISTING ~sw1h15.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - Replace S1 Long sword
		END
	BUT_ONLY
END

// Talon of the Gloomfrost
ACTION_IF (FILE_EXISTS_IN_GAME ~talongf.itm~) BEGIN
	COPY_EXISTING ~talongf.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - Replace S1 Long sword
		END
	BUT_ONLY
END

// Valiant
ACTION_IF (FILE_EXISTS_IN_GAME ~valiant.itm~) BEGIN
	COPY_EXISTING ~valiant.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - Replace S1 Long sword
		END
	BUT_ONLY
END

// Wind of Heaven
ACTION_IF (FILE_EXISTS_IN_GAME ~zzd5woh.itm~) BEGIN
	COPY_EXISTING ~zzd5woh.itm~ ~override~
		PATCH_IF (SOURCE_SIZE > 0x71) BEGIN	// protects against invalid files
			WRITE_ASCII 0x22 ~SC~			// Scimitar - Replace S1 Long sword
		END
	BUT_ONLY
END

//END of COMPONENT